Repository palantir/atlasdb, pull requests merged in 2018-07, with the labels that each got.

#3331 FFT - 1st ed., Part 5: Asynchronously Disengaging Representative (Async-Unlocker ADR)
  docs/source/miscellaneous/doc/adr/0015-batch-asynchronous-post-transaction-unlock-calls.md
Labels: component: documentation

#3101 Reduce a number of error and warn messages to lower logging levels.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/Blacklist.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingQueryRunner.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/SweepStatsKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingPrefsConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/AdjustableSweepBatchConfigSource.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  docs/source/release_notes/release-notes.rst
  lock-api/src/main/java/com/palantir/lock/client/LockRefreshingLockService.java
  lock-api/src/main/java/com/palantir/lock/client/LockRefreshingRemoteLockService.java
  qos-service-impl/src/main/java/com/palantir/atlasdb/qos/ratelimit/CassandraMetricMeasurementsLoader.java
  qos-service-impl/src/main/java/com/palantir/atlasdb/qos/ratelimit/QosRateLimiter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/clock/ClockSkewEvents.java
Labels: pr: needs review

#3381 Unflake test
  atlasdb-commons/src/test/java/com/palantir/async/initializer/CallbackTest.java
Labels: small

#3427 Fix async puncher to not roll over and die on exceptions
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/AsyncPuncher.java
  docs/source/release_notes/release-notes.rst
Labels: small

#3428 Get currentTimeMillis for targeted sweep metrics from timelock
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepableCellsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
Labels: small
