Repository palantir/atlasdb, pull requests merged in 2018-06, with the labels that each got.

#3245 PDS-69180 - CommitTsLoader is too aggressive when warming its cache
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CommitTsLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepableCellFilter.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/CommitTsLoaderTest.java
  docs/source/release_notes/release-notes.rst
Labels: priority: P0

#3261 Remove unused class + tests
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CountingIterator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/CountingIteratorShould.java
Labels: small

#3263 C* Timestamps, Part 2: Docs
  docs/source/miscellaneous/doc/adr/0013-write-cassandra-tombstones-and-sentinels-with-a-fresh-cassandra-timestamp.md
Labels: priority: P2

#3281 FFT Part 2: Timers For Setup and Finalization in SnapshotTransactionManager
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  docs/source/release_notes/release-notes.rst
Labels: component: metrics

#3290 People should use TimeLock, not reverse migrate
  docs/source/services/timelock_service/reverse-migration.rst
Labels: component: documentation

#3311 Moved CancelableServerCall annotation to commons-annotations
  commons-annotations/src/main/java/com/palantir/annotations/remoting/CancelableServerCall.java
Labels: small

#3327 [TS] Do not report metrics when no data on last swept timestamp
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
Labels: small

#3326 Actually rate limit detailed profile logging
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/logging/CommitProfileProcessor.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/logging/LogConsumerProcessor.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  docs/source/release_notes/release-notes.rst
Labels: priority: P1

#3319 FFT - getRowColumnRange Merge, Part 2: SortedMap -> List + Sort
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  docs/source/release_notes/release-notes.rst
Labels: component: performance
