Repository palantir/atlasdb, pull requests merged in 2018-03, with the labels that each got.

#3013 Shutdown Client Pool if Creating C*KVS Fails
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  docs/source/release_notes/release-notes.rst
Labels: type: bug

#3055 Fix sweep metrics to be updated by iteration results instead of cumulative results
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SpecificTableSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweeperServiceImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/BackgroundSweeperFastTest.java
  docs/source/release_notes/release-notes.rst
Labels: component: metrics, small

#3046 [MMM] Respond to docs feedback [no release notes]
  docs/source/troubleshooting/index.rst
Labels: component: documentation

#3073 Stream Store Backoff Between Blocks
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/AbstractPersistentStreamStore.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/StandardPeriodicBackoffStrategy.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/StreamStoreBackoffStrategy.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/StreamStorePersistenceConfiguration.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/stream/StandardPeriodicBackoffStrategyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfig.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfigDeserializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfigTest.java
  atlasdb-config/src/test/resources/runtime-config-block.yml
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataStreamStore.java
  docs/source/release_notes/release-notes.rst
Labels: needs verification

#3018 [PoC] Timestamp Corroboration Consistency Check
  atlasdb-api/src/main/java/com/palantir/atlasdb/factory/TransactionManagerConsistencyResult.java
  atlasdb-commons/build.gradle
  atlasdb-commons/src/main/java/com/palantir/async/initializer/Callback.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/CallChainTest.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/CallbackTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunner.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunnerTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/consistency/TimestampCorroborationConsistencyCheck.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/consistency/TransactionManagerConsistencyCheck.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/consistency/TimestampCorroborationConsistencyCheckTest.java
  docs/source/release_notes/release-notes.rst
Labels: component: timelock
