Repository palantir/atlasdb, pull requests merged in 2018-12, with the labels that each got.

#3597 _transactions2, Part 7: Burnin' Bridges / StartIdentifiedAtlasDbTransaction
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/ImmutableTimestampBridgingTimeLockService.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/ImmutableTimestampBridgingTimeLockServiceTest.java
  atlasdb-ete-tests/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  docs/source/release_notes/release-notes.rst
  lock-api/src/main/java/com/palantir/lock/v2/TimelockService.java
  timelock-server-benchmark-cluster/build.gradle
  timelock-server-distribution/build.gradle
Labels: pr: do not merge

#3669 Hotfix Publish + List of Canonical Product Dependencies To Ignore For Non-Standard Distributions
  atlasdb-cli-distribution/build.gradle
  atlasdb-console-distribution/build.gradle
  atlasdb-ete-tests/build.gradle
  gradle/non-client-dist.gradle
  timelock-server-benchmark-client/build.gradle
  timelock-server-benchmark-cluster/build.gradle
  timelock-server-distribution/build.gradle
Labels: priority: P0

#3690 [no release notes] Remove unused implementation of TSBS
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/SimpleKvsTimestampBoundStore.java
Labels: small
