Repository palantir/atlasdb, pull requests merged in 2018-04, with the labels that each got.

#3080 Fix Silent Merge Conflicts in TCCC Setup
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunner.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunnerTest.java
  docs/source/release_notes/release-notes.rst
Labels: pr: +1

#3075 Tagged Metrics for TimeLock: Clients and Leadership
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TaggedMetricsInvocationEventHandler.java
  docs/source/release_notes/release-notes.rst
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
Labels: pr: work in progress

#3090 Sweep Priority/Blacklist Overrides
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/SweepConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweeperImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/priority/NextTableToSweepProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/priority/SweepPriorityOverrideConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/SweeperTestSetup.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/priority/NextTableToSweepProviderTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/priority/SweepPriorityOverrideConfigTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  docs/source/cluster_management/sweep.rst
  docs/source/release_notes/release-notes.rst
Labels: component: sweep, needs verification

#3116 Include Cassandra semi-break in release notes
  docs/source/release_notes/release-notes.rst
  docs/source/services/key_value_services/index.rst
Labels: small
