Repository palantir/atlasdb, pull requests merged in 2019-12, with the labels that each got.

#4433 [LW] Lock Event Log Impl
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventVisitor.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchOpenLocksEvent.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchStateUpdate.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindow.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/NoOpLog.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindowTest.java
Labels: no changelog

#4451 [LW] Hacky LW Test Service
  lock-api/src/main/java/com/palantir/lock/watch/LockEvent.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCreatedEvent.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEvent.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventVisitor.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchOpenLocksEvent.java
  lock-api/src/main/java/com/palantir/lock/watch/UnlockEvent.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindow.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchTestRuntimeConfig.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchTestingService.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindowTest.java
Labels: autorelease, no changelog

#4453 [PDS-95791] Stop deserialising!
  atlasdb-config/src/main/java/com/palantir/atlasdb/debug/TransactionPostMortemRunner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/WritesDigestEmitter.java
  changelog/@unreleased/pr-4453.v2.yml
  examples/profile-client/src/test/java/com/palantir/example/profile/WritesDigestTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TransactionPostMortemIntegrationTest.java
Labels: autorelease

#4457 [Timelock Partitioning] Part 44d: Revert partitioning refactors
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  changelog/@unreleased/pr-4457.v2.yml
  leader-election-api/src/main/java/com/palantir/leader/LeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosTestState.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderElectionServiceFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/NetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockServicesCreator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosUseCase.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetrics.java
Labels: autorelease, merge when ready

#4461 Remove ThrowingCqlClientImpl
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsAsyncFallbackMechanismsTests.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CassandraAsyncKeyValueServiceFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/DefaultCassandraAsyncKeyValueServiceFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/CqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/ThrowingCqlClientImpl.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainer.java
  changelog/@unreleased/pr-4461.v2.yml
Labels: autorelease, merge when ready

#4463 Fix #tryUnlock.
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4463.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-impl/src/main/java/com/palantir/lock/impl/LegacyTimelockService.java
Labels: autorelease, merge when ready

#4465 Remove unnecessary boxing in getCommitTimestamps.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog

#4472 Increase number of retries in ClientOptions to 13
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  changelog/@unreleased/pr-4472.v2.yml
Labels: autorelease, merge when ready

#4469 fix infinite loop in LocalOrRemoteProxy
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/LocalOrRemoteProxy.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4469.v2.yml
Labels: autorelease

#4480 Fixed logging in AsyncTimeLockUnlocker.
  changelog/@unreleased/pr-4480.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/AsyncTimeLockUnlocker.java
Labels: autorelease, merge when ready

#3864 [LoggingArgs] Remove Unused Methods + Fix Semantics Mismatch
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/LoggingArgs.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/logging/LoggingArgsTest.java
Labels: no changelog

#4482 Fix typo in dynamic column docs.
  docs/source/schemas/tables_and_indices.rst
Labels: merge when ready, no changelog

#4485 [CJR] Refresh experimental clients every 30 minutes
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ExperimentRunningProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ExperimentRunningProxyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/VersionSelectingClients.java
  changelog/@unreleased/pr-4485.v2.yml
Labels: autorelease
