Repository palantir/atlasdb, pull requests merged in 2019-09, with the labels that each got.

#4197 CommitTsCache for targeted sweep expires entries after 5 minutes
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/AbortingCommitTsLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CommitTsCache.java
  changelog/@unreleased/pr-4197.v2.yml
Labels: autorelease, merge when ready

#4199 Factor out timestamp cache
  atlasdb-client/src/main/java/com/palantir/atlasdb/cache/DefaultTimestampCache.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/cache/TimestampCache.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/cache/TimestampCacheTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/@unreleased/pr-4199.v2.yml
Labels: autorelease, merge when ready

#4208 Expose TimeLockAgent#shutdown for graceful shutdown.
  changelog/@unreleased/pr-4208.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease, merge when ready

#4209 Do not log CassandraClients.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  changelog/@unreleased/pr-4209.v2.yml
Labels: autorelease, merge when ready

#4192 [Conjure Java Runtime] Part 2: Server Infrastructure - New ExceptionMappers, Custom Auxiliary Agents
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersion.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/BlockingTimeoutExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/HttpProtocolAwareExceptionTranslator.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotCurrentLeaderExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotInitializedExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/ProtocolAwareExceptionMapper.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersionTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/ProtocolAwareExceptionMapperTest.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersion.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbRemotingConstants.java
Labels: no changelog

#4193 [Conjure Java Runtime] Part 3: Target Factory
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbFeignTargetFactory.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/TargetFactory.java
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/runner/BenchmarkRunnerBase.java
Labels: no changelog

#4201 Stream Store Metadata Cleanup Task Recovery
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/SimpleTodoResource.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/TodoClient.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/TodoResource.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TargetedSweepEteTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsMetadataCleanupTask.java
  changelog/@unreleased/pr-4201.v2.yml
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosMetadataCleanupTask.java
Labels: autorelease

#4216 Fix Publishing: Don't publish intermediate artifactless project
  build.gradle
Labels: no changelog

#4217 Fix broken changelog
  changelog/@unreleased/pr-4213.v2.yml
Labels: autorelease

#4218 Block the 'examples' project by itself
  build.gradle
Labels: no changelog

#4215 Improve Throwables documentation
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
Labels: no release notes

#4221 Explicitly authorize KeyedStream.keys() in stream stores
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataMetadataCleanupTask.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsMetadataCleanupTask.java
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosMetadataCleanupTask.java
Labels: no changelog

#4224 Publish correct scm info within POM
  gradle/publish-jars.gradle
Labels: no changelog

#4223 Improve AbstractPoolingContainer log levels to reduce noise
  atlasdb-commons/src/main/java/com/palantir/common/pooling/AbstractPoolingContainer.java
  changelog/@unreleased/pr-4223.v2.yml
Labels: merge when ready

#4232 Lock refresh
  changelog/@unreleased/pr-4232.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LockRefresher.java
Labels: merge when ready

#4228 A quick hack to see the viability of table level conflict handling
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TableTransactionConflictManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
Labels: autorelease, no changelog

#4219 Remove some AtlasDB allocations
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/InstrumentationUtils.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowMetricsInvocationHandler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  changelog/@unreleased/pr-4219.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/LockTokenShare.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
  lock-api/src/test/java/com/palantir/lock/client/LockTokenShareTest.java
Labels: autorelease

#4210 Mark node as not eligible for leadership.
  changelog/@unreleased/pr-4210.v2.yml
  leader-election-api/src/main/java/com/palantir/leader/LeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/BatchingLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
Labels: autorelease, merge when ready

#4241 Revert "A quick hack to see the viability of table level conflict han…
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TableTransactionConflictManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-4241.v2.yml
Labels: autorelease, merge when ready

#4238 [Timelock Partioning] Part 28: Move timestamp paxos to runtime config.
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/ClientPaxosResourceFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
  timelock-server/src/testCommon/resources/paxosMultiServer0.yml
  timelock-server/src/testCommon/resources/paxosMultiServer1.yml
  timelock-server/src/testCommon/resources/paxosMultiServer2.yml
  timelock-server/src/testCommon/resources/paxosMultiServerBatch0.yml
  timelock-server/src/testCommon/resources/paxosMultiServerBatch1.yml
  timelock-server/src/testCommon/resources/paxosMultiServerBatch2.yml
Labels: no changelog

#4244 Use our own jackson decoder/encoder
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbFeignTargetFactory.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbJacksonDecoder.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbJacksonEncoder.java
  changelog/@unreleased/http-allocations.v2.yml
Labels: autorelease, merge when ready

#4242 Forming query strings with prefixed table names
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/query/forming/CacheQueryFormer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/query/forming/QueryFormer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/query/forming/SupportedQuery.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/query/forming/QueryFormingTest.java
Labels: no changelog

#4246 Single C*KVS for CassandraKeyValueServiceTransactionIntegrationTest
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTransactionIntegrationTest.java
Labels: no changelog

#4248 Docker proxy rule version bump
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/Containers.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/InterruptibleFileLogCollector.java
  scripts/circle-ci/run-circle-tests.sh
  versions.props
Labels: no changelog

#4249 Avoid extending Assert
  atlasdb-commons/src/test/java/com/palantir/common/base/ThrowablesTest.java
  commons-db/src/test/java/com/palantir/nexus/db/ThreadConfinedProxyTest.java
  commons-executors/src/test/java/com/palantir/common/concurrent/ExecutorInheritableThreadLocalTest.java
Labels: no changelog

#4251 [Timelock Partitioning] Part 29: Add in ability for use case aware single leader clients
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorAdapter.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorRpcClient.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosLearnerAdapter.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosLearnerRpcClient.java
Labels: no changelog

#4227 [Conjure Java Runtime] Part 7: Namespaced Timestamp Management RPC Client
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  timestamp-api/src/main/java/com/palantir/timestamp/RemoteTimestampManagementAdapter.java
  timestamp-api/src/main/java/com/palantir/timestamp/TimestampManagementRpcClient.java
Labels: no changelog

#4240 [Conjure Java Runtime] Part 8: Namespaced Lock and Nullable/Optional Bridging
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceCreator.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  lock-api/src/main/java/com/palantir/lock/LockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/NamespaceAgnosticLockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/client/NamespaceAgnosticLockClientAdaptor.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteLockServiceAdapter.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
Labels: no changelog

#4256 Get rid of unused config, and actually enable the dangerous flag.
  atlasdb-jepsen-tests/resources/atlasdb/timelock.yml
  changelog/@unreleased/pr-4256.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/config/ClusterConfiguration.java
  timelock-agent/src/test/java/com/palantir/timelock/config/ClusterConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/DefaultClusterConfigurationTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/config/ClusterConfiguration.java
  timelock-server-distribution/var/conf/timelock-db.yml
  timelock-server-distribution/var/conf/timelock-http2.yml
  timelock-server-distribution/var/conf/timelock-oracle.yml
  timelock-server-distribution/var/conf/timelock-postgres.yml
  timelock-server-distribution/var/conf/timelock.yml
  timelock-server/src/integTest/resources/paxosSingleServer.yml
  timelock-server/src/integTest/resources/paxosSingleServerWithNonBlockingAppender.yml
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/TimeLockServerConfiguration.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/TimeLockServerConfigurationTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstantsTest.java
Labels: autorelease

#4205 [Conjure Java Runtime] Part 4: Server-Side 308 Construction
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotCurrentLeaderExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/RedirectRetryTargeter.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/RedirectRetryTargeterTest.java
  changelog/@unreleased/pr-4205.v1.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosRemotingUtils.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/PaxosRemotingUtilsTest.java
Labels: autorelease

#4140 [Timelock Partitioning] Part 19: `AutobatchingLeaderPinger`
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/ClientAwarePingableLeader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactoryTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuidTests.java
Labels: no changelog

#4261 Pr 4140 follow ups
  timelock-impl/build.gradle
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPingableLeader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/ClientAwarePingableLeader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosUseCase.java
Labels: no changelog

#4262 [Timelock Partitioning] Part 31: Refactor to make leadership deps easy
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/ClientPaxosResourceFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockProxyFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosTimestampCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosLearnerResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosResources.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalAndRemotes.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosComponents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosUseCase.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockPaxosMetrics.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosResource.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: no changelog

#4267 Removed duplicate method
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
Labels: no changelog
