Repository palantir/atlasdb, pull requests merged in 2019-08, with the labels that each got.

#4161 Guard a couple debug logging statements with level checks
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueCleaner.java
Labels: no changelog, no release notes

#4158 AssertUtils.getDebuggingException returns a SafeLoggable Exception
  atlasdb-commons/build.gradle
  atlasdb-commons/src/main/java/com/palantir/util/AssertUtils.java
Labels: no changelog

#3974 Upgrade gradle-baseline to 0.57.0
  .circleci/config.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  build.gradle
  docs/source/release_notes/release-notes.rst
  flake-rule/src/test/java/com/palantir/flake/fail/ExpectedFailureRule.java
  gradle/baseline.gradle
  scripts/circle-ci/monitor-all-processes.sh
  scripts/circle-ci/run-circle-tests.sh
  versions.props
Labels: no changelog

#4163 Use better reservoir for TS metrics
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetrics.java
Labels: must be merged, no changelog

#4164 Allow dropping tables when not writing to the sweep queue
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4164.v2.yml
Labels: must be merged

#4171 Fix annotation processing in IntelliJ
  atlasdb-dagger/build.gradle
  atlasdb-perf/build.gradle
  atlasdb-processors/build.gradle
  build.gradle
  versions.props
Labels: component: devEx, no changelog

#4170 [Timelock Partitioning] Part 20: Proper usage of get learned values
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptCoalescingFunction.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosLearner.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosLearnerResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LearnedValuesCoalescingFunction.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PrepareCoalescingFunction.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/WithSeq.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/AcceptorCacheImplTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosLearnerResourceTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LearnedValuesCoalescingFunctionTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PrepareCoalescingFunctionTests.java
Labels: no changelog

#4173 File comparison test does not check __CLASS_HASH
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemaTest.java
Labels: no changelog

#4175 [Timelock Partitioning] Part 21: Integration pain points
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptorCacheKey.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/Client.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
Labels: no changelog

#4176 [Timelock Partitioning] Part 22: Fix up `BatcingPaxosLatestSequenceCache`.
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptor.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCache.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCacheTests.java
Labels: no changelog

#4182 [Timelock Partitioning] Part 24: Further separation of rpc layer and logical layer.
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptor.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptorRpcClient.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCache.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/InvalidAcceptorCacheKeyException.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosAcceptor.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosAcceptorAdapter.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptorResourceTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCacheTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosAcceptorTests.java
Labels: no changelog

#4184 Fix the build
  scripts/circle-ci/download-moreutils.sh
Labels: merge when ready, no changelog

#4188 Allow disabling read-write conflict checking on a per transaction basis.
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  changelog/@unreleased/pr-4188.v2.yml
Labels: autorelease

#4189 Fix Publishing
  changelog/@unreleased/pr-4180.v2.yml
Labels: autorelease

#4187 Cassandra driver and tracing lib version bump
  atlasdb-client/src/main/java/com/palantir/atlasdb/tracing/CloseableTrace.java
  changelog/@unreleased/pr-4187.v2.yml
  gradle/versions.gradle
  versions.props
Labels: autorelease

#4191 CachingTransaction correctly handles cache misses in #getRows.
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CachingTransactionTest.java
  changelog/@unreleased/pr-4191.v2.yml
Labels: autorelease, merge when ready

#4183 [Conjure Java Runtime] AtlasDB HTTP Schema Version Headers
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolHandler.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersion.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/HttpProtocolAwareExceptionTranslator.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotCurrentLeaderExceptionMapper.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersionTest.java
  atlasdb-feign/build.gradle
Labels: no changelog
