Repository palantir/atlasdb, pull requests merged in 2019-10, with the labels that each got.

#4271 Fix caching of config hostnames in cassandra client pool
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-4271.v2.yml
Labels: autorelease

#4265 [Conjure Java Runtime] Part 11: Transformable Polling Refreshables
  atlasdb-commons/src/main/java/com/palantir/util/CachedTransformingSupplier.java
  atlasdb-commons/src/test/java/com/palantir/util/CachedTransformingSupplierTest.java
Labels: no changelog

#4272 [Timelock Partitioning] Part 33: Clearer `LeadershipObserver`
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceCreator.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  leader-election-impl/src/main/java/com/palantir/leader/AsyncLeadershipObserver.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
Labels: no changelog

#4273 [Timelock Partitioning] Part 34: Extract `LocalPingableLeader`from the builder
  leader-election-impl/src/main/java/com/palantir/leader/LocalPingableLeader.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionServiceBuilder.java
Labels: no changelog

#4274 Create .changelog.yml
  .changelog.yml
Labels: no changelog

#4275 Additional config to allow allSafeForLogging on transaction manager level
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/KeyValueServiceLogArbitrator.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/LoggingArgs.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/logging/KeyValueServiceLogArbitratorTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/logging/LoggingArgsTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagersInitializer.java
  changelog/@unreleased/pr-4275.v2.yml
Labels: autorelease, merge when ready

#4277 Death to UserAgents
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-console/src/main/groovy/com/palantir/atlasdb/console/module/AtlasCoreModule.groovy
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  changelog/@unreleased/pr-4277.v2.yml
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/BenchmarksResource.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
Labels: autorelease, merge when ready

#4279 Enable binary compatibility.
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ImmutableTransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-console/src/main/groovy/com/palantir/atlasdb/console/module/AtlasCoreModule.groovy
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  changelog/@unreleased/pr-4279.v2.yml
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/BenchmarksResource.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
Labels: autorelease

#4268 Implement weighting by local rack when selecting cassandra hosts
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/EC2HostLocationSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocation.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplierTest.java
  atlasdb-container-test-utils/src/main/resources/docker-compose-cassandra.yml
  changelog/@unreleased/cass-az-awareness.v2.yml
Labels: autorelease, merge when ready

#4278 [Conjure Java Runtime] Part 13: SSL in Testing
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-config/var/security/keyStore.jks
  atlasdb-config/var/security/trustStore.jks
  atlasdb-ete-tests/Dockerfile
  atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra-async.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.dbkvs.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.multiple-cassandra-async.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.multiple-cassandra.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.client.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.timelock.cassandra.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.timelock.dbkvs.yml
  atlasdb-ete-tests/docker/security/keyStore.jks
  atlasdb-ete-tests/docker/security/trustStore.jks
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-ete-tests/var/security/keyStore.jks
  atlasdb-ete-tests/var/security/trustStore.jks
  atlasdb-jepsen-tests/var/security/keyStore.jks
  atlasdb-jepsen-tests/var/security/trustStore.jks
Labels: no changelog

#4280 Refactorings for old user agent form to new user agent form.
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/OneNodeDownGetTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-refactorings/build.gradle
  atlasdb-refactorings/src/main/java/com/palantir/atlasdb/refactorings/UseTypedUserAgentVsString.java
  atlasdb-refactorings/src/test/java/com/palantir/atlasdb/refactorings/UseTypedUserAgentVsStringTest.java
  changelog/@unreleased/pr-4280.v2.yml
  scripts/circle-ci/run-circle-tests.sh
  settings.gradle
  versions.props
Labels: autorelease

#4056 [_transactions2] Part 49: ADR Chapter 2
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoadingBatcher.java
  docs/source/miscellaneous/doc/adr/0016-cassandra-params.png
  docs/source/miscellaneous/doc/adr/0016-cellloader2-graph1.png
  docs/source/miscellaneous/doc/adr/0016-cellloader2-graph2.png
  docs/source/miscellaneous/doc/adr/0016-use-tickets-encoding-for-transactions.md
Labels: no changelog

#4281 Rename EC2 to Ec2 as per the docs
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplierTest.java
  changelog/@unreleased/pr-4281.v2.yml
Labels: autorelease, merge when ready

#4283 Fix Ec2HostLocationSupplier using a different format to Cassandra
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplierTest.java
  changelog/@unreleased/pr-4283.v2.yml
Labels: autorelease, merge when ready

#4284 Add licensce
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
Labels: no changelog

#4286 Add check for one datacenter being a prefix of the other
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocation.java
  changelog/@unreleased/pr-4286.v2.yml
Labels: autorelease, merge when ready

#4287 Async Puncher To Grab Fresh Timestamp If None Known At Punch Time
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/AsyncPuncher.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/DefaultCleanerBuilder.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/AsyncPuncherTest.java
  changelog/@unreleased/pr-4287.v2.yml
Labels: autorelease

#4288 Remove redundant default annotation in CassandraKeyValueServiceConfig
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
Labels: no changelog

#4270 Tunable CQL client creation
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientFactoryImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/ThrowingCqlClientImpl.java
Labels: no changelog

#4266 [Conjure Java Runtime] Part 12: Conjure Java Runtime Target Factory
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-feign/build.gradle
  atlasdb-feign/src/main/java/com/palantir/atlasdb/config/RemotingClientConfig.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/AtlasDbFeignTargetFactory.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/TargetFactory.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  changelog/@unreleased/pr-4266.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  versions.props
Labels: autorelease

#4290 apply plugin: 'com.palantir.revapi'
  .palantir/revapi.yml
  atlasdb-config/build.gradle
  build.gradle
Labels: no changelog

#4293 CQL config and factory additions
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientFactoryImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraServersConfigsTest.java
  atlasdb-cassandra/src/test/resources/testServersConfigCqlCapableDifferent.yml
Labels: no changelog

#4291 [Conjure Java Runtime] Part 14: Experiment Running Proxy and Data Collection
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ExperimentRunningProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ExperimentRunningProxyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/VersionSelectingClients.java
Labels: no changelog

#4295 Bumped tracing library
  changelog/@unreleased/pr-4295.v2.yml
  versions.props
Labels: autorelease

#4297 Convert client to memoized supplier
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
Labels: autorelease, no changelog

#4298 [Timelock Partitioning] Part 35: Learn should not be a quorum call
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPaxosLearnerNetworkClientFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LearnCoalescingConsumer.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LearnCoalescingConsumerTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: no changelog

#4296 Route 25% of queries to the same AZ for all services that use AtlasDB
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  changelog/@unreleased/pr-4296.v2.yml
Labels: autorelease, merge when ready

#4303 [CJR] Enable fast failovers
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/v2/FastFailoverProxy.java
  atlasdb-feign/src/test/java/com/palantir/atlasdb/http/v2/FastFailoverProxyTest.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
Labels: autorelease, no changelog

#4304 Listenable future refactoring for transaction get
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog

#4306 Remove most noisy logging
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplier.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategy.java
  atlasdb-coordination-impl/src/main/java/com/palantir/atlasdb/coordination/CoordinationServiceImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/TransactionSchemaManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  changelog/@unreleased/pr-4306.v2.yml
Labels: autorelease, merge when ready

#4308 Refactored parametrized tests for async.
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTransactionIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/GetSynchronousDelegate.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CachingTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
Labels: no changelog

#4314 [Timelock Partitioning] Part 37: Leadership components
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  leader-election-impl/src/main/java/com/palantir/leader/BatchingLeaderElectionService.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetrics.java
Labels: no changelog

#4311 Gzip compression
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/stream/StreamStoreDefinition.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/stream/StreamStoreDefinitionBuilder.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/AbstractGenericStreamStore.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/AbstractPersistentStreamStore.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-commons/src/main/java/com/palantir/common/compression/GzipCompressingInputStream.java
  atlasdb-commons/src/main/java/com/palantir/common/compression/LZ4CompressingInputStream.java
  atlasdb-commons/src/main/java/com/palantir/common/compression/StreamCompression.java
  atlasdb-commons/src/test/java/com/palantir/common/compression/StreamCompressionTests.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataStreamStore.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsStreamStore.java
  changelog/@unreleased/pr-4220.v2.yml
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosStreamStore.java
Labels: autorelease

#4319 Return and use `ManagedTimestampService` everywhere.
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigrators.java
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/timestamp/FastForwardTimestamp.java
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/timestamp/FetchTimestamp.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestFastForwardTimestampCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestSingleBackendCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestSweepCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestTimestampCommand.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/AtlasDbServices.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/LockAndTimestampModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/benchmarks/endpoint/TimestampServiceEndpoint.java
  changelog/@unreleased/pr-4319.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/DbBoundTimestampCreator.java
  timestamp-client/src/main/java/com/palantir/timestamp/DelegatingManagedTimestampService.java
  timestamp-client/src/test/java/com/palantir/timestamp/DelegatingManagedTimestampServiceTest.java
Labels: autorelease

#4300 Reap by immutable timestamp
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
Labels: no changelog

#4320 Update GZIP stream store compression changelog
  changelog/0.162.3/pr-4220.v2.yml
  changelog/0.162.3/pr-4311.v2.yml
Labels: merge when ready, no changelog

#4318 [Conjure Java Runtime] Part 15: Revise Parameters for ClientOptions
  atlasdb-feign/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  changelog/@unreleased/pr-4318.v2.yml
Labels: autorelease, merge when ready

#4324 Track total number of errors in version selecting clients
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AccumulatingValueMetric.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ExperimentRunningProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ExperimentRunningProxyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceCreator.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/VersionSelectingClients.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/VersionSelectingClientsTest.java
  changelog/@unreleased/pr-4324.v2.yml
Labels: autorelease

#4323 [Timelock Partitioning] Part 39: Have separate paxos leadership remote clients.
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorAdapter.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosLearnerAdapter.java
Labels: no changelog

#4315 [Timelock Partitioning] Part 38: Autobatching leadership observer
  .palantir/revapi.yml
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  leader-election-impl/src/main/java/com/palantir/leader/AsyncLeadershipObserver.java
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipObserver.java
  leader-election-impl/src/test/java/com/palantir/leader/AsyncLeadershipObserverTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AutobatchingLeadershipObserverFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java
Labels: no changelog

#4328 rev api fixes again...
  .palantir/revapi.yml
Labels: no changelog

#4329 Lazily create timers.
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowMetricsInvocationHandler.java
Labels: merge when ready, no changelog

#4327 [Timelock Partitioning] Part 40: `LeaderPinger` returns `PingResult`
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingResult.java
  leader-election-impl/src/main/java/com/palantir/paxos/LeaderPinger.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  leader-election-impl/src/test/java/com/palantir/leader/PaxosLeaderEventsTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/ClientAwarePingableLeader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PingCoalescingFunction.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactoryTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PingCoalescingFunctionTests.java
  versions.props
Labels: no changelog

#4332 [Timelock Partitioning] Part 41: Leadership wiring refactors
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosRuntimeConfiguration.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPingableLeaderResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosAcceptor.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosLearner.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosUseCase.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockPaxosMetrics.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimestampPaxosResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/BatchPingableLeaderResourceTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosAcceptorTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosLearnerTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: no changelog

#4322 Add Timed annotation and remove instrumentation from some TransactionManager methods
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/Timed.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TimedOnlyInstrumentationFilter.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/AtlasDbMetricsTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/TimedOnlyInstrumentationFilterTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
Labels: no changelog

#4334 Only whitelist certain KeyValueService methods for metrics.
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/AtlasDbMetricsTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
Labels: autorelease, no changelog

#4335 Only whitelist certain TransactionService methods for metrics.
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/service/TransactionService.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
Labels: autorelease, merge when ready, no changelog

#4337 Remove unused PersistentLockManager from BackgroundSweeperImpl.
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweeperImpl.java
Labels: no changelog

#4338 Cassandra Blacklist NPE fix
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/Blacklist.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/BlacklistTest.java
  changelog/@unreleased/pr-4338.v2.yml
Labels: autorelease

#4330 [CJR] Runtime config for disabling experiment fallbacks
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ExperimentRunningProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ExperimentRunningProxyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/VersionSelectingClients.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/VersionSelectingClientsTest.java
  atlasdb-feign/src/main/java/com/palantir/atlasdb/config/RemotingClientConfig.java
Labels: autorelease, no changelog

#4333 [Timelock Partitioning] Part 42: `LeadershipMetrics` propagates its client.
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipEvents.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeadershipEventRecorder.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosLeadershipCreator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingLeadershipObserverFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetrics.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockPaxosMetrics.java
Labels: no changelog

#4341 Remove SweepOutcome.SHUTDOWN.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweeperImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcome.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetrics.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
Labels: no changelog

#4331 Only whitelist certain CassandraClient methods for metrics.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientImpl.java
Labels: autorelease, no changelog

#4342 Remove SweepOutcome.DISABLED.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcome.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
Labels: merge when ready, no changelog

#4344 [Transaction Async get] Part 1: Return type for getWithPostFiltering
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog

#4343 Make SweepOutcomeMetrics lazily register gauges.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/LegacySweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetrics.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
Labels: autorelease, no changelog

#4336 [Timelock Partitioning] Part 43: `LocalPaxosComponents` knows about `LocalPingableLeader`
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: no changelog

#4354 Route 50% of queries to the same AZ
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  changelog/@unreleased/pr-4354.v2.yml
Labels: autorelease

#4355 Run Tests With Postgres 9.6
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.yml
  atlasdb-ete-tests/docker-compose.dbkvs.yml
  atlasdb-ete-tests/docker-compose.timelock.database.bound.postgres.yml
  atlasdb-perf/src/main/resources/postgres-docker-compose.yml
  scripts/circle-ci/common-containers.yml
Labels: no changelog

#4345 [Transaction Async get] Part 2: Refactored TransactionService and futures helper.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/futures/AtlasFutures.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/AsyncTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/PreStartHandlingTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SplitKeyDelegatingTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/WriteBatchingTransactionService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/service/PreStartHandlingTransactionServiceTest.java
Labels: no changelog

#4358 Fail loudly when a closed LockRefreshingLockService is used
  changelog/@unreleased/pr-4358.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LockRefreshingLockService.java
  lock-impl/src/test/java/com/palantir/lock/client/LockRefreshingLockServiceTest.java
Labels: autorelease

#4360 [Conjure Java Runtime] Part 16: Revising Project Paths, Fix FastFailoverProxy
  atlasdb-autobatch/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-client/build.gradle
  atlasdb-commons/build.gradle
  atlasdb-config/build.gradle
  atlasdb-conjure/build.gradle
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/FastFailoverProxy.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/FastFailoverProxyTest.java
  atlasdb-console/build.gradle
  atlasdb-feign/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-remoting-api/build.gradle
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/AuxiliaryRemotingParameters.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/RemotingClientConfig.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/ServerListConfig.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersion.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/http/AtlasDbRemotingConstants.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/http/PollingRefreshable.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/http/TargetFactory.java
  atlasdb-remoting-api/src/test/java/com/palantir/atlasdb/http/PollingRefreshableTest.java
  atlasdb-tests-shared/build.gradle
  changelog/@unreleased/pr-4360.v2.yml
  gradle/versions.gradle
  leader-election-impl/build.gradle
  lock-api/build.gradle
  lock-impl/build.gradle
  settings.gradle
  timelock-server/build.gradle
  timestamp-impl/build.gradle
  versions.props
Labels: autorelease

#4365 [0.121.x] Disable ErrorProne to unblock hotfix releases
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog

#4347 [Transaction Async get] Part 4: Listenable futures for getCommitTimestamps.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
Labels: no changelog

#4366 [Conjure Java Runtime] Part 18: Internode Support
  .palantir/revapi.yml
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/LockWithTimelockEteTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TimeLockMigrationEteTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  changelog/@unreleased/pr-4366.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/IsolatedPaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/ExceptionMatchers.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxies.java
Labels: autorelease
