Repository palantir/atlasdb, pull requests merged in 2019-11, with the labels that each got.

#4370 [Conjure Java Runtime] Part 19: Retrying is Futile... Sometimes.
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TimeLockMigrationEteTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  changelog/@unreleased/pr-4370.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/IsolatedPaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxies.java
Labels: autorelease

#4349 [Transaction Async get] Part 5: Async path on getWithPostFilteringFuture and getFromKeyValueSevice
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AsyncKeyValueService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/KeyValueServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog

#4374 Fix deadlock in static class initialization
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/api/WriteReference.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  changelog/@unreleased/pr-4374.v2.yml
Labels: autorelease

#4376 Table creation metadata tests
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
Labels: no changelog

#4368 [Transaction Async get] Part 6: Catch unintentional switches between blocking and non-blocking calls during tests.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/GetAsyncDelegate.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/PathTypeTracker.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/PathTypeTrackers.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/WrapperWithTracker.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
Labels: no changelog

#4381 [RevAPI] Set reference point and acknowledge breaks correctly
  .palantir/revapi.yml
Labels: autorelease, no changelog

#4383 Do not use RevAPI for Atlas
  .palantir/revapi.yml
  atlasdb-config/build.gradle
  build.gradle
Labels: no changelog

#4375 CQL driver version bump
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-multinode-tests/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraServersConfigs.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTableCreator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientFactoryImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/ThrowingCqlClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/CqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/CqlClientFactoryImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DelegatingNettyOptions.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/CqlQuerySpec.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/GetQuerySpec.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/RowAccumulator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/statement/preparing/CachingStatementPreparer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/statement/preparing/StatementPreparer.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraServersConfigsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CachingStatementPreparerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientImplTests.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/futures/AtlasFutures.java
  changelog/@unreleased/pr-4375.v2.yml
  gradle/versions.gradle
  versions.props
Labels: autorelease

#4391 Remove a bunch of deprecated and unused code
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java
Labels: no changelog

#4395 Revert "CQL driver version bump (#4375)"
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-multinode-tests/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraServersConfigs.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTableCreator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientFactoryImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/ThrowingCqlClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/CqlClientFactoryImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DelegatingNettyOptions.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/CqlQuerySpec.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/GetQuerySpec.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/RowStreamAccumulator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/statement/preparing/CachingStatementPreparer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/statement/preparing/StatementPreparer.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraServersConfigsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CachingStatementPreparerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientImplTests.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/futures/AtlasFutures.java
  changelog/@unreleased/pr-4395.v2.yml
  gradle/versions.gradle
  versions.props
Labels: autorelease

#4390 [LW] (Real) Part 1: Registration and Deregistration APIs
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/KvsLockWatchingService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/NoOpKvsLockWatchingService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/RowReference.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/WatchIdToRowReferenceMapping.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatch.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchRequest.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchState.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchingRpcClient.java
  lock-api/src/main/java/com/palantir/lock/watch/NamespacedLockWatchingRpcClient.java
  lock-api/src/main/java/com/palantir/lock/watch/WatchId.java
  lock-api/src/main/java/com/palantir/lock/watch/WatchIdToLockDesciptor.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
Labels: no changelog

#4392 [LW] Part 2: Transaction Related LW APIs
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/GuardedValue.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/LockWatchingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/NoOpLockWatchingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/NoOpTransactionLockWatchingCacheView.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/RowLockDescriptorMapping.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionLockWatchingCacheView.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  lock-api/src/main/java/com/palantir/lock/v2/StartTransactionWithWatchesResponse.java
  lock-api/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-api/src/main/java/com/palantir/lock/watch/TimestampedLockResponse.java
Labels: no changelog

#4401 Do not delegate for new API with default implementations
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  lock-api/src/main/java/com/palantir/lock/v2/TimelockService.java
Labels: no changelog

#4378 AsyncPuncherTest shuts down AsyncPuncher instances
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/AsyncPuncherTest.java
Labels: no changelog

#4388 [PDS-95791] Lock diagnostics
  atlasdb-config/src/main/java/com/palantir/atlasdb/debug/TransactionPostMortemRunner.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/ClientLockDiagnosticCollector.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/ClientLockDiagnosticCollectorImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/ConflictTracer.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/FullDiagnosticDigest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticInfo.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticInfoService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticTimelockRpcClient.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockInfo.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/WritesDigest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/WritesDigestEmitter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/TransactionConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/@unreleased/pr-4388.v2.yml
  examples/profile-client/src/test/java/com/palantir/example/profile/WritesDigestTest.java
  lock-api/src/main/java/com/palantir/lock/v2/TimelockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/v2/WaitForLocksRequest.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/CombinedLockEvents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/HeldLocks.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/HeldLocksCollection.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockAcquirer.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockDiagnosticCollector.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockEvents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LoggingLockEvents.java
  timelock-server/build.gradle
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TransactionPostMortemIntegrationTest.java
  timelock-server/src/integTest/resources/paxosSingleServer.yml
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/HeldLocksCollectionTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/HeldLocksTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
Labels: priority: P0

#4404 [Conjure Java Runtime] Part 22: Martin Lewis's Muse
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-coordination-impl/src/main/java/com/palantir/atlasdb/coordination/CoordinationService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/CoordinationServices.java
  commons-annotations/src/main/java/com/palantir/atlasdb/metrics/Timed.java
  leader-election-api/src/main/java/com/palantir/leader/LeaderElectionService.java
  leader-election-api/src/main/java/com/palantir/leader/PingableLeader.java
  leader-election-api/src/main/java/com/palantir/paxos/PaxosAcceptor.java
  leader-election-api/src/main/java/com/palantir/paxos/PaxosLearner.java
  leader-election-api/src/main/java/com/palantir/paxos/PaxosProposer.java
Labels: no changelog

#4403 [Conjure Java Runtime] Part 21: Global Conjuration
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/AuxiliaryRemotingParameters.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/RemotingClientConfigs.java
  changelog/@unreleased/pr-4403.v2.yml
Labels: autorelease

#4407 [Conjure Java Runtime] Part 23 - Guest PR: Random retries
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/RedirectRetryTargeter.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/RedirectRetryTargeterTest.java
  changelog/@unreleased/pr-4407.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/ExceptionMatchers.java
Labels: autorelease

#4408 Upgrade CJR
  changelog/@unreleased/pr-4408.v2.yml
  versions.props
Labels: autorelease

#4410 Fun with AutoDelegates <3
  changelog/@unreleased/pr-4410.v2.yml
  lock-api/src/main/java/com/palantir/lock/v2/TimelockService.java
Labels: autorelease

#4409 [Conjure Java Runtime] Part 24: Removing Feign From Jepsen, TM Test and ADHC Test
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotCurrentLeaderExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/RedirectRetryTargeter.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/VersionSelectingClients.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/RedirectRetryTargeterTest.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-jepsen-tests/src/jepsen/atlasdb/lock.clj
  atlasdb-jepsen-tests/src/jepsen/atlasdb/timestamp.clj
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/AsyncLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/SynchronousLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimelockUtils.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimestampClient.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/http/TargetFactory.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxies.java
Labels: no changelog

#4413 [Conjure Java Runtime] Part 25: Fast Failover Proxy Needs To Be Used On Non-Live-Reloadable Paths
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  changelog/@unreleased/pr-4413.v2.yml
Labels: autorelease

#4405 [Timelock Partitioning] Part 46: Test reorganisation/refactor
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceTargetedSweepRateLimitingTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/IsolatedPaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/NonBlockingAppenderIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/SingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/suite/PaxosSuite.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxies.java
Labels: no changelog

#4417 Default to 100% local host weighting
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  changelog/@unreleased/pr-4417.v2.yml
Labels: autorelease, merge when ready

#4425 Fix develop
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  leader-election-api/src/main/java/com/palantir/leader/LeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosTestState.java
Labels: no changelog

#4398 add metrics to scrubber
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/DefaultCleanerBuilder.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/cleaner/ScrubberTest.java
  changelog/@unreleased/pr-4398.v2.yml
Labels: autorelease

#4439 Number of hosts in C* config fix.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraServersConfigs.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServices.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/DefaultCassandraAsyncKeyValueServiceFactory.java
  changelog/@unreleased/pr-4439.v2.yml
Labels: autorelease

#4435 [PDS-10{3841,4895}] Part 2: Stream Diagnostics
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataMetadataCleanupTask.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueMetadataCleanupTask.java
  changelog/@unreleased/pr-4435.v2.yml
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosMetadataCleanupTask.java
Labels: autorelease

#4442 Prevent exceptions for 0 CQL contact points
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/DefaultCassandraAsyncKeyValueServiceFactory.java
  changelog/@unreleased/pr-4442.v2.yml
Labels: autorelease, merge when ready

#4444 [PDS-10{3841,4895}] Part 5: Don't Reuse Streams In The Stream Store
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/AbstractPersistentStreamStore.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/StreamTest.java
  changelog/@unreleased/pr-4444.v2.yml
Labels: P0 follow-up, autorelease

#4446 Tracing for futures processing.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/futures/AtlasFutures.java
  changelog/@unreleased/pr-4446.v2.yml
Labels: autorelease, merge when ready

#4447 Increase the timeout on CQL queries.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
  changelog/@unreleased/pr-4447.v2.yml
Labels: autorelease, merge when ready

#4448 [Timelock Partitioning] Part 44b: Ensure same instance of `LeaderElectionService` is reused
  changelog/@unreleased/pr-4448.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderElectionServiceFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
Labels: autorelease

#4450 [Timelock Partitioning] Part 44c: Restore batching behaviour.
  changelog/@unreleased/pr-4450.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderElectionServiceFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
Labels: autorelease
