Repository palantir/atlasdb, pull requests merged in 2020-07, with the labels that each got.

#4875 Remove duplicate metrics from TimelockAgent.createSharedExecutor
  changelog/@unreleased/pr-4875.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease, merge when ready

#4877 Borrow WC variants of executor views to reduce thread count and increase reuse
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/DefaultCassandraAsyncKeyValueServiceFactory.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  changelog/@unreleased/pr-4877.v2.yml
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasQueuedViewExecutor.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasQueuelessViewExecutor.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasRenamingExecutorService.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasUncaughtExceptionHandler.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasViewExecutor.java
  commons-executors/src/main/java/com/palantir/common/concurrent/NamedThreadFactory.java
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
Labels: merge when ready

#4880 Upgrade dialogue
  changelog/@unreleased/pr-4880.v2.yml
  commons-executors/src/test/java/com/palantir/common/concurrent/PTExecutorsTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#4882 Fix baseline error prone ExecutorSubmitRunnableFutureIgnored
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/CoalescingSupplier.java
  changelog/@unreleased/pr-4882.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/invariants/NoSimultaneousServiceCheck.java
Labels: merge when ready

#4869 Namespace in TM
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-4869.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
  timelock-api/src/main/conjure/timelock-feedback.yml
Labels: autorelease, merge when ready

#4884 QueuedViewExecutor concurrency: state is guarded by lock
  changelog/@unreleased/pr-4884.v2.yml
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasQueuedViewExecutor.java
Labels: autorelease, merge when ready

#4883 Atlas dialogue consumption provides a ptexecutor cached pool
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-4883.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: merge when ready

#4885 Add original client namespace while sending adjudication feedback
  changelog/@unreleased/pr-4885.v2.yml
  lock-api-objects/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackResource.java
Labels: autorelease

#4886 Add logging to initialisation path
  atlasdb-commons/src/main/java/com/palantir/async/initializer/Callback.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-4886.v2.yml
Labels: autorelease

#4887 PTExecutors fixed executor views handle shutdown after termination
  changelog/@unreleased/pr-4887.v2.yml
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasQueuedViewExecutor.java
Labels: autorelease, merge when ready

#4878 [PD$-110002] Part 9: Cassandra Client Pool II - Distribution Outlier Controllers
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolHostLevelMetric.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetrics.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/DistributionOutlierController.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetricsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/DistributionOutlierControllerTest.java
  changelog/@unreleased/pr-4878.v2.yml
Labels: autorelease

#4894 [LW] Test for lock watch updates that are too far behind
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
Labels: merge when ready, no changelog

#4889 Tweak acceptable request rate
  changelog/@unreleased/pr-4889.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/Constants.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackHandler.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/ServiceLevelObjectiveSpecification.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackAnalysisTest.java
Labels: autorelease, pr: needs review

#4892 [PD$-110002] Part 10: Top-N Tables | Primitives
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TopNMetricPublicationController.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/TopNMetricPublicationControllerTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/ZeroBasedDeltaGauge.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/ZeroBasedDeltaGaugeTest.java
Labels: no changelog

#4898 CassandraClientPoolHostLevelMetric fields final
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolHostLevelMetric.java
Labels: no changelog

#4890 Adjudication logs
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/Constants.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackHandler.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/HealthStatus.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/ServiceLevelObjectiveSpecification.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/PointHealthReportAnalysisTest.java
Labels: merge when ready, no changelog

#4893 [PD$-110002] Part 11: Top-N Tables | Toplist Delta Filtering Controller
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/MetricsManagers.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TopNMetricPublicationController.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/TopNMetricPublicationControllerTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/SimpleTableLevelMetricsController.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TableLevelMetricsController.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/ToplistDeltaFilteringTableLevelMetricsController.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/ToplistDeltaFilteringTableLevelMetricsControllerTest.java
Labels: no changelog

#4905 Make all logging HikariCPConnectionManager SLS
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  changelog/@unreleased/pr-4905.v2.yml
Labels: merge when ready

#4896 [PDS-126257] Setting Fire to the Rain: Killing the SharedExecutor
  changelog/0.237.1-rc1/pr-4896.v2.yml
  changelog/0.237.1-rc2/pr-4896.v2.yml
  changelog/@unreleased/pr-4896.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderLearnerNetworkClient.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/LockCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorAdapters.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosLearnerAdapters.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutorsTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPaxosLearnerNetworkClientFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LearnCoalescingConsumer.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalAndRemotes.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosLearnerAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/WithDedicatedExecutor.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LearnCoalescingConsumerTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: :white_check_mark: Prod validated, autorelease

#4908 [LW] Fix exception handling in ResilientLockWatchEventCache
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCacheTest.java
  changelog/@unreleased/pr-4908.v2.yml
Labels: merge when ready

#4914 [PDS-127937] Distinct Executors for Pinging as Opposed to Paxos
  changelog/@unreleased/pr-4914.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClientsTest.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutorsTest.java
  timelock-agent/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: autorelease

#4909 [PDS-127999] Improved Corroboration Checker
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/TimestampCorroboratingTimelockService.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/TimestampCorroboratingTimelockServiceTest.java
  changelog/@unreleased/pr-4909.v2.yml
Labels: autorelease

#4917 [PDS-127121] Log refreshed Cassandra hosts at info level
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  changelog/@unreleased/pr-4917.v2.yml
Labels: merge when ready

#4918 Only log if auto-refresh is on.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-4918.v2.yml
Labels: autorelease, merge when ready

#4681 [PDS-114184] Make Atlas CLI Validate Step Use Many Transactions
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/schema/KeyValueServiceValidator.java
  changelog/@unreleased/pr-4681.v2.yml
Labels: merge when ready

#4919 add jenv file
  .java-version
Labels: merge when ready, no changelog

#4900 [PDS-125544] Configurable, Instrumented Feedback Sink
  changelog/@unreleased/pr-4900.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockAdjudicationConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockAdjudicationConfigurationTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackHandler.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackSink.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackAnalysisTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackHandlerTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/PointHealthReportAnalysisTest.java
  timelock-impl/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: autorelease

#4922 Remove local vs remote host selected metric
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-4922.v2.yml
Labels: merge when ready

#4907 Leader election rate
  changelog/@unreleased/pr-4907.v2.yml
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipEvents.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeadershipEventRecorder.java
  leader-election-impl/src/main/java/com/palantir/leader/health/LeaderElectionHealthCheck.java
  leader-election-impl/src/main/java/com/palantir/leader/health/LeaderElectionHealthStatus.java
  leader-election-impl/src/main/metrics/leader-election.yml
  leader-election-impl/src/test/java/com/palantir/leader/LeadershipElectionCheckTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: pr: needs revision

#4920 [PD$-110002] Part 12: Only Publish Top Ten Table Metrics
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-4920.v2.yml
Labels: autorelease

#4906 [TimeLock blue-green] PingV2 | ping gets version of timeLock on remote server with leader info
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4906.v2.yml
  leader-election-api/build.gradle
  leader-election-api/src/main/java/com/palantir/leader/PingResult.java
  leader-election-api/src/main/java/com/palantir/leader/PingableLeader.java
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/leader/LocalPingableLeader.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClientsTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
  timelock-server-benchmark-cluster/src/main/java/com/palantir/atlasdb/timelock/benchmarks/server/TimelockBenchmarkServerLauncher.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
  versions.lock
  versions.props
Labels: autorelease

#4921 [PD$-110002] Part 13: Filter Resiliency
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationArbiter.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/MetricPublicationArbiterTest.java
  changelog/@unreleased/pr-4921.v2.yml
Labels: autorelease
