Repository palantir/atlasdb, pull requests merged in 2020-10, with the labels that each got.

#5011 [DB TimeLock] 1B, 1C: DB TimeLock for Multiple Series
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTestSuite.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/PostgresEmbeddedDbTimestampBoundStoreTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/PostgresMultiSeriesDbTimestampBoundStoreTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/InDbTimestampBoundStore.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/LegacyPhysicalBoundStoreStrategy.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/MultiSequencePhysicalBoundStoreStrategy.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/PhysicalBoundStoreDatabaseUtils.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/PhysicalBoundStoreStrategy.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/TimestampSeries.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcAtlasDbFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/DbBoundTimestampCreator.java
Labels: no changelog

#5010 Dbkvs invalidate
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKvsPostgresInvalidationRunnerTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTestSuite.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidator.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/InvalidationRunner.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/CreateTimestampTableQueries.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/LegacyPhysicalBoundStoreStrategy.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/PhysicalBoundStoreDatabaseUtils.java
  changelog/@unreleased/pr-5010.v2.yml
Labels: pr: needs revision

#5016 Revert 5010
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKvsPostgresInvalidationRunnerTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTestSuite.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidator.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/InvalidationRunner.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/CreateTimestampTableQueries.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/LegacyPhysicalBoundStoreStrategy.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/PhysicalBoundStoreDatabaseUtils.java
Labels: autorelease, merge when ready, no changelog

#5014 [DB TimeLock] 1D - Agent Wiring
  atlasdb-api/build.gradle
  atlasdb-api/src/main/java/com/palantir/atlasdb/config/DbTimestampCreationSetting.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TimestampSeries.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/AtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/timestamp/TimestampCreationParametersCheck.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/timestamp/TimestampCreationParametersCheckTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplier.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AutoServiceAnnotatedAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactory.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/PostgresMultiSeriesDbTimestampBoundStoreTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/InDbTimestampBoundStore.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/MultiSequencePhysicalBoundStoreStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcAtlasDbFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/DbBoundTimestampCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/DbBoundTimestampCreatorTest.java
Labels: no changelog

#5019 Revert revert dvkvs invalidator
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKvsPostgresInvalidationRunnerTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTestSuite.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidator.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/InvalidationRunner.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleErrorConstants.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/CreateTimestampTableQueries.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/LegacyPhysicalBoundStoreStrategy.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/PhysicalBoundStoreDatabaseUtils.java
  changelog/0.249.1-rc1/pr-5019.v2.yml
Labels: autorelease, no changelog

#5029 Upgrade RocksDB-JNI
  changelog/@unreleased/pr-5029.v2.yml
  versions.lock
  versions.props
Labels: autorelease

#5031 [LW] Check for bad version in the right place
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-5031.v2.yml
Labels: autorelease, merge when ready

#5025 [DB TimeLock] 3B.2 - DbTimeLockSingleLeaderPaxosSuite
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/suite/DbTimeLockSingleLeaderPaxosSuite.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServerConfiguration.java
  timelock-server/src/testCommon/resources/dbTimeLockPaxosMultiServer.ftl
Labels: no changelog

#5032 [TS] Parallelism is nice and should be respected
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ScalingSweepTaskScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ScalingSweepTaskSchedulerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepDelayTest.java
  changelog/@unreleased/pr-5032.v2.yml
Labels: autorelease, merge when ready

#5027 [DB TimeLock] 1D.2/3C.1 - Validation of DB TimeLock Multiple Series Mode
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: no changelog

#5035 Fix CR nits from automerged PR
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
Labels: merge when ready, no changelog

#5026 Double check that the SQLite migration is consistent with current state
  changelog/@unreleased/pr-5026.v2.yml
  leader-election-api/src/main/java/com/palantir/paxos/PaxosValue.java
  leader-election-api/src/main/java/com/palantir/paxos/Versionable.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorState.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosAcceptorStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
Labels: merge when ready

#5033 Wire invalidator 2
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/AtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplier.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKvsPostgresInvalidationRunnerTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidatorCreationTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTestSuite.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  changelog/@unreleased/pr-5033.v2.yml
Labels: autorelease

#5037 Fix broken build after 5033
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidatorCreationTest.java
Labels: merge when ready, no changelog

#5039 [LW] Don't compare Longs using ==
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-5039.v2.yml
Labels: autorelease, merge when ready

#5040 LockWatchManager#isEnabled.
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCacheTest.java
  changelog/@unreleased/pr-5040.v2.yml
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
Labels: autorelease, merge when ready

#5045 Read from palantir system table to try and use hostnames instead of ips
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostnamesByIpSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostnamesByIpSupplierTest.java
  changelog/@unreleased/pr-5045.v2.yml
Labels: autorelease, merge when ready

#5038 make oracle protocol case insensitive
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionProtocol.java
  atlasdb-dbkvs-hikari/src/test/java/com/palantir/nexus/db/pool/config/OracleConnectionConfigTest.java
  changelog/@unreleased/pr-5038.v2.yml
Labels: autorelease, merge when ready

#5046 reduce log level.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-5046.v2.yml
Labels: merge when ready

#5051 Enforce error-prone InputStreamSlowMultibyteRead
  atlasdb-commons/src/main/java/com/palantir/common/compression/StreamCompression.java
  build.gradle
Labels: merge when ready, no changelog

#5055 ./gradlew format
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/ClusterAvailabilityStatusTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/KeyAlreadyExistsExceptionTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/SweepResultsTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/TableReferenceTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/transaction/api/KeyValueServiceStatusTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceGetRowKeysInRangeTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceSweepTaskRunnerIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTimestampIntegrationTest.java
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/CassandraSchemaLockTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactoryTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfigTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraApiVersionTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceConfigTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandlerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitionsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/HiddenTablesTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/RetryableCassandraRequestTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/WeightedHostsTest.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestKvsMigrationCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestScrubQueueMigrationCommand.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/IterablePartitionerTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueServiceTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/SweepStatsKeyValueServiceTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueServiceTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ConflictHandlersTest.java
Labels: merge when ready

#5050 Remove StreamOfEmpty from the error-prone allow-list
  build.gradle
Labels: merge when ready, no changelog

#5036 [TL] Persist Schema Version in Sqlite
  changelog/@unreleased/pr-5036.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PersistedSchemaVersion.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/PersistedSchemaVersionTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
Labels: merge when ready

#5064 [LE] Implement SlidingWindowWeightedMeanGauge
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowWeightedMeanGauge.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/SlidingWindowWeightedMeanGaugeTest.java
  changelog/@unreleased/pr-5064.v2.yml
Labels: merge when ready

#5057 [TimeLock corruption detection] | Timestamp corruption checks
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionCheckViolation.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionStatus.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/HistoryAnalyzer.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/RemoteCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/handle/CorruptionNotifierResource.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/handle/JerseyCorruptionFilter.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/handle/LocalCorruptionHandler.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/handle/UndertowCorruptionHandlerService.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/models/CompletePaxosHistoryForNamespaceAndUseCase.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/models/ConsolidatedLearnerAndAcceptorRecord.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/models/LearnedAndAcceptedValue.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/HistoryLoaderAndTransformerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/SqliteHistoryQueriesTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/utils/PaxosSerializationTestUtils.java
Labels: no changelog, pr: needs revision

#5072 Lock lease service should short circuit on unlock
  changelog/@unreleased/pr-5072.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
Labels: autorelease, merge when ready

#5062 Leader Election Metrics 1a: Client Side Wiring
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/AsyncLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimestampClient.java
  gradle/shared.gradle
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockServiceImpl.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
  lock-api/src/main/metrics/metric-schema.yml
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
  lock-api/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
Labels: autorelease, merge when ready, no changelog

#5073 Unify LeaderClock's LeadershipId with Lock Watch Log's Leader ID
  changelog/@unreleased/pr-5073.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/LeadershipId.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
Labels: merge when ready

#5074 Do not kill timelock for no reason
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
Labels: autorelease, no changelog

#5076 [TS] Tune sweepdelay metrics
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepDelayTest.java
Labels: autorelease, merge when ready, no changelog

#5071 [Timelock Corruption]: Final Wiring part 1
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockCorruptionComponents.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionCheckViolation.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionHealthCheck.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionHealthReport.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionStatus.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/HistoryAnalyzer.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/RemoteCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/handle/JerseyCorruptionFilter.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/handle/UndertowCorruptionHandlerService.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
Labels: autorelease, no changelog

#5069 Leader Election Metrics 1b: Estimate Leader Election Duration
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
Labels: no changelog

#5081 Fail on compiler warnings
  atlasdb-api/build.gradle
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/CoalescingBatchingEventHandlerTests.java
  atlasdb-cassandra/build.gradle
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/output/OutputPrinter.java
  atlasdb-client-protobufs/build.gradle
  atlasdb-client/build.gradle
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SerializingUtils.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/service/WriteBatchingTransactionServiceTest.java
  atlasdb-tests-shared/build.gradle
  build.gradle
  commons-executors/build.gradle
  examples/profile-client-protobufs/build.gradle
  leader-election-api-protobufs/build.gradle
  leader-election-impl/build.gradle
  lock-api/src/test/java/com/palantir/lock/client/TestBatchElement.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuidTests.java
  timelock-server/build.gradle
  timestamp-client/src/test/java/com/palantir/timestamp/RequestBatchingTimestampServiceTest.java
Labels: merge when ready, no changelog

#5060 Match dialogue read/write timeout
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/DialogueClientOptions.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/DialogueClientOptionsTest.java
  changelog/@unreleased/pr-5060.v2.yml
Labels: autorelease

#5082 Enforce more error-prone checks
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/DistributionOutlierController.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/ThriftObjectSizeUtilsTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/cache/DefaultOffHeapCache.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/ValueType.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategy.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TopNMetricPublicationController.java
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
  atlasdb-commons/src/main/java/com/palantir/common/random/SecureRandomPool.java
  atlasdb-commons/src/main/java/com/palantir/util/debug/StackTraceUtils.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/AsyncInitializerTest.java
  atlasdb-commons/src/test/java/com/palantir/common/compression/StreamCompressionTests.java
  atlasdb-commons/src/test/java/com/palantir/util/crypto/Sha256HashTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ConnectionManagerAwareDbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbReadTable.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TimeLockMigrationEteTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/FullDiagnosticDigest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/LockCheckingTransactionTaskTest.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcKeyValueService.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/PerformanceResults.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/proto/fork/ForkedJsonFormat.java
  build.gradle
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipEvents.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/HistoryAnalyzer.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCache.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/SingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
Labels: merge when ready, no changelog

#5083 Fix AsyncInitializerTest message assertion
  atlasdb-commons/src/test/java/com/palantir/async/initializer/AsyncInitializerTest.java
Labels: merge when ready, no changelog

#5080 Fix hashCode related error-prone checks
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Namespace.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java
  atlasdb-commons/src/main/java/com/palantir/common/base/BatchingVisitables.java
  build.gradle
  leader-election-api/src/main/java/com/palantir/paxos/BooleanPaxosResponse.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorState.java
  lock-api-objects/src/main/java/com/palantir/lock/LockClient.java
  lock-api-objects/src/main/java/com/palantir/lock/LockRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/LockResponse.java
  lock-api-objects/src/main/java/com/palantir/lock/SimpleTimeDuration.java
  lock-api/src/main/java/com/palantir/lock/LockServerOptions.java
Labels: merge when ready, no changelog

#5079 Leader Election Metrics 2a: Server side wiring
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-feedback.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/LeaderElectionMetricAggregator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackResource.java
Labels: merge when ready, no changelog

#5084 [PSL] Better Logging and Option to Skip Validation + Truncate for PSL Migration
  leader-election-api/src/main/java/com/palantir/paxos/PaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorState.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStorageParameters.java
  leader-election-impl/src/main/java/com/palantir/paxos/SplittingPaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease, no changelog

#5086 Fix and enforce ByteBufferBackingArray
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServices.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/HostPartitioner.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/sweep/GetCandidateRowsForSweeping.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutorTest.java
  build.gradle
Labels: merge when ready, no changelog

#5077 [DB TimeLock] 3Q - Simplify DbTimestampCreationSetting To Only Apply To DB TimeLock
  atlasdb-api/src/main/java/com/palantir/atlasdb/config/DbTimestampCreationSetting.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/AtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/timestamp/TimestampCreationParametersCheck.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/timestamp/TimestampCreationParametersCheckTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplier.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AutoServiceAnnotatedAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactory.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidatorCreationTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/RelationalDbTimeLockFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryDbTimeLockFactory.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcAtlasDbFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/ServiceDiscoveringDatabaseTimeLockSupplier.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/DbBoundTimestampCreator.java
  timelock-agent/src/test/java/com/palantir/timelock/ServiceDiscoveringDatabaseTimeLockSupplierTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/DbBoundTimestampCreatorTest.java
Labels: no changelog

#5087 Simplify protobuf configuration
  atlasdb-client-protobufs/build.gradle
  examples/profile-client-protobufs/build.gradle
  leader-election-api-protobufs/build.gradle
Labels: merge when ready, no changelog
