Repository palantir/atlasdb, pull requests merged in 2020-08, with the labels that each got.

#4926 Fix duplicate registration of MetricPublicationFilters
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationArbiter.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationFilter.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/MetricPublicationArbiterTest.java
  changelog/@unreleased/pr-4926.v2.yml
Labels: autorelease, merge when ready

#4928 Bufix/pds 129897
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationArbiter.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/MetricPublicationArbiterTest.java
Labels: autorelease, merge when ready, no changelog

#4930 [PDS-129897] Fix Memory Leak in the Publication Controller
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/MemoizingTableLevelMetricsController.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/ToplistDeltaFilteringTableLevelMetricsController.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/MemoizingTableLevelMetricsControllerTest.java
  changelog/0.240.1-rc2/pr-4930.v2.yml
  changelog/@unreleased/pr-4930.v2.yml
Labels: :white_check_mark: Prod validated, autorelease

#4934 Bump TimeLock Schema Version
  changelog/@unreleased/pr-4934.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease

#4933 Bound lock acquire timeout
  changelog/@unreleased/pr-4933.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/BlockEnforcingLockService.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
Labels: autorelease

#4935 Don't throw on duplicate metric names
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/DisjointUnionTaggedMetricSet.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/DisjointUnionTaggedMetricSetTest.java
  changelog/@unreleased/pr-4935.v2.yml
Labels: autorelease

#4923 Bg gain leadership
  changelog/@unreleased/pr-4923.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipEvents.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionEventRecorder.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeadershipEventRecorder.java
  leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingResult.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  leader-election-impl/src/main/metrics/leader-election.yml
  leader-election-impl/src/test/java/com/palantir/leader/LeadershipEventRecorderTest.java
  leader-election-impl/src/test/java/com/palantir/leader/PaxosLeaderEventsTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
Labels: autorelease

#4941 Much less ram used by disruptors
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/BatchElement.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  changelog/@unreleased/pr-4941.v2.yml
Labels: autorelease

#4944 Update config.yml
  .circleci/config.yml
  docs/source/conf.py
  gradle/shared.gradle
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog

#4937 Reuse Dialogue Factory in Timelock Adjudication Service
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4937.v2.yml
Labels: autorelease

#4947 Add the Oracle driver into AtlasDB directly (No tests)
  atlasdb-dbkvs-tests/src/test/resources/.gitignore
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfig.java
  changelog/@unreleased/pr-4947.v2.yml
  commons-db/build.gradle
  commons-db/src/main/java/com/palantir/db/oracle/JdbcHandler.java
  commons-db/src/main/java/com/palantir/db/oracle/NativeOracleJdbcHandler.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#4948 [PDS-130107] Enable Divergent KVS Namespaces and TimeLock Clients
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbConfigTest.java
  changelog/@unreleased/pr-4948.v2.yml
Labels: autorelease

#4946 Make PingResult java serializable
  changelog/@unreleased/pr-4946.v2.yml
  leader-election-api/src/main/java/com/palantir/leader/PingResult.java
  leader-election-impl/src/test/java/com/palantir/leader/PingResultTest.java
Labels: autorelease, merge when ready

#4952 Update AtlasDB docs to reflect new SotW re. Oracle drivers
  docs/source/cluster_management/clis.rst
Labels: merge when ready, no changelog

#4949 Relieve Flakes - Make Stress Test Run Slightly Longer
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: merge when ready, no changelog

#4956 Intern the token map
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-4956.v2.yml
Labels: autorelease

#4955 memoize ssl socket factory creation
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  changelog/@unreleased/pr-4955.v2.yml
Labels: autorelease

#4939 [PD$-110002] Part 15: MetricsFilterEvaluationContext
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/DefaultMetricsFilterEvaluationContext.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/MetricsFilterEvaluationContext.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/ToplistDeltaFilteringTableLevelMetricsController.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/DefaultMetricsFilterEvaluationContextTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/ToplistDeltaFilteringTableLevelMetricsControllerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/0.240.10-rc2/pr-4939.v2.yml
  changelog/0.241.5-rc1/pr-4939.v2.yml
  changelog/@unreleased/pr-4939.v2.yml
Labels: :white_check_mark: Prod validated

#4953 Pingv2 fallback
  atlasdb-config/src/test/java/com/palantir/atlasdb/SinglePingableLeaderTest.java
  changelog/@unreleased/pr-4953.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/LeaderPingResult.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  leader-election-impl/src/test/java/com/palantir/leader/PaxosLeaderEventsTest.java
Labels: autorelease

#4962 [LW] Fixes, 5: Throw underlying exception if already on fallback cache
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCacheTest.java
  changelog/@unreleased/pr-4962.v2.yml
Labels: merge when ready

#4961 [LW] Fixes, 4: Register lockwatches eagerly
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
Labels: merge when ready, no changelog

#4963 [LW] Fixes, 6: Don't forget the equals
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-4963.v2.yml
Labels: merge when ready

#4964 [LW] Fixes, 5.1: Safe runtime exception
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchEventCacheTest.java
Labels: autorelease, merge when ready, no changelog

#4959 [LW] Fixes, 3: Additional logging towards fixing obscure bug
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  lock-api/src/main/java/com/palantir/lock/client/CommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/LockWatchLogUtility.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
Labels: merge when ready, no changelog
