Repository palantir/atlasdb, pull requests merged in 2020-04, with the labels that each got.

#4670 [TimeLock Partitioning] Part 57: Single Leader Mode Exposes Both Solo And Batch Modes
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderLearnerResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipResource.java
Labels: no changelog

#4691 ProfilingTimelockService delegates initialization check
  changelog/@unreleased/pr-4691.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/ProfilingTimelockServiceTest.java
Labels: autorelease

#4687 getRowsColumnRange always has cells grouped by row
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-4687.v2.yml
Labels: autorelease, merge when ready

#4690 [PDS-111849] Rolling in the Deep, Part 2: Bounded Executors for Acceptors (Single and Batched)
  changelog/@unreleased/pr-4690.v2.yml
  scripts/circle-ci/run-circle-tests.sh
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/RejectionTrackingCallerRunsPolicy.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutorsTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPaxosAcceptorNetworkClientFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPaxosLearnerNetworkClientFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosQuorumCheckingCoalescingFunction.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease

#4692 [Timelock Partitioning] Test Switching Between SL and Batched SL
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosUseCase.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/SingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
Labels: no changelog

#4698 [PDS-111849] Rolling in the Deep, Part 3: Fix Metrics Plughole
  changelog/@unreleased/pr-4698.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockPaxosMetrics.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease

#4676 [LW] Remove old client and resource and use undertow
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchingRpcClient.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/NamespacedLockWatchingRpcClient.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureLockWatchingService.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureLockWatchingResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureResourceExceptionHandler.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimeLockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimeLockServices.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchTestingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImplTest.java
Labels: autorelease, no changelog

#4700 [PDS-111849] Rolling in the Deep, Part 4: Relax Shared Executor Bound
  changelog/@unreleased/pr-4700.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/RejectionTrackingCallerRunsPolicy.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease

#4704 Restoring the Range Request Contract, Part 1: Parameter Objects for getRange
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/GetRangesQuery.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
Labels: no changelog

#4707 Executor quality of life and instrumentation
  atlasdb-commons/src/main/java/com/palantir/common/proxy/InterruptibleProxy.java
  changelog/@unreleased/pr-4707.v2.yml
  commons-executors/build.gradle
  commons-executors/src/main/java/com/palantir/common/concurrent/NamedThreadFactory.java
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  commons-executors/src/test/java/com/palantir/common/concurrent/PTExecutorsTest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  lock-impl/src/test/java/com/palantir/lock/LockServiceTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ClientAwareLockTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/LockCreator.java
  versions.props
Labels: merge when ready

#4710 Remove qos-service-impl.
  docs/source/configuration/index.rst
  docs/source/configuration/qos_configs/index.rst
  docs/source/configuration/qos_configs/qos_client_config.rst
  docs/source/services/index.rst
  docs/source/services/qos_service/enabling-rate-limiting.rst
  docs/source/services/qos_service/index.rst
  qos-service-impl/build.gradle
Labels: merge when ready, no changelog

#4708 [PDS-111849] Rolling in the Deep, Part 5: Only One Dedicated Executor
  changelog/@unreleased/pr-4708.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorAdapter.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorAdapters.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosAcceptorAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/WithDedicatedExecutor.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/SingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
Labels: autorelease

#4713 Fix bad merge
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockPaxosAcceptorAdapter.java
Labels: no changelog

#4717 Conjure Java Runtime 5.7.0
  changelog/@unreleased/pr-4717.v2.yml
  versions.props
Labels: autorelease

#4719 [Timelock Partitioning] Tag remote hosts for internode communication
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
Labels: autorelease, no changelog

#4712 [CentOS Migration] Part 1: Configurable Ban on New Clients
  changelog/@unreleased/pr-4712.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosInstallConfiguration.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease

#4724 [PaxosLog] Sqlite implementation without namespaces
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  versions.props
Labels: no changelog

#4723 Use refreshable for runtime config
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/ServerListConfigs.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/debug/TransactionPostMortemRunner.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbRuntimeConfigRefreshable.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/ServerListConfigsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/LockAndTimestampModule.java
  changelog/@unreleased/pr-4723.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TransactionPostMortemIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
  versions.props
Labels: autorelease, merge when ready

#4727 stalebot closes PRs after 30+7 days
  .github/stale.yml
Labels: merge when ready, no changelog

#4729 [PaxosLog] Use JDBI and add namespacing
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  versions.props
Labels: no changelog

#4732 [PDS-117161] Add additional logging on close of Snapshot Transaction Manager
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
Labels: autorelease, merge when ready, no changelog

#4733 Remove deprecation until downstream services catch up.
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-4733.v2.yml
Labels: autorelease, merge when ready

#4726 [PaxosLog] Part 3: Namespacing SqlitePaxosStateLog
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStorageParameters.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: no changelog

#4734 Fix flaky test
  leader-election-impl/build.gradle
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
Labels: no changelog

#4728 Get all namespaces
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
Labels: no changelog

#4738 [PDS-117310] Add trace logging when updating the namespace mapping
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingService.java
Labels: no changelog

#4737 [PaxosLog] Expose batch write method
  leader-election-api/src/main/java/com/palantir/paxos/PaxosRound.java
  leader-election-api/src/main/java/com/palantir/paxos/PaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
Labels: no changelog

#4736 Timelock consensus
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/NamespacedConsensus.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
Labels: autorelease, no changelog

#4735 [PaxosLog] VerifyingPaxosStateLog
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/VerifyingPaxosStateLogTest.java
Labels: no changelog

#4741 Standardize on NamedThreadFactory for observability
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  changelog/@unreleased/pr-4741.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockPaxosExecutors.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease

#4744 PG-148649: AgnosticLightResultSetImpl doesn't fill the finalizer queue
  changelog/@unreleased/pr-4744.v2.yml
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticLightResultSetImpl.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/SQL.java
Labels: autorelease

#4721 Serializable index need not lock anything
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/ConflictHandler.java
  changelog/@unreleased/pr-4721.v2.yml
Labels: autorelease
