Repository palantir/atlasdb, pull requests merged in 2020-11, with the labels that each got.

#5091 Fix build fail
  atlasdb-container-test-utils/build.gradle
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/Containers.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TimeLockMigrationEteTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryDbTimeLockFactory.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/DatabasesContainer.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  lock-api/src/test/java/com/palantir/lock/client/AsyncTimeLockUnlockerTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/AwaitedLocksCollectionTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/DbKvsRule.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#5094 [LE] Add timing to additional endpoints
  changelog/@unreleased/pr-5094.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
Labels: merge when ready

#5089 [TimeLock Corruption Detection] | Integration tests
  timelock-corruption-detection/src/test/java/com/palantir/timelock/TimelockCorruptionTestConstants.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/CorruptionDetectionIntegrationTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionDetectionHelper.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionTestSetup.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/HistoryLoaderAndTransformerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/PaxosLogHistoryProviderTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/utils/HistoryQueries.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/utils/PaxosSerializationTestUtils.java
Labels: no changelog

#5090 Enable TimeLock Corruption Detection
  changelog/0.260.1-rc1/pr-5078.v2.yml
  changelog/0.260.1-rc1/pr-5090.v2.yml
  changelog/0.261.1-rc1/pr-5090.v2.yml
  changelog/@unreleased/pr-5090.v2.yml
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
Labels: autorelease

#5088 [LE] Server Side Metrics Accumulator For Leadership Duration
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
  timelock-api/src/main/conjure/timelock-feedback.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/LeaderElectionDurationAccumulator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/LeaderElectionMetricAggregator.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/LeaderElectionDurationAccumulatorTest.java
Labels: autorelease, merge when ready, no changelog

#5098 [LE] Wire in the metrics from client to server
  changelog/@unreleased/pr-5098.v2.yml
  lock-api-objects/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
Labels: autorelease, merge when ready

#5104 Fix build
  scripts/circle-ci/download-moreutils.sh
Labels: merge when ready, no changelog

#5100 [LW] Filter out locks using the serverToken, not the fake token in LeasedLockToken
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/lock/client/LeasedLockTokenCreator.java
  changelog/@unreleased/pr-5100.v2.yml
Labels: autorelease, merge when ready

#5108 Fix MaskedValue Jackson 2.12 compatibility
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/MaskedValue.java
  atlasdb-dbkvs-hikari/src/test/java/com/palantir/nexus/db/pool/config/MaskedValueTest.java
  changelog/@unreleased/pr-5108.v2.yml
Labels: merge when ready

#5067 Increase error-prone reference comparison strictness
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitionsTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueServiceTest.java
  atlasdb-commons/src/main/java/com/palantir/common/time/Clock.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsIndexCleanupTask.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsMetadataCleanupTask.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataIndexCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataIndexCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataMetadataCleanupTask.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataStreamStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryDbTimeLockFactory.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueIndexCleanupTask.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueMetadataCleanupTask.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestIndexCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemIndexCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashIndexCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsIndexCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsMetadataCleanupTask.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsStreamStore.java
  build.gradle
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosStreamStore.java
  gradle/shared.gradle
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeadershipToken.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
Labels: merge when ready, no changelog

#5105 add cache warming option to ssm
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManagers.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresSweepTaskRunnerTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbkvsPostgresTargetedSweepIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  changelog/@unreleased/pr-5105.v2.yml
Labels: autorelease, merge when ready, pr: needs review

#5106 [LW] Check the correct client versions range
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-5106.v2.yml
Labels: autorelease, merge when ready

#5112 [Tl Corruption Checks] | Bump down the limit for rows verified per iteration
  changelog/@unreleased/pr-5112.v2.yml
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/PaxosLogHistoryProgressTracker.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/CorruptionDetectionIntegrationTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/PaxosLogHistoryProgressTrackerTest.java
Labels: autorelease

#5101 [Cross Client Batching - 1] | TimeLock Batch endpoints
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
Labels: merge when ready, no changelog

#5116 Bump timelock dep by 1 version
  lock-api-objects/build.gradle
Labels: autorelease, merge when ready, no changelog

#5115 [Cross Client Batching - 1b] | Wiring TimeLock Batch endpoints
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
Labels: autorelease, no changelog

#5114 remove moreutils dependency in build
  .circleci/config.yml
  scripts/circle-ci/download-moreutils.sh
  scripts/time-cmd.sh
Labels: merge when ready, no changelog

#5119 [Cross Client Batching - 1d] | Modify leaderTimes api
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease, merge when ready, no changelog

#5120 [Cross Client Batching LeaderTimes - 2a] | Refactor coalescing leaderTimeGetter
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/Autobatchers.java
  changelog/@unreleased/pr-5120.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LeaderTimeCoalescingBatcher.java
  lock-api/src/main/java/com/palantir/lock/client/LeaderTimeGetter.java
  lock-api/src/main/java/com/palantir/lock/client/LegacyLeaderTimeGetter.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedCoalescingLeaderTimeGetter.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
Labels: merge when ready

#5113 Better metrics
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/LeaderElectionMetricAggregator.java
Labels: autorelease, merge when ready, no changelog

#5122 [Cross Client Batching LeaderTimes - 2b] | MultiClientConjureTimelockService Dialogue Clients
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  lock-api/src/main/java/com/palantir/lock/client/AuthenticatedInternalMultiClientConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/InternalMultiClientConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/LeaderTimeCoalescingBatcher.java
Labels: merge when ready, no changelog

#5125 [Cross Client Batching - 3a] | Bump TL product dependency
  lock-api-objects/build.gradle
Labels: autorelease, merge when ready, no changelog

#5126 Bump TimeLock product dependency
  lock-api-objects/build.gradle
Labels: autorelease, merge when ready, no changelog

#5129 Remove unused project
  atlasdb-api/build.gradle
  atlasdb-autobatch/build.gradle
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/CassandraSchemaLockTest.java
  atlasdb-cassandra/build.gradle
  atlasdb-client/build.gradle
  atlasdb-commons/build.gradle
  atlasdb-commons/src/test/java/com/palantir/common/proxy/InterruptibleProxyTest.java
  atlasdb-conjure/build.gradle
  atlasdb-dbkvs/build.gradle
  atlasdb-ete-test-utils/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-jepsen-tests/build.gradle
  atlasdb-processors-tests/build.gradle
  atlasdb-refactorings/build.gradle
  atlasdb-remoting-api/build.gradle
  atlasdb-tests-shared/build.gradle
  examples/profile-client/build.gradle
  lock-api/build.gradle
  scripts/circle-ci/run-circle-tests.sh
  settings.gradle
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#5124 Add serialize/deserialize annotations for Oracle service name configuration
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  changelog/@unreleased/pr-5124.v2.yml
Labels: autorelease

#5093 add initializeAsync for Db implementations
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKvsPostgresInvalidationRunnerTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidatorCreationTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/PostgresMultiSequenceTimestampSeriesProviderTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/PostgresMultiSeriesDbTimestampBoundStoreTest.java
  atlasdb-dbkvs/build.gradle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/RelationalDbTimeLockFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ConnectionManagerAwareDbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKeyValueService.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/InDbTimestampBoundStore.java
  changelog/@unreleased/pr-5093.v2.yml
Labels: autorelease

#5123 [PDS-146501] Cast DEFAULT_TARGETED_SWEEP_SHARDS=1 down into the briny deeps
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.yml
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraTimestampsEteTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ShardProgressTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperNumShardSupplierTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  changelog/@unreleased/pr-5123.v2.yml
Labels: autorelease, merge when ready

#5128 [Cross Client Batching LeaderTimes - 3b] | AtlasDb accepts external request batcher for LeaderTime api
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/TimeLockRequestBatcherProvider.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/TimeLockRequestBatcherProviders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-5128.v2.yml
Labels: autorelease, merge when ready
