Repository palantir/atlasdb, pull requests merged in 2020-06, with the labels that each got.

#4815 Enable dialogue clients by default
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/RemotingClientConfig.java
  changelog/@unreleased/pr-4815.v2.yml
Labels: autorelease

#4811 Lock watches wiring and exposing API for PreCommitCondition.
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/InternalLockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpInternalLockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/InstrumentedTimelockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadOnlyTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/impl/AtlasDbServiceImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  lock-api-objects/build.gradle
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/CommitUpdate.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/TransactionUpdate.java
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/CommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  lock-api/src/test/java/com/palantir/lock/client/CommitTimestampGetterTest.java
  lock-api/src/test/java/com/palantir/lock/client/TestBatchElement.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LegacyTimelockService.java
Labels: autorelease, merge when ready, no changelog

#4817 Fix incorrect getRangeSlices trace span names
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingCassandraClient.java
  changelog/@unreleased/pr-4817.v2.yml
Labels: merge when ready

#4824 Avoid setting insecure hostname verification
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  changelog/@unreleased/pr-4824.v2.yml
Labels: autorelease

#4821 [GCV Blocker] Don't use org.json.simple
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/NameMetadataDescription.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/ValueType.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/NameMetadataDescriptionTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ValueTypeTest.java
Labels: no changelog

#4809 [Dialogue] Part 10: :hot_pepper: TimeLock Internode by Shim
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/DialogueClientOptions.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/AuxiliaryRemotingParameters.java
  changelog/@unreleased/pr-4809.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockDialogueServiceProvider.java
Labels: autorelease

#4822 [PDS-119625] Log the Exception, not UnsafeArg.of(exceptionMessage)
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  changelog/@unreleased/pr-4822.v2.yml
Labels: merge when ready

#4825 [PDS-95791/Post Mortems] Local Lock Trackers
  atlasdb-config/src/main/java/com/palantir/atlasdb/debug/TransactionPostMortemRunner.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/FullDiagnosticDigest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LocalLockTracker.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticComponents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticConjureTimelockService.java
  changelog/@unreleased/pr-4825.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TransactionPostMortemIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
Labels: autorelease

#4769 Gradle consistent versions
  .circleci/config.yml
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  atlasdb-cassandra/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TaggedMetricsInvocationEventHandler.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemaTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/render/TableRendererTest.java
  atlasdb-container-test-utils/build.gradle
  atlasdb-ete-test-utils/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/AdjustableSweepBatchConfigSourceTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/priority/NextTableToSweepProviderTest.java
  atlasdb-jepsen-tests/build.gradle
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/Event.java
  atlasdb-jepsen-tests/src/test/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckerIntegrationTest.java
  build.gradle
  dropwizard-metrics-hack/build.gradle
  dropwizard-metrics-hack/src/main/java/com/codahale/metrics/jvm/JvmAttributeGaugeSet.java
  gradle/tests.gradle
  leader-election-api/build.gradle
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipEvents.java
  lock-impl/build.gradle
  settings.gradle
  tests.props
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncResult.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/ImmutableTimestampTracker.java
  timelock-server-benchmark-client/build.gradle
  timelock-server-benchmark-cluster/build.gradle
  timelock-server/build.gradle
  versions.lock
  versions.props
Labels: no changelog

#4828 Close resource in RemoteTimelockServiceAdapter
  changelog/@unreleased/pr-4828.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
Labels: autorelease, merge when ready

#4830 [Dialogue] Part 12: Fix Misdeclared Product Dependencies
  changelog/@unreleased/pr-4830.v2.yml
  lock-conjure-api/build.gradle
Labels: autorelease

#4826 Override blocking thrift threadpool.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  changelog/@unreleased/pr-4826.v2.yml
Labels: autorelease, merge when ready

#4831 [PDS-119588] Relax Cassandra Schema Version Check
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServices.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTables.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServicesSchemaConsensusTest.java
  changelog/@unreleased/pr-4831.v2.yml
Labels: autorelease

#4835 PG-151833: Apply the default cancel-remaining-calls value globally
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  changelog/@unreleased/pr-4835.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosConstants.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/LeaderPingHealthCheck.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosQuorumCheckingCoalescingFunction.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease, merge when ready, must be merged

#4839 Change CassandraKeyValueServiceConfig#thriftExecutorService -> thrift…
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  changelog/@unreleased/pr-4839.v2.yml
Labels: autorelease, merge when ready

#4840 override service name
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4840.v2.yml
Labels: autorelease

#4836 [PD$-110002] Part 1: Targeted Sweep Metrics, Configurable By Strategy
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepInstallConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepableCellsTest.java
  changelog/@unreleased/pr-4836.v2.yml
Labels: autorelease

#4837 [PD$-110002] Part 2: Economising Snapshot Transaction commitWrites() Timers
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-4837.v2.yml
Labels: autorelease

#4838 [PD$-110002] Part 3: Remove transactionsReadFromDB
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-4838.v2.yml
Labels: autorelease

#4843 Add serviceId
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-4843.v2.yml
Labels: autorelease

#4844 TimeLock client feedback api
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-feedback.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackResource.java
Labels: autorelease, no changelog

#4846 [PD$-110002] CONTENTIOUS - Part 4: Redirect All Metrics To TaggedMetricRegistries
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/DisjointUnionTaggedMetricSet.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/DisjointUnionTaggedMetricSetTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-4846.v2.yml
Labels: autorelease

#4851 Targeted sweep is no longer in active development
  docs/source/cluster_management/sweep/targeted-sweep.rst
Labels: no changelog, small

#4856 Change API from SortedMap to NavigableMap.
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ResultsExtractor.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestV2Table.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/Cells.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/RowResults.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableClassRendererV2.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/AbstractSchemaApiTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ranges/DbKvsGetRanges.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-4856.v2.yml
Labels: autorelease, merge when ready

#4847 [PDS$-110002] Part 5 | PoC?: Threshold-Based Metric Filtering and Metric-Schema for Targeted Sweep Metrics
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/FilteredTaggedMetricSet.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationArbiter.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationFilter.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/FilteredTaggedMetricSetTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/MetricPublicationArbiterTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/MetricsManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetricPublicationFilter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetricPublicationFilterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetricsTest.java
  changelog/@unreleased/pr-4847.v2.yml
Labels: autorelease

#4853 Error rates
  lock-api-objects/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/DialogueAdaptingConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
  lock-api/src/main/metrics/metric-schema.yml
  timelock-api/src/main/conjure/timelock-feedback.yml
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackMetricsTest.java
Labels: autorelease, no changelog, pr: needs review

#4858 bump version of timeLock product dependency
  changelog/@unreleased/pr-4858.v2.yml
  lock-api-objects/build.gradle
Labels: autorelease, merge when ready

#4859 Upgrade dialogue to get rid of apache-hc4 constraint
  atlasdb-conjure/build.gradle
  changelog/@unreleased/pr-4859.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#4862 RowResult#getColumns NavigableMap.
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RowResult.java
Labels: autorelease, merge when ready, no changelog

#4865 Name key count logged safe parameter
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ProfilingCassandraClient.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/LoggingArgs.java
  changelog/@unreleased/pr-4865.v2.yml
Labels: merge when ready

#4863 Local and remote health pinger
  changelog/@unreleased/pr-4863.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackResource.java
Labels: autorelease

#4820 Remove LockWatchStateUpdate#Failed.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/failedUpdateClearsAllCaches/event-cache-1.json
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchStateUpdate.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
  timelock-impl/build.gradle
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindow.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ValueAndLockWatchStateUpdate.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindowTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/UpdateVisitors.java
Labels: autorelease, merge when ready, no changelog

#4861 Feedback integration ii
  changelog/@unreleased/pr-4861.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/Constants.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackHandler.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/HealthStatus.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/HealthStatusReport.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/ServiceFeedback.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/ServiceLevelObjectiveSpecification.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackSink.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/Utils.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FakeTicker.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackAnalysisTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackSinkTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/HealthStateTest.java
Labels: autorelease

#4871 [TimeLock Adjudication] Handle duplicate case
  changelog/@unreleased/pr-4871.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackHandler.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackAnalysisTest.java
Labels: autorelease

#4868 Increase gradle build memory to 2 GB
  gradle.properties
Labels: no changelog

#4876 [PD$-110002] Part 8: Make Disjoint Metric Set Disjoint
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/InstrumentationUtils.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowMetricsInvocationHandler.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TaggedMetricsInvocationEventHandler.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/InstrumentationUtilsTest.java
  changelog/@unreleased/pr-4876.v2.yml
Labels: autorelease

#4867 [PD$-110002] Part 6: One-Shots and Legacies
  atlasdb-api/src/main/java/com/palantir/atlasdb/metrics/MetricPublicationFilter.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/health/MetricsBasedTimelockHealthCheck.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/CoordinationServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/AdjustableSweepBatchConfigSource.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/InstrumentedTimelockService.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/health/MetricsBasedTimelockHealthCheckTest.java
  changelog/@unreleased/pr-4867.v2.yml
Labels: autorelease
