Repository palantir/atlasdb, pull requests merged in 2020-12, with the labels that each got.

#5138 [LW] Log some more
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
Labels: autorelease, merge when ready, no changelog

#5143 [LW] Add logging to Timelock
  changelog/@unreleased/pr-5143.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
Labels: autorelease, merge when ready

#5145 [LW] Smile for the snapshot
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-5145.v2.yml
Labels: autorelease, merge when ready

#5146 [LW] [PDS-148088] Close your eyes
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/lock/SimpleEteLockWatchResource.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  changelog/@unreleased/pr-5146.v2.yml
Labels: autorelease, merge when ready

#5139 Set dclocal_read_repair chance to 0
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTableCreator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ColumnFamilyDefinitions.java
  changelog/@unreleased/pr-5139.v2.yml
Labels: autorelease, merge when ready

#5147 [pds-147605] Upgrade Gradle SLS Packaging 4.10.1 -> 4.24.0
  build.gradle
  changelog/@unreleased/pr-5147.v2.yml
Labels: autorelease, merge when ready

#5149 Make EC2 Location supplier memoize on failures
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplierTest.java
  changelog/@unreleased/pr-5149.v2.yml
Labels: autorelease, merge when ready

#5150 Fix: Downgrade Jackson to 2.11.1
  changelog/@unreleased/pr-5150.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5137 [Productionizing GetSortedColumns] Part 1: Row Column Range Traps
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  changelog/@unreleased/pr-5137.v2.yml
Labels: autorelease

#5160 Revert "Actually build the docs"
  .circleci/config.yml
Labels: merge when ready, no changelog

#5162 bump commons
  atlasdb-cassandra/build.gradle
  changelog/@unreleased/pr-5162.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5161 [WIP] Publish github pages correctly.
  .circleci/config.yml
Labels: no changelog

#5164 Don't try to publish internal docs from external CircleCI!
  .circleci/config.yml
Labels: merge when ready, no changelog

#5140 [LW] No Op cache tracks version
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/DuplicatingLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/AsyncLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimestampClient.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/@unreleased/pr-5140.v2.yml
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
Labels: autorelease, merge when ready

#5167 [LW] Handle Snapshots into Empty Successes Correctly
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/emptySuccessesFollowingSnapshotsDoNotCauseAdditionalCacheClearance/event-cache-1.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/emptySuccessesFollowingSnapshotsDoNotCauseAdditionalCacheClearance/event-cache-2.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/emptySuccessesFollowingSnapshotsDoNotCauseAdditionalCacheClearance/event-cache-3.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/emptySuccessesFollowingSnapshotsDoNotCauseAdditionalCacheClearance/event-cache-4.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/emptySuccessesFollowingSnapshotsDoNotCauseAdditionalCacheClearance/event-cache-5.json
  changelog/@unreleased/pr-5167.v2.yml
Labels: autorelease, merge when ready
