Repository palantir/atlasdb, pull requests merged in 2020-05, with the labels that each got.

#4751 [CentOS Migration] Part 2: Node-level is-new-service
  timelock-agent/src/main/java/com/palantir/timelock/config/ClusterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockPersistenceInvariants.java
  timelock-agent/src/test/java/com/palantir/timelock/config/ClusterConfigurationDeserializationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosInstallConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockPersistenceInvariantsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/PaxosRemotingUtilsTest.java
Labels: autorelease, no changelog

#4746 [PaxosLog] Part 7b: Configuration Sketch :fire: CONTENTIOUS :fire:
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/SqlitePaxosPersistenceConfiguration.java
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosInstallConfigurationIntegrationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockPersistenceInvariantsTest.java
Labels: autorelease, no changelog

#4748 Fix bug in transaction starter if it fails midway through the batch
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
Labels: no changelog

#4752 Add namespace validation as a param to KvTableMappingService
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingService.java
Labels: autorelease, no changelog

#4755 com.palantir.refreshable 1.0
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbRuntimeConfigRefreshable.java
  versions.props
Labels: autorelease, merge when ready, no changelog

#4757 Implement better TM closing
  atlasdb-commons/src/main/java/com/palantir/util/SafeShutdownRunner.java
  atlasdb-commons/src/test/java/com/palantir/util/SafeShutdownRunnerTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-4757.v2.yml
Labels: autorelease

#4753 [PaxosLog] Part 8 & [CentOS] Part 3: Merged PersistentNamespaceLoaders
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/PersistentNamespaceContext.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/PersistentNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoaderTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
Labels: autorelease, no changelog

#4761 [Dialogue] Part 1: BlockingSensitive -> TimeoutSensitive Nomenclature Changes
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceCreator.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/ShortAndLongTimeoutServices.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/TimeoutSensitiveConjureTimelockService.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/TimeoutSensitiveLockRpcClient.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/TimeoutSensitiveLockRpcClientTest.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/ClientOptionsTest.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimelockUtils.java
  atlasdb-remoting-api/src/main/java/com/palantir/atlasdb/config/AuxiliaryRemotingParameters.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  changelog/@unreleased/pr-4761.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/ClientSplitLockService.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease

#4762 [Dialogue] Part 2: Translation from AtlasDB Services to ServiceConfigBlocks
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/ShortAndLongTimeoutServices.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/ShortAndLongTimeoutServicesTest.java
  atlasdb-config/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  atlasdb-conjure/build.gradle
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptionsConstants.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/DialogueClientOptions.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/RemoteServiceConfiguration.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/ClientOptionsTest.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/DialogueClientOptionsTest.java
  lock-api/build.gradle
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  versions.props
Labels: no changelog

#4763 [Dialogue] Part 3: AtlasDbDialogueServiceProvider
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProviderTest.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/FastFailoverProxy.java
  lock-api/src/main/java/com/palantir/lock/client/DialogueAdaptingConjureTimelockService.java
  versions.props
Labels: no changelog

#4765 [PaxosStateLog] Migrator and unit tests
  leader-election-impl/src/main/java/com/palantir/paxos/NamespaceAndUseCase.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoaderTest.java
Labels: no changelog

#4768 [PaxosStateLog] File to Sqlite Integration Tests
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogBatchReaderTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/VerifyingPaxosStateLogTest.java
Labels: no changelog

#4774 [PaxosStateLog] Implement Different Migration States
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
Labels: no changelog

#4770 Allow invalidating SweepStrategyManager cache
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManagers.java
  changelog/@unreleased/pr-4770.v2.yml
Labels: autorelease

#4779 SqlitePaxosStateLogMigrationState$States variable final
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
Labels: no changelog

#4780 Update README.md
  README.md
Labels: merge when ready, no changelog

#4775 [PaxosStateLog] Wire up and Migrate To Verifying PSL
  changelog/@unreleased/pr-4775.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStorageParameters.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease

#4782 Revert "[PaxosStateLog] Wire up and Migrate To Verifying PSL (#4775)"
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStorageParameters.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease, no changelog

#4783 Address Some Known Flakes
  atlasdb-commons/src/test/java/com/palantir/util/SafeShutdownRunnerTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: merge when ready, no changelog

#4778 [Dialogue] Part 6: Road to Multitenancy
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProviderTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-console/build.gradle
  changelog/@unreleased/pr-4778.v2.yml
Labels: autorelease, merge when ready

#4784 [Dialogue] Part 6b: api not impl
  atlasdb-config/build.gradle
  changelog/@unreleased/pr-4784.v2.yml
Labels: autorelease

#4785 [PaxosStateLog] Implement locking for SqlitePSL
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoaderTest.java
Labels: no changelog

#4786 [PaxosStateLog] Reintroduce Migration and Verification with Locks
  changelog/@unreleased/pr-4786.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStorageParameters.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogFactory.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoaderTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease

#4789 Upgrade dialogue & conjure-java
  versions.props
Labels: autorelease, merge when ready, no changelog

#4788 [PaxosStateLog] Validate without migration
  changelog/@unreleased/pr-4788.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
Labels: autorelease

#4791 Always send full last known version, including id.
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionRequestV5.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/IdentifiedVersion.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImplTest.java
Labels: merge when ready, no changelog

#4795 Fix deserialization issue.
  changelog/@unreleased/pr-4795.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
Labels: autorelease

#4797 [PaxosStateLog] Use WAL and remove locking
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogFactory.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoaderTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
Labels: autorelease, no changelog

#4794 [Dialogue] Part 9: Shims for Lesser Used Services: AtlasDB -> TimeLock
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/DialogueShimFactory.java
  changelog/@unreleased/pr-4794.v2.yml
Labels: autorelease

#4803 [PDS-120786, PaxosLog] Avoid Overhead From Repeatedly Taking Locks And Starting New Connections
  changelog/@unreleased/pr-4803.v2.yml
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStorageParameters.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/PersistentNamespaceContext.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoaderTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  versions.props
Labels: autorelease

#4804 Make Circle Builds ~4:30 Faster
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: merge when ready, no changelog

#4802 Filter out leaderPaxos from list of namespaces
  changelog/@unreleased/pr-4802.v2.yml
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoaderTest.java
Labels: autorelease

#4805 Update test after refactor
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoaderTest.java
Labels: merge when ready, no changelog

#4793 [PaxosStateLog] Splitting log
  leader-election-impl/src/main/java/com/palantir/paxos/SplittingPaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/SplittingPaxosStateLogTest.java
Labels: no changelog

#4796 [PaxosStateLog] Migrate from Cutoff + Persist Cutoff
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLogMigrationState.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SplittingPaxosStateLogTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
Labels: no changelog

#4810 [PaxosStateLog] Use Singlethreaded access to Sqlite
  leader-election-impl/src/main/java/com/palantir/paxos/SqliteConnections.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/config/SqlitePaxosPersistenceConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/SingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemplateVariables.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java
  timelock-server/src/testCommon/resources/paxosMultiServer.ftl
Labels: no changelog

#4813 [PaxosStateLog] Migrate
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  changelog/@unreleased/pr-4813.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosAcceptorImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosLearnerImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/main/java/com/palantir/paxos/SplittingPaxosStateLog.java
  leader-election-impl/src/main/java/com/palantir/paxos/VerifyingPaxosStateLog.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  leader-election-impl/src/test/java/com/palantir/paxos/SplittingPaxosStateLogTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/VerifyingPaxosStateLogTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease

#4814 [PaxosStateLog] Fix Corner Case
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogMigrator.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
Labels: autorelease, no changelog
