Repository palantir/atlasdb, pull requests merged in 2020-03, with the labels that each got.

#4620 Refactor out an AsyncRetrier to allow for better testing
  changelog/@unreleased/pr-4620.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AsyncRetrier.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AsyncRetrierTest.java
Labels: merge when ready

#4622 Add implementation of getFreshTimestamps to the conjure timelock service
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticConjureTimelockService.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
Labels: autorelease, merge when ready, no changelog

#4607 SweepStrategyManagers only load one table metadata on cache miss
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManagers.java
  changelog/@unreleased/pr-4607.v2.yml
Labels: merge when ready

#4610 If a method returned by AwaitingLeadershipProxy returns ListenableFuture, the leadership check is also asynchronous
  atlasdb-commons/build.gradle
  atlasdb-commons/src/main/java/com/palantir/atlasdb/futures/AtlasFutures.java
  atlasdb-commons/src/main/java/com/palantir/atlasdb/futures/FuturesCombiner.java
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/CoalescingSupplier.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SerializingProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CoalescingSupplierTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/benchmarks/AwaitingLeadershipProxyBenchmark.java
  changelog/@unreleased/pr-4610.v2.yml
  leader-election-api/src/main/java/com/palantir/leader/LeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/BatchingLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/paxos/CoalescingPaxosLatestRoundVerifier.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosTestState.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/ConjureTimelockResourceTest.java
Labels: autorelease, merge when ready

#4621 Improve observability of DisruptorAutobatcher.
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/Autobatchers.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/BatchSizeRecorder.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/ProfilingEventHandler.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/TracingEventHandler.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/BatchSizeRecorderTest.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/TracingEventHandlerTest.java
  versions.props
Labels: no changelog

#4614 [LW] Add LW to conjure start transactions
  changelog/@unreleased/pr-4614.v2.yml
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceIntegrationTest.java
Labels: autorelease

#4627 Add Conjureable analogues for remaining endpoints
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/BlockingSensitiveTimelockRpcClient.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticConjureTimelockService.java
  changelog/@unreleased/pr-4627.v2.yml
  lock-api/src/main/java/com/palantir/lock/v2/NamespacedTimelockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/v2/TimelockRpcClient.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockLog.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImplTest.java
Labels: autorelease, merge when ready

#4623 [Timelock Partitioning] Part 52: ManualBatchingLeaderPinger
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/ClientAwareLeaderPinger.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/CumulativeLeaderPinger.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactoryTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/CumulativeLeaderPingerTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuidTests.java
Labels: no changelog

#4599 [PDS-105073] Support Specifying Service Name in Oracle Connection Config
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  atlasdb-dbkvs-hikari/src/test/java/com/palantir/nexus/db/pool/config/OracleConnectionConfigTest.java
  changelog/@unreleased/pr-4599.v2.yml
  docs/source/configuration/key_value_service_configs/oracle_key_value_service_config.rst
Labels: autorelease

#4575 [Conjure Java Runtime] Part 28: Modernisation and Recovery of Jepsen
  atlasdb-jepsen-tests/resources/atlasdb/timelock.yml
  atlasdb-jepsen-tests/src/jepsen/atlasdb/timelock.clj
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/AsyncLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/SynchronousLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimelockUtils.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimestampClient.java
  atlasdb-jepsen-tests/var/security/keyStore.jks
  atlasdb-jepsen-tests/var/security/trustStore.jks
Labels: no changelog

#4605 [LW] Wire LW into TransactionStarter
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TableWatchState.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadOnlyTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/AsyncLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimelockUtils.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimestampClient.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionResponseV5.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/IdentifiedVersion.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchingRpcClient.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/NamespacedLockWatchingRpcClient.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockResource.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
Labels: no changelog

#4597 [LW] Synchronise Issuing Start Timestamps with Lock Event Log
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionResponseV5.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindow.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ValueAndVersion.java
Labels: autorelease, no changelog

#4634 Fix old endpoint
  changelog/@unreleased/pr-4634.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockResource.java
Labels: autorelease

#4635 [LW] Revert dev break until necessary
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
Labels: autorelease, merge when ready, no changelog

#4638 [PDS-113120] Conjure TimeLock Service had blocking and non-blocking the wrong way round
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/BlockingAndNonBlockingServices.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/BlockingSensitiveConjureTimelockService.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/BlockingSensitiveLockRpcClient.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/BlockingSensitiveLockRpcClientTest.java
  changelog/@unreleased/pr-4638.v2.yml
Labels: P0 follow-up, autorelease

#4637 [PDS-113136/PDS-113116] Corroboration Check Exception Logging
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/consistency/TimestampCorroborationConsistencyCheck.java
  changelog/@unreleased/pr-4637.v2.yml
Labels: autorelease

#4642 Allow easy migration from/to thorough sweep
  atlasdb-client-protobufs/src/main/proto/TableMetadataPersistence.proto
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/SweepStrategy.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManagers.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/transaction/impl/ReadTransactionShould.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTaskRunner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/Sweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardAndStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperLock.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitioner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/AbstractSweepQueueTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ShardAndStrategyTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperLockTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitionerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-4642.v2.yml
Labels: autorelease

#4643 [PDS-113349] Clients for Paxos resources should not support blocking operations
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-4643.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
Labels: autorelease

#4647 Fix bug in CoalescingSupplier
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/CoalescingSupplier.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CoalescingSupplierTest.java
  changelog/@unreleased/pr-4647.v2.yml
Labels: autorelease

#4648 Change conjure client replacement logic to replace ASAP
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ReplaceIfExceptionMatchingProxy.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SelfRefreshingProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ReplaceIfExceptionMatchingProxyTest.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/SelfRefreshingProxyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  changelog/@unreleased/pr-4648.v2.yml
Labels: autorelease, merge when ready

#4650 Add missing test to ReplaceIfExceptionMatchingProxy.
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ReplaceIfExceptionMatchingProxyTest.java
Labels: merge when ready, no changelog

#4645 [PDS-113120] Block Enforcing (Client-Side) Lock Service
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  changelog/@unreleased/pr-4645.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/BlockEnforcingLockService.java
  lock-api/src/main/java/com/palantir/lock/client/ConjureLockRequests.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/test/java/com/palantir/lock/client/BlockEnforcingLockServiceTest.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease

#4653 log tableref on serializable conflicts
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
Labels: no changelog

#4654 Support Acquire Timeouts of 0 and Fail Hard on Negative Timeouts
  changelog/@unreleased/pr-4654-fix.v2.yml
  changelog/@unreleased/pr-4654.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/LockRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/WaitForLocksRequest.java
  lock-api/src/main/java/com/palantir/lock/client/BlockEnforcingLockService.java
  lock-api/src/test/java/com/palantir/lock/client/BlockEnforcingLockServiceTest.java
Labels: autorelease

#4639 [Timelock Partitioning] Part 53: Latest sequence cache concurrent
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptorCache.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptorCacheDigest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptorCacheImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptorCacheKey.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCache.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosAcceptor.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimestampedAcceptorCacheKey.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCacheTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalBatchPaxosAcceptorTests.java
Labels: no changelog

#4565 [Timelock Partitioning] Part 51: Wiremock integration tests for multi leader
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  timelock-server/build.gradle
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/suite/MultiLeaderPaxosSuite.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxies.java
  versions.props
Labels: no changelog

#4663 [Timelock Partitioning] Part 55: Takeover primitive
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SerializingProxy.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SimulatingServerProxy.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/benchmarks/AwaitingLeadershipProxyBenchmark.java
  leader-election-api/src/main/java/com/palantir/leader/LeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/BatchingLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  lock-impl/src/test/java/com/palantir/lock/LockServiceIntegrationTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/NamespaceTakeoverResource.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-api/src/main/conjure/timelock-paxos-api.yml
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/suite/SingleLeaderPaxosSuite.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
Labels: no changelog

#4646 [PDS-113496] Martin Lewis's Muse Part 1: Snapshot Transaction
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ResultsExtractor.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RowColumnRangeExtractor.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ValueExtractor.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-4646.v2.yml
Labels: autorelease

#4669 Lazy Initialization for ReplaceIfExceptionMatchingProxy
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ReplaceIfExceptionMatchingProxy.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ReplaceIfExceptionMatchingProxyTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/AtlasDbHttpClients.java
  changelog/@unreleased/pr-4669.v2.yml
Labels: autorelease

#4666 [Timelock Partitioning] Part 53b: Fix insiduous cache bug
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingPaxosLatestSequenceCache.java
Labels: no changelog

#4651 Make #close safer.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
Labels: autorelease, merge when ready, no changelog

#4675 Increase default buffer size to 4096
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/Autobatchers.java
  changelog/@unreleased/pr-4675.v2.yml
Labels: autorelease, merge when ready

#4677 The Wrath of Indonesia: JavaX -> Jakarta Migration
  DEPENDENCIES.md
  atlasdb-api/build.gradle
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-config/build.gradle
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/ExceptionMappersTest.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptions.java
  atlasdb-impl-shared/build.gradle
  atlasdb-persistent-lock-api/build.gradle
  atlasdb-service/build.gradle
  build.gradle
  changelog/@unreleased/pr-4677.v2.yml
  leader-election-api/build.gradle
  lock-api-objects/build.gradle
  lock-api/build.gradle
  tests.props
  timestamp-api/build.gradle
  versions.props
Labels: autorelease

#4674 [Timelock Perf] Disruptor future
  atlasdb-autobatch/build.gradle
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/Autobatchers.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/BatchElement.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/CoalescingBatchingEventHandler.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/TracingEventHandler.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/CoalescingBatchingEventHandlerTests.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/TracingEventHandlerTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/WriteBatchingTransactionService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/service/WriteBatchingTransactionServiceTest.java
  changelog/@unreleased/pr-4674.v2.yml
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuidTests.java
  timestamp-client/src/test/java/com/palantir/timestamp/RequestBatchingTimestampServiceTest.java
Labels: autorelease

#4668 Optimize getRowsColumnRange
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-4668.v2.yml
Labels: autorelease

#4679 Generate dialogue bindings for lock API
  build.gradle
  settings.gradle
  timelock-api/timelock-api-dialogue/.gitignore
  versions.props
Labels: merge when ready, no changelog

#4686 [PDS-111849] Rolling in the Deep, Part 1: Failing Test & Rerouting Internode Calls Through Proxies
  timelock-server/build.gradle
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/SingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemplateVariables.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  timelock-server/src/testCommon/resources/paxosMultiServer.ftl
Labels: no changelog
