Repository palantir/atlasdb, pull requests merged in 2020-09, with the labels that each got.

#4940 Merge some per-txn-manager thread pools into shared thread pools
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/AsyncPuncher.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/TransactionSchemaInstaller.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/internalschema/TransactionSchemaInstallerTest.java
  changelog/@unreleased/pr-4940.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/LockRefresher.java
  lock-api/src/main/java/com/palantir/lock/client/LockRefreshingLockService.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
Labels: autorelease

#4967 B g fix
  changelog/@unreleased/pr-4967.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
Labels: autorelease

#4973 [TS] Auto Tune TS Pause Between Iterations
  atlasdb-config/src/test/resources/runtime-config-block.yml
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepIterationResult.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepDelayTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  changelog/@unreleased/pr-4973.v2.yml
Labels: autorelease, merge when ready

#4976 Bug fix
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
Labels: autorelease, no changelog

#4977 Undo accidental push
  atlasdb-ete-tests/docker/conf/atlasdb-ete.dbkvs.yml
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/DbKvsTestSuite.java
Labels: merge when ready, no changelog

#4979 Bump dialogue to 1.81.0
  changelog/@unreleased/pr-4979.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#4974 Leader election slos
  changelog/@unreleased/pr-4974.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/health/LeaderElectionHealthCheck.java
  leader-election-impl/src/test/java/com/palantir/leader/LeadershipElectionCheckTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetrics.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease

#4975 [TS] Auto tune number of parallel background tasks
  atlasdb-commons/src/main/java/com/palantir/common/time/Clock.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/LockWithoutTimelockEteTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ScalingSweepTaskScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ScalingSweepTaskSchedulerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  changelog/@unreleased/pr-4975.v2.yml
Labels: autorelease

#4982 [Part 1] | TimeLock shoots itself
  timelock-api/src/main/conjure/timelock-corruption.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/CorruptionDetector.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/CorruptionHealthCheck.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/CorruptionNotifierResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/CorruptionStatus.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/LocalCorruptionDetector.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/LocalCorruptionHandler.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/RemoteCorruptionDetector.java
Labels: merge when ready, no changelog

#4985 [TS] Increase max delay
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
Labels: autorelease, merge when ready, no changelog

#4983 [Part 2] | TimeLock shoots itself
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockCorruptionComponents.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: no changelog

#4968 Transaction#markTableInvolved.
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  changelog/@unreleased/pr-4968.v2.yml
Labels: autorelease

#4986 Reject requests if corruption
  changelog/@unreleased/pr-4986.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/JerseyCorruptionFilter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/corruption/UndertowCorruptionHandlerService.java
Labels: autorelease

#4994 only log at debug for unused keystore/truststore
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  changelog/@unreleased/pr-4994.v2.yml
Labels: autorelease, merge when ready

#4989 Tl corr history
  changelog/@unreleased/pr-4989.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/NamespaceAndUseCaseAndFunction.java
  settings.gradle
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/main/java/com/palantir/history/LocalHistoryLoader.java
  timelock-corruption-detection/src/main/java/com/palantir/history/PaxosLogHistoryProvider.java
  timelock-corruption-detection/src/main/java/com/palantir/history/mappers/AcceptorPaxosRoundMapper.java
  timelock-corruption-detection/src/main/java/com/palantir/history/mappers/LearnerPaxosRoundMapper.java
  timelock-corruption-detection/src/main/java/com/palantir/history/mappers/NamespaceAndUseCaseMapper.java
  timelock-corruption-detection/src/main/java/com/palantir/history/models/AcceptorUseCase.java
  timelock-corruption-detection/src/main/java/com/palantir/history/models/CompletePaxosHistoryForNamespaceAndUseCase.java
  timelock-corruption-detection/src/main/java/com/palantir/history/models/LearnedAndAcceptedValue.java
  timelock-corruption-detection/src/main/java/com/palantir/history/models/LearnerAndAcceptorRecords.java
  timelock-corruption-detection/src/main/java/com/palantir/history/models/LearnerUseCase.java
  timelock-corruption-detection/src/main/java/com/palantir/history/models/PaxosHistoryOnSingleNode.java
  timelock-corruption-detection/src/main/java/com/palantir/history/sqlite/LogVerificationProgressState.java
  timelock-corruption-detection/src/main/java/com/palantir/history/sqlite/SqlitePaxosStateLogHistory.java
  timelock-corruption-detection/src/main/java/com/palantir/history/util/UseCaseUtils.java
  timelock-corruption-detection/src/test/java/com/palantir/history/LogVerificationStateTest.java
  timelock-corruption-detection/src/test/java/com/palantir/history/SqliteHistoryQueryTest.java
  timelock-corruption-detection/src/test/java/com/palantir/history/util/UseCaseUtilsTest.java
Labels: autorelease

#4997 Wire paxos history providers
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockCorruptionComponents.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: no changelog

#4998 Refactor corruption detectors
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimeLockCorruptionComponents.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/main/conjure/timelock-corruption.yml
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionHealthCheck.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionNotifierResource.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionStatus.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/JerseyCorruptionFilter.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionHandler.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/RemoteCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/UndertowCorruptionHandlerService.java
Labels: no changelog

#5001 [TS] Enable TS autotuning
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  changelog/@unreleased/pr-5001.v2.yml
Labels: autorelease

#5004 Use jboss-threads ViewExecutor instead of our own
  changelog/@unreleased/pr-5004.v2.yml
  commons-executors/build.gradle
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasQueuedViewExecutor.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasQueuelessViewExecutor.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasViewExecutor.java
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  versions.lock
  versions.props
Labels: merge when ready

#5006 [LW] Rename IdentifiedVersion
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/CacheUpdate.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshotState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStoreTest.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionRequestV5.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchVersion.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/TransactionsLockWatchUpdate.java
  lock-api/src/main/java/com/palantir/lock/client/CommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/LockWatchLogUtility.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api/src/test/java/com/palantir/lock/client/CommitTimestampGetterTest.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchTestRuntimeConfig.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImplTest.java
Labels: no changelog

#5005 [LW] Remove StartTransactionsv5
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionRequestV5.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionResponseV5.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
Labels: no changelog
