Repository palantir/atlasdb, pull requests merged in 2020-02, with the labels that each got.

#4548 [Timelock Partitioning] Part 50b: Fix develop
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
Labels: no changelog

#4550 [LW] Part 9(?): Lock Descriptor Utils
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtils.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CellReference.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtilsTest.java
Labels: no changelog

#4502 [LW] 2nd Prequel to Part 5: LockWatchStateUpdater
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchStateUpdater.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchStateUpdaterTest.java
Labels: no changelog

#4555 [PDS-110262] Meter for Cassandra pool exhaustion events
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetrics.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  changelog/@unreleased/pr-4555.v2.yml
Labels: merge when ready

#4543 Better log when rolled back by someone else
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  lock-api/src/main/java/com/palantir/lock/client/LeasedLockToken.java
  lock-api/src/main/java/com/palantir/lock/client/LockTokenShare.java
  lock-api/src/main/java/com/palantir/lock/v2/LockToken.java
Labels: no changelog

#4556 Make max threadpool size for Cass calls track connection pool sizes.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  changelog/@unreleased/pr-4556.v2.yml
Labels: autorelease

#4552 [PDS-109527 FLUP] TimeLock Invariant Enforcement Part 1: Only One Leader Allowed
  changelog/@unreleased/pr-4552.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/invariants/NoSimultaneousServiceCheck.java
  timelock-agent/src/main/java/com/palantir/timelock/invariants/ServerKiller.java
  timelock-agent/src/main/java/com/palantir/timelock/invariants/TimeLockActivityChecker.java
  timelock-agent/src/main/java/com/palantir/timelock/invariants/TimeLockActivityCheckerFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/invariants/NoSimultaneousServiceCheckTest.java
  timelock-agent/src/test/java/com/palantir/timelock/invariants/TimeLockActivityCheckerTest.java
Labels: autorelease

#4551 [Timelock Partitioning] Collapse silly code
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosTimestampCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: no changelog

#4562 Fix yaml formatting in changelog
  changelog/@unreleased/pr-4558.v2.yml
Labels: autorelease

#4564 Fix flakes
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/http/TestProxyUtils.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosQuorumChecker.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TimeLockServerDownIntegrationTest.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServer.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxies.java
Labels: no changelog

#4566 Revert AtlasDB metrics to before we thought there were metrics issues
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  changelog/@unreleased/pr-4566.v2.yml
Labels: autorelease

#4567 [Jepsen tests] Fix Clojure Missing Namespace Error
  atlasdb-jepsen-tests/src/jepsen/atlasdb/lock.clj
  atlasdb-jepsen-tests/src/jepsen/atlasdb/timestamp.clj
Labels: no changelog

#4573 [Conjure Java Runtime] Part 27: Security in Jepsen
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimelockUtils.java
Labels: no changelog

#4582 Update certs again.
  atlasdb-config/var/security/keyStore.jks
  atlasdb-config/var/security/trustStore.jks
  atlasdb-ete-tests/docker/security/keyStore.jks
  atlasdb-ete-tests/docker/security/trustStore.jks
  atlasdb-ete-tests/var/security/keyStore.jks
  atlasdb-ete-tests/var/security/trustStore.jks
  atlasdb-impl-shared/src/test/resources/keyStore.jks
  atlasdb-impl-shared/src/test/resources/trustStore.jks
  atlasdb-jepsen-tests/var/security/keyStore.jks
  atlasdb-jepsen-tests/var/security/trustStore.jks
  timelock-server-benchmark-client/var/security/keyStore.jks
  timelock-server-benchmark-client/var/security/trustStore.jks
  timelock-server-distribution/var/security/keyStore.jks
  timelock-server-distribution/var/security/trustStore.jks
  timelock-server/var/security/keyStore.jks
  timelock-server/var/security/trustStore.jks
Labels: no changelog

#4577 safe-tag connection pool logging
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  changelog/@unreleased/pr-4577.v2.yml
Labels: autorelease

#4587 [Timelock OOMs] Stop `PaxosQuorumChecker` cancellation
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  changelog/@unreleased/pr-4587.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosQuorumChecker.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderAcceptorNetworkClient.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderLearnerNetworkClient.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  leader-election-impl/src/test/java/com/palantir/leader/PaxosLeaderEventsTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusTestUtils.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchingNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Factories.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/SingleLeaderNetworkClientFactories.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/LeaderPingHealthCheck.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPaxosAcceptorNetworkClientFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosQuorumCheckingCoalescingFunction.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimeLockConstants.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosQuorumCheckingCoalescingFunctionTests.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
Labels: autorelease

#4590 [LW] Fix corner case in registering lock watches
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
Labels: no changelog

#4588 Safer workflow for getting rows from CassandraKvs
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraConstants.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  changelog/@unreleased/pr-4588.v2.yml
Labels: autorelease

#4600 Make KeyValueServiceRuntimeConfig jackson discoverable
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfigsTest.java
  atlasdb-config/src/main/resources/META-INF/services/io.dropwizard.jackson.Discoverable
  atlasdb-config/src/test/resources/runtime-config-block.yml
  changelog/@unreleased/pr-4600.v2.yml
Labels: autorelease

#4592 [LW] Snapshot Updates
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchCreatedEvent.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchEvent.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchOpenLocksEvent.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchStateUpdate.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchStateUpdater.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchStateUpdaterTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindow.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchTestingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatches.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/UpdateVisitors.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
Labels: no changelog

#4609 [Conjure Undertow, Part 2] Upgrade timelock dependency and inline
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/BlockingSensitiveTimelockRpcClient.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/BlockingSensitiveTimelockRpcClientTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticConjureTimelockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticTimelockRpcClient.java
  changelog/@unreleased/pr-4609.v2.yml
  lock-api-objects/build.gradle
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/v2/NamespacedTimelockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/v2/TimelockRpcClient.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease

#4606 Remove c3p0
  commons-db/build.gradle
  gradle/versions.gradle
Labels: no changelog

#4604 [LW] Expose LW Info in TM
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/IdentifiedVersion.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/TransactionsLockWatchEvents.java
Labels: no changelog
