Repository palantir/atlasdb, pull requests merged in 2021-10, with the labels that each got.

#5673 [LW] Keep additional snapshots around
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImplTest.java
  changelog/@unreleased/pr-5673.v2.yml
Labels: autorelease, merge when ready

#5671 [LW] Add tests for CacheValue
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValueTests.java
Labels: no changelog, merge when ready

#5672 [LW] Add further test coverage for LWVSCI
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
Labels: no changelog, merge when ready

#5677 [LW] Relax conditions on start transaction flow
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/FilteringValueCacheSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshotImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  changelog/@unreleased/pr-5677.v2.yml
Labels: autorelease, merge when ready

#5676 Remove jetty-alpn-agent dependency
  atlasdb-config/build.gradle
  gradle/versions.gradle
  timelock-server-benchmark-client/build.gradle
  timelock-server-benchmark-cluster/build.gradle
  timelock-server-distribution/build.gradle
  timelock-server/build.gradle
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/Http2Agent.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#5679 [LW] More logging around unusual edge case
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
Labels: no changelog, autorelease, merge when ready

#5669 InMemory timelock
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTestTools.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/InMemoryTimelockServices.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/AsyncPuncherTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableTasksTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/priority/SweepPriorityStoreTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/timelock/paxos/InMemoryTimelockServicesTest.java
  atlasdb-tests-shared/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  timelock-agent/build.gradle
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/build.gradle
  timestamp-impl/build.gradle
  timestamp-impl/src/test/java/com/palantir/timestamp/AbstractTimestampServiceTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/InMemoryTimestampServiceTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTests.java
Labels: component: testing, no changelog, merge when ready

#5682 [Exclusion Hunter] Part 14: JdkObsolete LinkedLists
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  build.gradle
  commons-executors/src/test/java/com/palantir/common/concurrent/ExecutorInheritableThreadLocalTest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
Labels: no changelog, merge when ready

#5674 [LW] More Leader Election tests for LWVIT
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: no changelog, merge when ready

#5685 [LW] Add memory metrics
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStoreTest.java
  changelog/@unreleased/pr-5685.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: autorelease, merge when ready

#5687 Exclusions: VisibleForTesting
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/IterablePartitioner.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/LoggingArgs.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowMeanGauge.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ClientOptionsConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/KeyValueServicePuncherStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  build.gradle
  lock-api/src/main/java/com/palantir/lock/client/LockRefresher.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockClientIndices.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifier.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/PaxosLogHistoryProgressTracker.java
Labels: small, no changelog, merge when ready

#5688 [LW] Improve test coverage of Timelock components
  timelock-agent/src/main/java/com/palantir/timelock/config/RestrictedTimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchTestRuntimeConfig.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImplTest.java
Labels: no changelog, merge when ready
