Repository palantir/atlasdb, pull requests merged in 2021-09, with the labels that each got.

#5615 [EH] doMock
  build.gradle
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/BlockingTimeLimitedLockServiceTest.java
Labels: no changelog

#5617 Hunt exclusions V
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellValuePutter.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/RowResults.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/SweepStatsKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/SafeLoggableDataUtils.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/KvsRangeMigratorBuilder.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/TransactionRangeMigratorBuilder.java
  atlasdb-commons/src/main/java/com/palantir/async/initializer/LambdaCallback.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  build.gradle
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogImpl.java
  lock-api-objects/src/main/java/com/palantir/lock/HeldLocksGrant.java
  lock-api-objects/src/main/java/com/palantir/lock/HeldLocksToken.java
  lock-api-objects/src/main/java/com/palantir/lock/LockRequest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
Labels: no changelog, merge when ready

#5629 Don't Overexpose Codegen Dependencies
  atlasdb-client/build.gradle
  atlasdb-processors/build.gradle
Labels: no changelog, merge when ready

#5624 [k8s TL] | Runtime clusterConfig
  atlasdb-jepsen-tests/resources/atlasdb/timelock.yml
  changelog/@unreleased/pr-5624.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/config/ClusterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/ClusterInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/RestrictedTimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/invariants/TimeLockActivityCheckerFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosRemotingUtils.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClientsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/ClusterConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockPersistenceInvariantsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockRuntimeConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/PaxosRemotingUtilsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
  timelock-server-benchmark-cluster/src/main/java/com/palantir/atlasdb/timelock/benchmarks/server/TimelockBenchmarkServerLauncher.java
  timelock-server-benchmark-cluster/var/conf/template/timelock-remote0.yml
  timelock-server-benchmark-cluster/var/conf/template/timelock-remote1.yml
  timelock-server-benchmark-cluster/var/conf/template/timelock-remote2.yml
  timelock-server-distribution/var/conf/timelock-db.yml
  timelock-server-distribution/var/conf/timelock-http2.yml
  timelock-server-distribution/var/conf/timelock-oracle.yml
  timelock-server-distribution/var/conf/timelock-postgres.yml
  timelock-server-distribution/var/conf/timelock.yml
  timelock-server/src/integTest/resources/paxosSingleServer.ftl
  timelock-server/src/integTest/resources/paxosStaticThreeServers.ftl
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
  timelock-server/src/testCommon/resources/dbTimeLockPaxosMultiServer.ftl
  timelock-server/src/testCommon/resources/paxosMultiServer.ftl
Labels: merge when ready

#5626 Increase default max fetch size for AgnosticLightResultSetImpl
  changelog/@unreleased/agnostic-light-result-set-fetch-size.v2.yml
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticLightResultSetImpl.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java
Labels: autorelease, merge when ready

#5630 Track open transactions
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-5630.v2.yml
Labels: autorelease, merge when ready

#5628 Leaky sweep
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SweepCommand.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/TodoClient.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SpecificTableSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTaskRunner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweeperService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweeperServiceImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/SweeperServiceImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/SweeperTestSetup.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/benchmarks/SweepBenchmarks.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweeperServiceImplIntegrationTest.java
  changelog/@unreleased/pr-5628.v2.yml
Labels: autorelease, merge when ready

#5631 Add metrics for cache instance count
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  changelog/@unreleased/pr-5631.v2.yml
Labels: autorelease, merge when ready

#5637 Fix Potential Missed Serializable Transaction Conflicts
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  changelog/@unreleased/pr-5637.v2.yml
Labels: autorelease, merge when ready

#5632 [PDS-210062] Fix SnapshotTransaction/Delete Executor Resource Leak
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-5632.v2.yml
Labels: autorelease, merge when ready

#5635 [LW] Additional filtering for values flushed to central cache
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/DuplicatingLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-5635.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/watch/SpanningCommitUpdate.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
Labels: merge when ready

#5644 Quality code (fix IntelliJ)
  atlasdb-processors/build.gradle
Labels: no changelog

#5646 [LW] Resolve possible resource leak
  changelog/@unreleased/pr-5646.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/BatchingCommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/BatchingIdentifiedAtlasDbTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/LockWatchLogUtility.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientCommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarterHelper.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientTransactionStarterTest.java
Labels: autorelease, merge when ready

#5653 TL server killer
  changelog/@unreleased/pr-5653.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoaderTest.java
  timelock-server-benchmark-cluster/src/main/java/com/palantir/atlasdb/timelock/benchmarks/server/TimelockBenchmarkServerLauncher.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
Labels: autorelease, merge when ready

#5643 [LW] Add testing around edge cases when committing transactions
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: no changelog, merge when ready

#5654 Nuke Persistent Lock
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/build.gradle
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/SweeperModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestSweeperModule.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/CheckAndSetExceptionMapper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/KvsBackedPersistentLockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/LockEntry.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/LockStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/LockStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/NoOpPersistentLockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CellsSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/PersistentLockManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/persistentlock/KvsBackedPersistentLockServiceClientTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/persistentlock/KvsBackedPersistentLockServiceTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/persistentlock/LockEntryTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/persistentlock/LockStoreTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/persistentlock/PersistentLockServiceClientTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/CellsSweeperShould.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/PersistentLockManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/SweeperServiceImplTest.java
  atlasdb-persistent-lock-api/build.gradle
  atlasdb-persistent-lock-api/src/main/java/com/palantir/atlasdb/persistentlock/PersistentLockId.java
  atlasdb-persistent-lock-api/src/main/java/com/palantir/atlasdb/persistentlock/PersistentLockService.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  changelog/@unreleased/pr-5654.v2.yml
  docs/source/cluster_management/backup-restore.rst
  docs/source/cluster_management/index.rst
  docs/source/release_notes/release-notes.rst
  docs/source/services/timelock_service/installation.rst
  docs/source/troubleshooting/index.rst
  settings.gradle
Labels: merge when ready

#5655 Retry Legacy Sweep Iterations
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SpecificTableSweeper.java
Labels: no changelog, autorelease, merge when ready

#5659 Reduce MNPTLSIT flakes
  atlasdb-commons/src/test/java/com/palantir/util/SafeShutdownRunnerTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: no changelog, merge when ready

#5636 Retry when starting transactions times out
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/Autobatchers.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/AutobatchersTests.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-5636.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/BatchingIdentifiedAtlasDbTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/StartTransactionFailedException.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TimeLockServerDownIntegrationTest.java
Labels: autorelease, merge when ready

#5649 Switch Cluster client to use DCAwareRR
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
  changelog/@unreleased/pr-5649.v2.yml
Labels: autorelease, merge when ready

#5660 [LW] Fix cache size metrics
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
  changelog/@unreleased/pr-5660.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: merge when ready

#5658 [LW] Add additional fail-safe mechanisms around stored state
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  changelog/@unreleased/pr-5658.v2.yml
Labels: merge when ready

#5663 [Exclusions] Part 8-13: Javadoc Exclusions
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraMutationTimestampProviders.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-commons/src/main/java/com/palantir/async/initializer/Callback.java
  atlasdb-commons/src/main/java/com/palantir/async/initializer/CallbackInitializable.java
  atlasdb-commons/src/main/java/com/palantir/util/Mutable.java
  atlasdb-commons/src/main/java/com/palantir/util/Pair.java
  atlasdb-commons/src/main/java/com/palantir/util/SoftCache.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/monitoring/profiler/SimpleSqlProfiler.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticResultRowImpl.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQLString.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/SqlConnectionHelper.java
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TsBoundPersisterConfiguration.java
Labels: no changelog, merge when ready

#5667 Exclusion Hunter VIII: EmptyBlockTag
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
  atlasdb-commons/src/main/java/com/palantir/common/collect/EmptyQueue.java
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/BlockingWorkerPool.java
  atlasdb-commons/src/main/java/com/palantir/common/random/SecureRandomPool.java
  atlasdb-commons/src/main/java/com/palantir/util/JMXUtils.java
  atlasdb-commons/src/main/java/com/palantir/util/MBeanCache.java
  atlasdb-commons/src/main/java/com/palantir/util/Pair.java
  atlasdb-commons/src/main/java/com/palantir/util/SoftCache.java
  atlasdb-commons/src/main/java/com/palantir/util/debug/StackTraceUtils.java
  atlasdb-commons/src/main/java/com/palantir/util/file/TempFileUtils.java
  atlasdb-commons/src/main/java/com/palantir/util/paging/AbstractPagingIterable.java
  atlasdb-commons/src/main/java/com/palantir/util/paging/SimpleTokenBackedResultsPage.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/sql/AbstractAgnosticResultRow.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticLightResultRowImpl.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticResultRow.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticResultRowImpl.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQLString.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/ExceptionCheck.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/SqlConnectionHelper.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPaxosAcceptor.java
Labels: no changelog, merge when ready

#5554 Exclusion Hunter VII: HidingField
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetricsAssert.java
  build.gradle
Labels: no changelog, merge when ready

#5652 [LW] Rework value cache commit flow
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerInternal.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLogEvents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/DuplicatingLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchProxyTest.java
  changelog/@unreleased/pr-5652.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/watch/SpanningCommitUpdate.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCache.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCacheImpl.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchValueCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchValueCache.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchCacheImplTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: autorelease, merge when ready

#5670 [LW] Refactor value loader to not use table reference
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ReadOnlyTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ReadOnlyTransactionScopedCacheTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
Labels: no changelog, merge when ready

#5666 [LW] Add Value Stress Test
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/LockWatchEteTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: no changelog, merge when ready
