Repository palantir/atlasdb, pull requests merged in 2021-05, with the labels that each got.

#5411 Exclusion Hunter II: AnnotateFormatMethod
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/Log4JTracingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/StdoutTracingTransaction.java
  atlasdb-processors/src/main/java/com/palantir/processors/ProcessingException.java
  build.gradle
Labels: merge when ready, no changelog

#5402 [LW] Wire cache into transactions
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValue.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/HitDigest.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueDigest.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerInternal.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/AsyncLockClient.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimestampClient.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchStateUpdate.java
  lock-api/src/main/java/com/palantir/lock/client/BatchingCommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/BatchingIdentifiedAtlasDbTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientCommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedCommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedIdentifiedTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/RequestBatchersFactory.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarterHelper.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCacheImpl.java
  lock-api/src/main/java/com/palantir/lock/watch/StartTransactionsLockWatchEventCache.java
  lock-api/src/test/java/com/palantir/lock/client/BatchingCommitTimestampGetterTest.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientCommitTimestampGetterTest.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientTransactionStarterTest.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchCacheImplTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
Labels: autorelease, merge when ready, no changelog

#5417 [LW] Fix rare edge case
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  changelog/@unreleased/pr-5417.v2.yml
Labels: merge when ready

#5413 [LW] Fix bugs and be protective, I
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  changelog/@unreleased/pr-5413.v2.yml
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCacheImpl.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchValueCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchValueCache.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchCacheImplTest.java
Labels: autorelease, merge when ready

#5421 Transaction onSuccess(Runnable) / Callback Registration
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-5421.v2.yml
Labels: autorelease

#5418 [LW] Resilient Proxy for the value cache
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/ResilientLockWatchProxy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchProxyTest.java
  changelog/@unreleased/pr-5418.v2.yml
Labels: merge when ready

#5423 Upgrade GBJ
  build.gradle
  lock-impl/src/test/java/com/palantir/lock/LockServiceTest.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
Labels: autorelease, merge when ready, no changelog

#5429 Be better
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
Labels: autorelease, merge when ready, no changelog

#5431 Fix internal errors
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureResourceExceptionHandler.java
Labels: autorelease, merge when ready, no changelog

#5428 Use HttpURLConnection for hitting host metadata endpoint
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
  changelog/@unreleased/pr-5428.v2.yml
Labels: autorelease, merge when ready

#5433 [LW] Serializable Transactions Part II: updateCacheOnCommit
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchProxyTest.java
  changelog/@unreleased/pr-5433.v2.yml
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCacheImpl.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchValueCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchValueCache.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchCacheImplTest.java
Labels: merge when ready

#5436 Add explicit dependency on okio
  atlasdb-api/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-client/build.gradle
Labels: autorelease, merge when ready, no changelog

#5442 [LW] Make the value cache configurable
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/LockWatchCachingConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  changelog/@unreleased/pr-5442.v2.yml
Labels: merge when ready

#5441 [LW] Integration Tests
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/util/ByteArrayUtilities.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TransactionPostMortemIntegrationTest.java
  timelock-server/src/integTest/resources/paxosSingleServer.ftl
  timelock-server/src/integTest/resources/paxosStaticThreeServers.ftl
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtils.java
Labels: autorelease, merge when ready, no changelog

#5447 [PDS-184114] Interrupts look sus
  changelog/0.336.4-rc1/pr-5447.v2.yml
  changelog/@unreleased/pr-5447.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureResourceExceptionHandler.java
Labels: :white_check_mark: Prod validated, autorelease, merge when ready

#5449 [LW] Metrics
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValue.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/ResilientLockWatchProxy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchProxyTest.java
  atlasdb-impl-shared/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: do not merge, no changelog

#5448 [LW] Leader Election Tests
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
  timelock-server/src/testCommon/resources/dbTimeLockPaxosMultiServer.ftl
  timelock-server/src/testCommon/resources/paxosMultiServer.ftl
Labels: no changelog

#5450 [LW] Cache getRows
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/ColumnSelection.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ReadOnlyTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/Cells.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/util/ByteArrayUtilities.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
  changelog/@unreleased/pr-5450.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: autorelease, merge when ready

#5455 [LW] [PDS-185998] Log when removing entries from the cache store
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  changelog/@unreleased/pr-5455.v2.yml
Labels: merge when ready

#5454 [LW] Throw when exceeding maximum cache store size
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  changelog/@unreleased/pr-5454.v2.yml
Labels: autorelease, merge when ready

#5451 Remove some unused atlasdb-cassandra dependencies
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-multinode-tests/build.gradle
  atlasdb-cassandra/build.gradle
  versions.lock
Labels: autorelease, merge when ready, no changelog

#5460 [LW] Bug Hunter
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerInternal.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/ResilientLockWatchProxy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpLockWatchValueScopingCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ResilientLockWatchProxyTest.java
  changelog/@unreleased/pr-5460.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: autorelease, merge when ready

#5464 [LW] Remove noisy logline
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  changelog/@unreleased/pr-5464.v2.yml
Labels: autorelease, merge when ready

#5438 [PDS-183571] Maximum Lock Tenuring, Part 1: Forced Release
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/TransactionConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/InstrumentedTimelockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-5438.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/ClientLockingOptions.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/LockRefresher.java
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  lock-api/src/test/java/com/palantir/lock/client/LockRefresherTest.java
  lock-api/src/test/java/com/palantir/lock/client/TimeLockClientTest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LegacyTimelockService.java
Labels: autorelease

#5466 Add traces for kvs-get
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TaskRunner.java
  changelog/@unreleased/pr-5466.v2.yml
Labels: autorelease, merge when ready

#5465 [DbTL 2021] Part 2: Oracle Container Integration (ETEs)
  .circleci/config.yml
  atlasdb-ete-tests/build.gradle
  atlasdb-ete-tests/docker-compose.oracle.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.oracle.yml
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/EteSetup.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/OracleDbKvsEteTestSuite.java
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog

#5412 Cassandra calls use tracing tags.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlQuery.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingCassandraClient.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/tracing/CloseableTrace.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/tracing/Tracing.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueServiceTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/tracing/CloseableTraceTest.java
  changelog/@unreleased/pr-5412.v2.yml
Labels: autorelease, merge when ready
