Repository palantir/atlasdb, pull requests merged in 2021-11, with the labels that each got.

#5719 [LW] Add additional leader election tests to event cache
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchEventIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: no changelog, merge when ready

#5725 [Exclusion Hunter] Part 18: UndefinedEquals
  build.gradle
Labels: no changelog, merge when ready

#5726 [Exclusion Hunter] Part 19: UseCorrectAssertInTests
  build.gradle
Labels: no changelog, merge when ready

#5741 Exclusion Hunter X: PreferSafeLoggableExceptions
  atlasdb-commons/src/main/java/com/palantir/common/compression/StreamCompression.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ConjureJavaRuntimeTargetFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  build.gradle
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosQuorumChecker.java
  lock-api-objects/src/main/java/com/palantir/lock/AtlasLockDescriptorRanges.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
Labels: no changelog, merge when ready

#5717 [LW] Add tests for LockWatchEventCacheImpl
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImplTest.java
Labels: no changelog, merge when ready

#5720 [Migrate to Gradle 7] | Remove testCompile
  atlasdb-api/build.gradle
  atlasdb-autobatch/build.gradle
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-multinode-tests/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-cli/build.gradle
  atlasdb-client/build.gradle
  atlasdb-commons/build.gradle
  atlasdb-config/build.gradle
  atlasdb-conjure/build.gradle
  atlasdb-console/build.gradle
  atlasdb-container-test-utils/build.gradle
  atlasdb-coordination-impl/build.gradle
  atlasdb-dbkvs-tests/build.gradle
  atlasdb-dbkvs/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-jdbc-tests/build.gradle
  atlasdb-jepsen-tests/build.gradle
  atlasdb-perf/build.gradle
  atlasdb-processors-tests/build.gradle
  atlasdb-remoting-api/build.gradle
  atlasdb-service/build.gradle
  atlasdb-tests-shared/build.gradle
  changelog/@unreleased/pr-5720.v2.yml
  commons-db/build.gradle
  commons-executors/build.gradle
  examples/profile-client/build.gradle
  flake-rule/build.gradle
  gradle/shared.gradle
  leader-election-impl/build.gradle
  lock-api/build.gradle
  lock-impl/build.gradle
  timelock-agent/build.gradle
  timelock-corruption-detection/build.gradle
  timelock-impl/build.gradle
  timelock-server/build.gradle
  timestamp-api/build.gradle
  timestamp-client/build.gradle
  timestamp-impl/build.gradle
Labels: autorelease, merge when ready

#5722 [LW] Improve Event Cache Concurrency for singleton operations
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStoreState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogTest.java
  changelog/0.454.0-rc1/pr-5722.v2.yml
  changelog/0.456.0-rc1/pr-5722.v2.yml
  changelog/0.456.0-rc2/pr-5722.v2.yml
  changelog/@unreleased/pr-5722.v2.yml
Labels: autorelease, merge when ready

#5749 Kill LeaderElectionHealthCheck
  changelog/@unreleased/pr-5749.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/health/LeaderElectionHealthCheck.java
  leader-election-impl/src/test/java/com/palantir/leader/health/LeadershipElectionCheckTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/Dependencies.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetrics.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease, merge when ready

#5742 Exclusion Hunter XI: PreferSafeLoggingPreconditions
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/lock/LockAcquisitionLivenessChecker.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/PathTypeTrackers.java
  build.gradle
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientTransactionStarter.java
Labels: no changelog, merge when ready

#5708 ABR1: AtlasBackupService
  atlasdb-backup/build.gradle
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/AtlasBackupServiceTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LocalLockTracker.java
  changelog/@unreleased/pr-5708.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  settings.gradle
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AtlasBackupResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/backup/AtlasBackupResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/ConjureTimelockResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/util/TimelockTestUtils.java
Labels: component: timelock, autorelease, merge when ready

#5751 Exclusion Hunter XII: ImmutablesBuilderMissingInitialisation
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CandidateCellForSweeping.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbConfigTest.java
  build.gradle
Labels: no changelog, merge when ready

#5750 Add warning about non-standard topology
  docs/source/configuration/external_timelock_service_configs/timelock_client_config.rst
Labels: component: documentation, small, no changelog, merge when ready

#5721 [Migrate to Gradle 7] | Remove compile for external deps
  atlasdb-api/build.gradle
  atlasdb-autobatch/build.gradle
  atlasdb-client-protobufs/build.gradle
  atlasdb-client/build.gradle
  atlasdb-commons/build.gradle
  atlasdb-config/build.gradle
  atlasdb-console/build.gradle
  atlasdb-container-test-utils/build.gradle
  atlasdb-coordination-impl/build.gradle
  atlasdb-dagger/build.gradle
  atlasdb-dbkvs-hikari/build.gradle
  atlasdb-dbkvs/build.gradle
  atlasdb-ete-test-utils/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-jdbc-tests/build.gradle
  atlasdb-jdbc/build.gradle
  atlasdb-jepsen-tests/build.gradle
  atlasdb-perf/build.gradle
  atlasdb-processors/build.gradle
  atlasdb-remoting-api/build.gradle
  atlasdb-service/build.gradle
  atlasdb-tests-shared/build.gradle
  changelog/@unreleased/pr-5721.v2.yml
  commons-db/build.gradle
  commons-proxy/build.gradle
  examples/profile-client-protobufs/build.gradle
  flake-rule/build.gradle
  gradle/shared.gradle
  leader-election-api-protobufs/build.gradle
  leader-election-api/build.gradle
  leader-election-impl/build.gradle
  lock-api-objects/build.gradle
  lock-api/build.gradle
  lock-impl/build.gradle
  timelock-agent/build.gradle
  timelock-corruption-detection/build.gradle
  timelock-impl/build.gradle
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/TimeLockServicesTest.java
  timelock-server-benchmark-client/build.gradle
  timelock-server/build.gradle
  timestamp-api/build.gradle
  timestamp-client/build.gradle
  timestamp-impl/build.gradle
Labels: autorelease, merge when ready

#5727 [Exclusion Hunter] Part 20: ThrowError
  atlasdb-commons/src/main/java/com/palantir/common/collect/IteratorUtils.java
  atlasdb-commons/src/main/java/com/palantir/common/compression/StreamCompression.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SimulatingServerProxy.java
  atlasdb-commons/src/main/java/com/palantir/util/ByteArrayIOStream.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunner.java
  build.gradle
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/SimulatingFailingServerProxy.java
Labels: no changelog, merge when ready

#5755 [Migrate to Gradle 7] | Migrate runtime deps
  atlasdb-cli-distribution/build.gradle
  atlasdb-console-distribution/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-impl-shared/build.gradle
  timelock-server-distribution/build.gradle
  timelock-server/build.gradle
Labels: no changelog, merge when ready

#5746 Don't perform async initialization on calling thread
  atlasdb-commons/src/main/java/com/palantir/async/initializer/AsyncInitializer.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/AsyncInitializerTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/keyvalue/impl/AsyncInitializeableInMemoryKvs.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/AsyncInitializeableInMemoryTimestampService.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactoryTest.java
  changelog/@unreleased/pr-5746.v2.yml
Labels: autorelease, merge when ready

#5761 Fix dependency break
  atlasdb-client-protobufs/build.gradle
  atlasdb-client/build.gradle
Labels: no changelog, autorelease, merge when ready

#5766 Avoid exposing com.palantir.common:streams to consumers
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
Labels: no changelog, autorelease, merge when ready

#5762 "Fix" IntelliJ dependency discovery issue
  atlasdb-processors/build.gradle
Labels: no changelog, merge when ready

#5767 Exclusions: ImmutableEnum
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategy.java
  atlasdb-commons/src/main/java/com/palantir/util/crypto/Sha256Hash.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/Sweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/SweepableCellFilterParametrizedTest.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/monitoring/profiler/SimpleSqlProfiler.java
Labels: no changelog, merge when ready

#5757 TLA: fix log-spam
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionManager.java
  atlasdb-commons/src/main/java/com/palantir/util/RateLimitedLogger.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/priority/SweepPriorityCalculator.java
  leader-election-impl/src/main/java/com/palantir/leader/LeadershipEvents.java
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/paxos/PersistedRateLimitingLeadershipPrioritiser.java
Labels: component: usability, no changelog, merge when ready

#5759 ABR2: Coordination service state checking
  atlasdb-backup/build.gradle
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/BackupPersister.java
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/CoordinationServiceRecorder.java
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/InMemoryBackupPersister.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/AtlasBackupServiceTest.java
  atlasdb-backup/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  atlasdb-coordination-impl/src/main/java/com/palantir/atlasdb/coordination/ValueAndBound.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/InternalSchemaMetadataState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/CoordinationServices.java
  changelog/@unreleased/pr-5759.v2.yml
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AtlasBackupResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/backup/AtlasBackupResourceTest.java
Labels: merge when ready

#5771 ABR3: Backup persistence
  atlasdb-backup/build.gradle
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/BackupPersister.java
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/ExternalBackupPersister.java
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/InMemoryBackupPersister.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/ExternalBackupPersisterTest.java
  changelog/@unreleased/pr-5771.v2.yml
Labels: merge when ready

#5778 Downgrade okio
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#5784 Exclulsion Hunter: London Calling (JavaTimeDefaultTimeZone)
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/priority/StreamStoreRemappingSweepPriorityCalculatorTest.java
  build.gradle
Labels: component: devEx, no changelog, merge when ready

#5782 [EH] TypeParameterUnusedInFormals
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/SingleBackendCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestSweepCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestTimestampCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/runner/AbstractTestRunner.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/runner/InMemoryTestRunner.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/runner/SingleBackendCliTestRunner.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/AtlasDbServicesFactory.java
  atlasdb-processors-tests/src/main/java/com/palantir/processors/GenericsTester.java
  build.gradle
Labels: no changelog, merge when ready

#5785 Exclusion Hunter 4: A New Hope (for final classes)
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/progress/SweepProgressStoreImpl.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/proto/fork/ForkedJsonFormat.java
  build.gradle
Labels: component: devEx, no changelog, merge when ready

#5786 [TS] More aggressive backoff for TS when a Cassandra node is down
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ScalingSweepTaskSchedulerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepDelayTest.java
  changelog/@unreleased/pr-5786.v2.yml
Labels: autorelease, merge when ready

#5758 TCTS telemetry | Last request reference
  changelog/@unreleased/pr-5758.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/TimestampCorroboratingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/TimestampCorroboratingTimelockServiceTest.java
Labels: merge when ready

#5788 [Transactions3] TimedConsensusForgettingStore
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/pue/InstrumentedConsensusForgettingStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
  atlasdb-impl-shared/src/main/metrics/consensus-forgetting-store.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/pue/InstrumentedConsensusForgettingStoreTest.java
  changelog/@unreleased/pr-5788.v2.yml
Labels: autorelease

#5780 Remove okio dependency
  atlasdb-api/build.gradle
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtils.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/persistent/api/PersistentStore.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtilsTest.java
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceGetRowKeysInRangeTest.java
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/cas/CheckAndSetResponseDecoder.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/cas/CheckAndSetRunner.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServicePueTest.java
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/cache/DefaultOffHeapCache.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/cache/DeltaEncodingTimestampEntryMapper.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/cache/LongEntryMapper.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/persistent/rocksdb/RocksDbPersistentStore.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/cache/DeltaEncodingTimestampEntryMapperTests.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/cache/LongEntryMapperTests.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/persistent/rocksdb/RocksDbPersistentStoreTests.java
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#5791 Don't publish docs from tag builds
  .circleci/config.yml
Labels: no changelog, merge when ready

#5789 [Transactions3] Integration tests, meet transactions3.
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTransactionIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionSchemaVersionEnforcement.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemorySerializableTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemoryTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionSchemaVersionEnforcementTest.java
Labels: no changelog

#5790 [Transactions3] Wiring ETE Tests To Use Transactions3
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTransactionIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsSerializableTransactionTest.java
  atlasdb-ete-tests/build.gradle
  atlasdb-ete-tests/docker/conf/atlasdb-ete.no-leader.cassandra.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.timelock.cassandra.yml
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionSchemaVersionEnforcement.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemorySerializableTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemoryTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionSchemaVersionEnforcementTest.java
Labels: no changelog

#5792 [EH] Precision Throw
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/paging/CassandraRangePagingIterable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/DatabasesContainer.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/cli/AtlasDbPerfCli.java
  build.gradle
Labels: no changelog, merge when ready

#5794 [Transactions3] Read Coordination Service at ReadConsistency.SERIAL
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RangeLoader.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/ReadConsistencyProvider.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/ReadConsistencyProviderTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/AtlasDbConstantsTest.java
  changelog/@unreleased/pr-5794.v2.yml
Labels: autorelease, merge when ready

#5797 [Transactions3] Resolve accidental flakes around concurrentUpdatesAndReadsPermitted
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/ReadConsistencyProviderTest.java
Labels: no changelog
