Repository palantir/atlasdb, pull requests merged in 2021-06, with the labels that each got.

#5475 [LW] Fix getRows Caching
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/util/ByteArrayUtilities.java
  changelog/@unreleased/pr-5475.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: autorelease, merge when ready

#5467 Add metadata to kvs-get span
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellValuePutter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TaskRunner.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TaskRunnerTest.java
  changelog/@unreleased/pr-5467.v2.yml
Labels: autorelease, merge when ready

#5480 Get off the blacklisted version of conjure lib
  versions.lock
  versions.props
Labels: autorelease, merge when ready, no changelog

#5483 add operation name
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/DefaultCassandraAsyncKeyValueServiceFactory.java
  changelog/@unreleased/pr-5483.v2.yml
Labels: autorelease, merge when ready

#5484 fix operation name
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingCassandraClient.java
  changelog/@unreleased/pr-5483.v2.yml
  changelog/@unreleased/pr-5484.v2.yml
Labels: autorelease, merge when ready

#5490 [LW] Log the type of failed validation
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  changelog/@unreleased/pr-5490.v2.yml
Labels: autorelease, merge when ready

#5491 Exclusion Hunter III: AssertionFailureIgnored
  build.gradle
Labels: merge when ready, no changelog

#5489 Improve utility of SQLException logging
  changelog/@unreleased/pr-5489.v2.yml
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQLUtils.java
  commons-db/src/test/java/com/palantir/nexus/db/sql/BasicSQLTest.java
Labels: merge when ready

#5493 Delete the (dangerous) SingleCallProxy
  atlasdb-commons/src/main/java/com/palantir/common/base/BatchingVisitableFromIterable.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SingleCallProxy.java
  changelog/@unreleased/pr-5493.v2.yml
Labels: autorelease, merge when ready

#5496 fix oracle ete tests
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleTestSuite.java
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-ete-tests/docker-compose.oracle.yml
  changelog/@unreleased/pr-5496.v2.yml
  scripts/circle-ci/run-circle-tests.sh
Labels: merge when ready

#5497 Make TransactionConflictExceptions actually useful
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionConflictException.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionSerializableConflictException.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  changelog/@unreleased/pr-5497.v2.yml
Labels: autorelease, merge when ready

#5498 Reduce flakes in the SingleLeaderPaxosSuite
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
Labels: merge when ready, no changelog

#5502 Fix LWMI flakes
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
Labels: merge when ready, no changelog

#5501 Rise of the Coffee Elf (Java 11 Adoption)
  .circleci/config.yml
  atlasdb-api/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-ete-test-utils/build.gradle
  atlasdb-ete-tests/Dockerfile
  atlasdb-ete-tests/build.gradle
  atlasdb-jepsen-tests/resources/cassandra/cassandra-env.sh
  atlasdb-processors/src/main/java/com/palantir/processors/AutoDelegateProcessor.java
  changelog/@unreleased/pr-5501.v2.yml
  gradle/shared.gradle
  scripts/circle-ci/run-circle-tests.sh
  timelock-server-distribution/Dockerfile
Labels: autorelease

#5503 [PDS-146088] Validations must not throw an exception or the commons-pool implodes
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
  changelog/@unreleased/pr-5503.v2.yml
Labels: autorelease, merge when ready

#5504 python3-pip
  .circleci/config.yml
Labels: autorelease, merge when ready, no changelog

#5492 Make maxConnectionAge default 888 seconds (a little less than 15min)
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
  changelog/@unreleased/pr-5492.v2.yml
  docs/source/configuration/key_value_service_configs/postgres_key_value_service_config.rst
Labels: merge when ready

#5506 Change semantics of priority tables to be exclusive
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/priority/NextTableToSweepProvider.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/priority/NextTableToSweepProviderTest.java
  changelog/@unreleased/pr-5506.v2.yml
  docs/source/cluster_management/sweep/standard-sweep.rst
Labels: autorelease, merge when ready

#5508 fix docs publishing
  docs/source/code-block-with-version-replacement.py
  docs/source/conf.py
  docs/source/miscellaneous/doc/adr/0001-record-architecture-decisions.md
  docs/source/miscellaneous/doc/adr/0002-prevent-tables-from-being-creating-simultaneously-in-cassandra-via-a-locks-table.md
  docs/source/miscellaneous/doc/adr/0003-tagging-for-releases-and-long-term-support.md
  docs/source/miscellaneous/doc/adr/0004-create-schema-lock-table-via-a-one-off-cli-command.md
  docs/source/miscellaneous/doc/adr/0005-stop-allowing-embedded-lock-and-timestamp-services-in-production.md
  docs/source/miscellaneous/doc/adr/0006-create-schema-lock-table-using-configuration.md
  docs/source/miscellaneous/doc/adr/0007-use-cql-for-column-paging-for-sweep.md
  docs/source/miscellaneous/doc/adr/0008-add-heartbeat-for-schema-lock-holders.md
  docs/source/miscellaneous/doc/adr/0009-load-and-read-streams-in-same-transaction.md
  docs/source/miscellaneous/doc/adr/0010-use-partial-row-complete-cell-batching-in-gettimestampsbycell.md
  docs/source/miscellaneous/doc/adr/0011-retry-long-running-locks-via-blockingtimeoutexception.md
  docs/source/miscellaneous/doc/adr/0012-batch-timestamp-requests-on-the-client-side.md
  docs/source/miscellaneous/doc/adr/0013-write-cassandra-tombstones-and-sentinels-with-a-fresh-cassandra-timestamp.md
  docs/source/miscellaneous/doc/adr/0014-targeted-sweep.md
  docs/source/miscellaneous/doc/adr/0015-batch-asynchronous-post-transaction-unlock-calls.md
  docs/source/miscellaneous/doc/adr/0016-use-tickets-encoding-for-transactions.md
Labels: autorelease, merge when ready

#5507 Exclusion Hunter IV: CatchBlockLogException
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Cell.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/Blacklist.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutorImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostnamesByIpSupplier.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingPrefsConfig.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ValidatingQueryRewritingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schema.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/tracing/Tracing.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/ExperimentRunningProxy.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/PredicateSwitchedProxy.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/DiscoverableSubtypeResolver.java
  atlasdb-coordination-impl/src/main/java/com/palantir/atlasdb/coordination/keyvalue/KeyValueServiceCoordinationStore.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableValueStyleCache.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/persistentlock/LockStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/AbortingCommitTsLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/PersistentLockManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  build.gradle
  changelog/@unreleased/pr-5507.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/PaxosLeaderElectionService.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipCoordinator.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogImpl.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockAcquirer.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AutobatchingPingableLeaderFactory.java
Labels: merge when ready

#5511 Upgrade assertj 3.20.1 & safe-logging 1.15.0
  .java-version
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
  versions.lock
  versions.props
Labels: autorelease, component: testing, merge when ready, no changelog

#5514 Replace trove with eclipse-collections
  DEPENDENCIES.md
  atlasdb-cassandra/build.gradle
  atlasdb-dbkvs/build.gradle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/sweep/CandidateGroupingIterator.java
  atlasdb-impl-shared/build.gradle
  gradle/versions.gradle
  lock-impl/build.gradle
  lock-impl/src/main/java/com/palantir/lock/impl/LockClientIndices.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServerSync.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#5516 Upgrade assertj 3.20.2
  changelog/@unreleased/pr-5516.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5519 [DB TimeLock] 3A: AtlasDB Runtime Configuration for TimeLock
  atlasdb-api/src/main/java/com/palantir/atlasdb/timestamp/DbTimeLockFactory.java
  changelog/@unreleased/pr-5519.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/ServiceDiscoveringDatabaseTimeLockSupplier.java
  timelock-agent/src/main/java/com/palantir/timelock/config/DatabaseTsBoundPersisterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/DatabaseTsBoundPersisterRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PermittedKeyValueServiceTypes.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TsBoundPersisterRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/ServiceDiscoveringDatabaseTimeLockSupplierTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/PermittedKeyValueServiceTypesTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
  timelock-server-benchmark-cluster/src/main/java/com/palantir/atlasdb/timelock/benchmarks/server/TimelockBenchmarkServerLauncher.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
Labels: autorelease, merge when ready

#5521 [DB TimeLock] 3A.2 Silly errors
  changelog/@unreleased/pr-5521.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/config/DatabaseTsBoundPersisterRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
Labels: autorelease, merge when ready

#5518 [Exclusions] Missing fail is a fail
  build.gradle
  lock-impl/src/test/java/com/palantir/lock/impl/ClientAwareLockTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ThreadPooledWrapperTest.java
Labels: no changelog
