Repository palantir/atlasdb, pull requests merged in 2021-07, with the labels that each got.

#5522 bump libthrift to 0.12.0
  changelog/@unreleased/pr-5522.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5527 revert metadata
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellValuePutter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TaskRunner.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TaskRunnerTest.java
  changelog/@unreleased/pr-5527.v2.yml
Labels: autorelease, merge when ready

#5531 Upgrade dependencies
  atlasdb-conjure/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/AbortingCommitTsLoader.java
  versions.lock
  versions.props
Labels: merge when ready, no changelog

#5534 Fix build; revert implicit dependency check
  atlasdb-api/build.gradle
  atlasdb-autobatch/build.gradle
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-client/build.gradle
  atlasdb-commons/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-tests-shared/build.gradle
  build.gradle
  changelog/@unreleased/pr-5534.v2.yml
  commons-db/build.gradle
  commons-executors-api/build.gradle
  leader-election-impl/build.gradle
  lock-api/build.gradle
  lock-impl/build.gradle
  timelock-agent/build.gradle
  timelock-corruption-detection/build.gradle
  timelock-impl/build.gradle
  timelock-server/build.gradle
Labels: autorelease, merge when ready

#5533 [LW] Reduce flakes on ETE test
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/LockWatchEteTest.java
Labels: merge when ready, no changelog

#5540 Simplify assertions
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbConfigTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
Labels: merge when ready, no changelog

#5539 [PDS-198280] Banishing Corrupted Banishment: Prevent TimeLock Self-Confusion
  changelog/@unreleased/pr-5539.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactoryTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/transaction/timestamp/LeadershipGuardedClientAwareManagedTimestampService.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/transaction/timestamp/LeadershipGuardedClientAwareManagedTimestampServiceTest.java
Labels: autorelease, merge when ready

#5541 Replace the Jackson Afterburner module with Blackbird
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/WriteReferencePersister.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/progress/SweepProgressStoreImpl.java
  changelog/@unreleased/pr-5541.v2.yml
  versions.lock
Labels: merge when ready

#5547 Fix some issues
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureResourceExceptionHandler.java
Labels: autorelease, merge when ready, no changelog

#5546 Remove some unused dependencies
  atlasdb-config/build.gradle
  timelock-impl/build.gradle
  versions.lock
Labels: merge when ready, no changelog

#5545 [PDS-198346] Internal Errors - Propagate Exception Types Correctly
  changelog/@unreleased/pr-5545.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/BlockingTimeLimitedLockService.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/BlockingTimeLimitedLockServiceTest.java
Labels: autorelease, merge when ready

#5526 make transactions table safe;
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConstants.java
  changelog/@unreleased/pr-5526.v2.yml
Labels: autorelease, merge when ready

#5530 reduce backoff
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java
  changelog/0.370.0-rc1/pr-5530.v2.yml
  changelog/@unreleased/pr-5530.v2.yml
Labels: autorelease, merge when ready

#5550 Migrate from direct blackbird/afterburner usage to the CJR wrapper
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/WriteReferencePersister.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/progress/SweepProgressStoreImpl.java
  changelog/@unreleased/pr-5550.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5553 Exclusion Hunter VI: CatchFail
  build.gradle
Labels: merge when ready, no changelog

#5555 Move isNewService check to TimelockAgent
  changelog/@unreleased/pr-5555.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClientsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosInstallConfigurationIntegrationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockPersistenceInvariantsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/PaxosRemotingUtilsTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
Labels: autorelease, merge when ready

#5559 Format generated code using Goethe (palantir-java-format for javapoet)
  atlasdb-client/build.gradle
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/AllValueTypesTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/ApiTestTableFactory.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/HashComponentsTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestV2Table.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableClassRendererV2.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableFactoryRenderer.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemaHotspottingTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemaTest.java
  atlasdb-processors/build.gradle
  atlasdb-processors/src/main/java/com/palantir/processors/AutoDelegateProcessor.java
  changelog/@unreleased/pr-5559.v2.yml
  versions.lock
  versions.props
Labels: merge when ready

#5558 AutoDelegateProcessor supports gradle incremental builds
  atlasdb-processors/src/main/java/com/palantir/processors/AutoDelegateProcessor.java
  atlasdb-processors/src/main/java/com/palantir/processors/TypeToExtend.java
  atlasdb-processors/src/main/resources/META-INF/gradle/incremental.annotation.processors
  changelog/@unreleased/pr-5558.v2.yml
Labels: merge when ready

#5565 [Exclusions] ShortCircuitBoolean
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/Event.java
  build.gradle
Labels: merge when ready, no changelog

#5562 [Exclusions] NonAtomicVolatileUpdate
  atlasdb-commons/src/main/java/com/palantir/util/AggregatingVersionedSupplier.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/AsyncInitializerTest.java
  build.gradle
  timestamp-impl/src/test/java/com/palantir/timestamp/InMemoryTimestampBoundStore.java
Labels: merge when ready, no changelog

#5552 Exclusion Hunter V: DefaultCharset
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtils.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTableCreator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/ThriftObjectSizeUtilsTest.java
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/ScrubQueueMigrationCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestScrubQueueMigrationCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestSweepCommand.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/persistent/rocksdb/RocksDbPersistentStore.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schema.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/AbstractSchemaApiTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/transaction/impl/ReadTransactionShould.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/SinglePingableLeaderTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/SimpleTodoResource.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/TodoClient.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/ExaminedCellLimitTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/GetRowsColumnRangeIteratorTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableSplittingKeyValueServiceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/ptobject/EncodingUtilsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/StreamTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweepTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CachingTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  build.gradle
  lock-api-objects/src/main/java/com/palantir/lock/AtlasCellLockDescriptor.java
  lock-api-objects/src/main/java/com/palantir/lock/AtlasLockDescriptorRanges.java
  lock-api-objects/src/main/java/com/palantir/lock/AtlasRowLockDescriptor.java
  lock-impl/src/main/java/com/palantir/lock/logger/LockStateYamlWriter.java
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/benchmarks/KvsWriteBenchmark.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceTransactionIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TimeLockServerDownIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java
Labels: merge when ready, no changelog
