Repository palantir/atlasdb, pull requests merged in 2021-04, with the labels that each got.

#5357 Sanitizing the Git Version for Correct Snapshot Publishing
  build.gradle
Labels: no changelog

#5361 Remove usage of unsupported dropRight (only in Groovy 3.0)
  build.gradle
Labels: no changelog

#5367 [PDS-146088/174322] Actually take details of stacktraces
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  changelog/@unreleased/pr-5367.v2.yml
Labels: autorelease, merge when ready

#5365 add dbkvs runtime password config
  atlasdb-api/src/main/java/com/palantir/atlasdb/timestamp/DbTimeLockFactory.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceRuntimeConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/RelationalDbTimeLockFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ConnectionManagerAwareDbKvs.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryDbTimeLockFactory.java
  changelog/@unreleased/pr-5365.v2.yml
Labels: merge when ready

#5363 [DB TimeLock 2021] Parts 3 and 4: Blob Store and Config Change Protection
  changelog/@unreleased/pr-5363.v2.yml
  timelock-agent/build.gradle
  timelock-agent/src/main/java/com/palantir/timelock/config/DatabaseTsBoundPersisterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosTsBoundPersisterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TsBoundPersisterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/main/java/com/palantir/timelock/store/BlobStoreUseCase.java
  timelock-agent/src/main/java/com/palantir/timelock/store/PersistenceConfigStore.java
  timelock-agent/src/main/java/com/palantir/timelock/store/SqliteBlobStore.java
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosTsBoundPersisterConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentPersistedConfigTest.java
  timelock-agent/src/test/java/com/palantir/timelock/store/BlobStoreUseCaseTest.java
  timelock-agent/src/test/java/com/palantir/timelock/store/PersistenceConfigStoreTest.java
  timelock-agent/src/test/java/com/palantir/timelock/store/SqliteBlobStoreTest.java
  timelock-server-benchmark-cluster/src/main/java/com/palantir/atlasdb/timelock/benchmarks/server/TimelockBenchmarkServerLauncher.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
Labels: autorelease, merge when ready

#5376 LW Caching I: Basic interfaces
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionDigest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  changelog/@unreleased/pr-5376.v2.yml
Labels: merge when ready

#5374 fix dbkvs runtime config
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceRuntimeConfig.java
  changelog/@unreleased/pr-5374.v2.yml
Labels: autorelease

#5382 LW Caching III, A: Fix AtlasLockDescriptorUtils
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtils.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtilsTest.java
  changelog/@unreleased/pr-5382.v2.yml
Labels: merge when ready

#5383 [PDS-176064] burning smoke and bullet fire | getSortedColumns now avoids local writes correctly
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  changelog/@unreleased/pr-5383.v2.yml
Labels: autorelease

#5378 LW Cache III, B: Centralised Cache
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheEntry.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/StructureHolder.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshotImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/lock/watch/LockWatchReferencesVisitor.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImplTest.java
  changelog/@unreleased/pr-5378.v2.yml
  versions.lock
  versions.props
Labels: merge when ready

#5390 dependencies to latest
  versions.lock
  versions.props
Labels: no changelog

#5381 LW Cache IV: Per-Transaction Caching
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheEntry.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionCacheValueStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionCacheValueStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshotImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionCacheValueStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStoreTest.java
  changelog/@unreleased/pr-5381.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/watch/TransactionUpdate.java
  lock-api/src/main/java/com/palantir/lock/client/BatchingCommitTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientCommitTimestampGetter.java
  lock-api/src/test/java/com/palantir/lock/client/BatchingCommitTimestampGetterTest.java
Labels: merge when ready

#5395 [LW] CodeGen for caching and register watches
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/AbstractDefinition.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schema.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemaTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
Labels: no changelog

#5401 Remove repo info from everywhere
  atlasdb-autobatch/build.gradle
  atlasdb-client/build.gradle
  atlasdb-coordination-impl/build.gradle
  atlasdb-impl-shared/build.gradle
  atlasdb-persistent-lock-api/build.gradle
  atlasdb-processors-tests/build.gradle
  atlasdb-processors/build.gradle
  commons-executors-api/build.gradle
  commons-executors/build.gradle
  leader-election-api/build.gradle
  lock-api-objects/build.gradle
  lock-api/build.gradle
  lock-conjure-api/build.gradle
Labels: merge when ready, no changelog

#5403 [LW] Bound Cache by size
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImplTest.java
  changelog/@unreleased/pr-5403.v2.yml
Labels: merge when ready

#5396 [PDS-146088] Time out when borrowing objects from the Cassandra object pool
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolHostLevelMetric.java
  atlasdb-cassandra/src/main/java/org/apache/commons/pool2/impl/ExposedEvictionTimer.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-commons/src/main/java/com/palantir/util/SafeShutdownRunner.java
  atlasdb-commons/src/main/java/com/palantir/util/TimedRunner.java
  atlasdb-commons/src/test/java/com/palantir/util/SafeShutdownRunnerTest.java
  atlasdb-commons/src/test/java/com/palantir/util/TimedRunnerTest.java
  changelog/@unreleased/pr-5396.v2.yml
Labels: autorelease, merge when ready

#5405 [LW] Validate reads from the cache
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtils.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
  changelog/@unreleased/pr-5405.v2.yml
Labels: merge when ready

#5408 [LW] Rewire Transaction Caches
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueCacheImplTest.java
  changelog/@unreleased/pr-5408.v2.yml
Labels: merge when ready

#5410 Exclusion Hunter I: Almost Javadoc
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/api/AtlasDbImmutableTable.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/api/RangeToken.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticLightResultRowImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosUseCase.java
Labels: merge when ready, no changelog

#5409 [LW] Pair the caches together
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/LockWatchCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpLockWatchValueScopingCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  changelog/@unreleased/pr-5409.v2.yml
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCache.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchValueCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchValueCache.java
Labels: merge when ready

#5415 Reduce flakes on TargetedSweepEteTest
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/StreamTestUtils.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/TargetedSweepEteTest.java
Labels: no changelog
