Repository palantir/atlasdb, pull requests merged in 2021-01, with the labels that each got.

#5174 [PDS-146088] Additional logging around Cassandra client pool issues
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  changelog/@unreleased/pr-5174.v2.yml
Labels: autorelease

#5131 Clock went backwards corruption check
  changelog/@unreleased/pr-5131.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionCheckViolation.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifier.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/sqlite/SqlitePaxosStateLogHistory.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifierTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionDetectionHelper.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionTestSetup.java
Labels: autorelease, merge when ready, pr: needs review

#5181 Revert "Clock went backwards corruption check (#5131)"
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionCheckViolation.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifier.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/sqlite/SqlitePaxosStateLogHistory.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifierTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionDetectionHelper.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionTestSetup.java
Labels: autorelease, no changelog

#5180 [LW] Unify the NoOpLockWatchManager and its underlying cache
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/@unreleased/pr-5180.v2.yml
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
Labels: autorelease, merge when ready

#5183 Introducing CLOCK_WENT_BACKWARDS corruption violation
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/CorruptionCheckViolation.java
Labels: autorelease, merge when ready, no changelog

#5178 [LE] Add logging to debug metrics + fix bug
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
Labels: autorelease, no changelog

#5182 Revert revert 5131
  changelog/@unreleased/pr-5182.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalCorruptionDetector.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifier.java
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/sqlite/SqlitePaxosStateLogHistory.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifierTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionDetectionHelper.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionTestSetup.java
Labels: autorelease, merge when ready

#5099 [TS] Allow configuration of lower batch size
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsSerializableTransactionTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepBatchAccumulator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepDelay.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueReader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueUtils.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ScalingSweepTaskSchedulerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepBatchAccumulatorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepDelayTest.java
  changelog/@unreleased/pr-5099.v2.yml
Labels: autorelease, merge when ready

#5154 Make TransactionLockAcquisitionTimeoutException retryable
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionLockAcquisitionTimeoutException.java
  changelog/@unreleased/pr-5154.v2.yml
Labels: autorelease, merge when ready

#5195 Log the persistence mode of Timelock on startup
  changelog/@unreleased/pr-5195.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: merge when ready

#5197 [Cross Client Batching] Autobatchers support configurable wait strats
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/Autobatchers.java
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
  changelog/@unreleased/pr-5197.v2.yml
Labels: autorelease

#5225 [Fix develop] Fix a potential deadlock in SweepQueueReader
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsSerializableTransactionTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueReader.java
  changelog/@unreleased/pr-5225.v2.yml
Labels: merge when ready

#5228 update ojdbc driver to 21.1.0.0
  changelog/@unreleased/pr-5228.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5229 Suppress deprecation warnings in generated code
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/AllValueTypesTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/HashComponentsTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestV2Table.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableClassRendererV2.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableRenderer.java
  changelog/@unreleased/pr-5229.v2.yml
Labels: autorelease
