Repository palantir/atlasdb, pull requests merged in 2021-02, with the labels that each got.

#5230 Leader Election service isn't null
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
Labels: autorelease, merge when ready, no changelog

#5224 Avoid creating thousands of get-ranges threads
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionManager.java
  changelog/@unreleased/pr-5224.v2.yml
Labels: autorelease, merge when ready

#5231 [PDS-158510] Improved Detection of Orphaned Sentinels
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-5231.v2.yml
Labels: autorelease, merge when ready

#5232 Clean naked sentinels in thoroughly swept tables
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/MultiTableSweepQueueWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitioner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-5232.v2.yml
Labels: autorelease

#5236 Add the getRowKeysInRange method to the KVS interface
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DualWriteKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableRemappingKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableSplittingKeyValueService.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcKeyValueService.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemoryTransactionTest.java
  changelog/@unreleased/pr-5236.v2.yml
Labels: autorelease, merge when ready

#5240 [PDS-156719] | LeaderConfig bug fix
  atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java
  changelog/@unreleased/pr-5240.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease

#5244 More logging for Object pools
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
Labels: autorelease, merge when ready, no changelog

#5243 [TS] Calculate exact TS lag and allow configuring per shard lag metrics
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-commons/src/main/java/com/palantir/util/AggregatingVersionedMetric.java
  atlasdb-commons/src/main/java/com/palantir/util/AggregatingVersionedSupplier.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/KeyValueServicePuncherStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/MillisAndMaybeTimestamp.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/cleaner/KeyValueServicePuncherStoreTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepMetricsAssert.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepableCellsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  changelog/@unreleased/pr-5243.v2.yml
Labels: autorelease, merge when ready

#5245 [WIP] Circle speedup
  .circleci/config.yml
  changelog/@unreleased/pr-5245.v2.yml
  scripts/circle-ci/run-circle-tests.sh
  timelock-server/build.gradle
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerStressTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/DbTimeLockSingleLeaderPaxosStressTests.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/MultiLeaderPaxosStressTests.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/SingleLeaderPaxosStressTests.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease, merge when ready

#5251 Docs, docs everywhere
  docs/source/cluster_management/kvs-migration.rst
Labels: merge when ready

#5247 [PDS-146088] Log and metrics for a few more edge cases
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolHostLevelMetric.java
  atlasdb-cassandra/src/main/java/org/apache/commons/pool2/impl/ExposedEvictionTimer.java
  changelog/@unreleased/pr-5247.v2.yml
Labels: autorelease, merge when ready

#5252 Disable local host weighting after failing 5 times
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/Ec2HostLocationSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/ExceptionHandlingSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/ExceptionHandlingSupplierTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostLocationSupplierTest.java
  changelog/@unreleased/pr-5252.v2.yml
Labels: autorelease, merge when ready

#5255 [PDS-146088] Stop! Hammer (the client factory) Time
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-commons/src/main/java/com/palantir/util/SafeShutdownRunner.java
  atlasdb-commons/src/test/java/com/palantir/util/SafeShutdownRunnerTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-5255.v2.yml
Labels: autorelease, merge when ready

#5217 [Cross Client Batching] | AwaitingLeadershipProxy Breakdown
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/benchmarks/AwaitingLeadershipProxyBenchmark.java
  changelog/0.294.1-rc1/pr-5217.v2.yml
  changelog/@unreleased/pr-5217.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipCoordinator.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipCoordinatorFactory.java
Labels: :white_check_mark: Prod validated, autorelease, merge when ready

#5262 TL product dependency bump
  lock-api-objects/build.gradle
Labels: autorelease, merge when ready, no changelog

#5265 [TS] Metrics logging for debugging
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/KeyValueServicePuncherStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
Labels: autorelease, merge when ready, no changelog

#5268 ALP Hotfix
  changelog/@unreleased/pr-5268.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
Labels: autorelease, merge when ready

#5269 [pds-164019] expose isNewServiceNode() properly for user health checks
  changelog/@unreleased/pr-5269.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
Labels: autorelease, merge when ready

#5264 [CCB] | Multi-client startTransactions endpoint
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease, no changelog

#5273 I know what I am doing
  timelock-agent/src/main/java/com/palantir/timelock/config/PaxosInstallConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockInstallConfiguration.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
Labels: autorelease, merge when ready, no changelog

#5271 [CCB] | MultiClientTransactionStarter refactor - part 1
  lock-api/src/main/java/com/palantir/lock/client/BatchingIdentifiedAtlasDbTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/IdentifiedAtlasDbTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarterHelper.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
Labels: no changelog

#5274 [TS] Better shard balancing
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CellReference.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/AbstractSweepQueueTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ShardProgressTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepableCellsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitionerTest.java
  changelog/@unreleased/pr-5274.v2.yml
Labels: autorelease, merge when ready

#5272 Allow configuring Cassandra servers in runtime configuration
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/AtlasDbFactory.java
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraServersConfigs.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ForwardingCassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactoryTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfigTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplier.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AutoServiceAnnotatedAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplierTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactoryTest.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/ServicesConfig.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/DbTimestampStoreInvalidatorCreationTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/RelationalDbTimeLockFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactoryTest.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcAtlasDbFactory.java
  changelog/@unreleased/pr-5272.v2.yml
Labels: autorelease, merge when ready

#5261 [Cross Client Batching?] Liveness Checkers for Jepsen
  atlasdb-jepsen-tests/src/jepsen/atlasdb/timestamp.clj
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/JepsenHistoryCheckers.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/NemesisResilienceChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/Event.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/EventVisitor.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/FailEvent.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/InfoEvent.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/InvokeEvent.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/OkEvent.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/events/RequestType.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/lock/IsolatedProcessCorrectnessChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/lock/LockAcquisitionLivenessChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/lock/LockCorrectnessChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/lock/RefreshCorrectnessChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/timestamp/MonotonicChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/timestamp/NonOverlappingReadsMonotonicChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/timestamp/TimestampLivenessChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/timestamp/UniquenessChecker.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/jepsen/utils/LivenessChecker.java
  atlasdb-jepsen-tests/src/test/java/com/palantir/atlasdb/jepsen/lock/LockAcquisitionLivenessCheckerTest.java
  atlasdb-jepsen-tests/src/test/java/com/palantir/atlasdb/jepsen/timestamp/TimestampLivenessCheckerTest.java
  atlasdb-jepsen-tests/src/test/java/com/palantir/atlasdb/jepsen/timestamp/UniquenessCheckerTest.java
  changelog/@unreleased/pr-5261.v2.yml
Labels: merge when ready

#5276 [TS] Hashes, now even better
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CellReference.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CellReferenceTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfo.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/AbstractSweepQueueTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitionerTest.java
Labels: autorelease, no changelog

#5021 [LW] Compress snapshots returned to the user
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/LockWatchEteTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEvents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionBounds.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStoreTest.java
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/getEventsForTransactionsMaxCondensing/event-cache-1.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/getEventsForTransactionsNoCondensing/event-cache-1.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/getEventsForTransactionsSomeCondensing/event-cache-1.json
  atlasdb-impl-shared/src/test/resources/lockwatch-event-cache-output/getEventsForTransactionsSomeCondensing/event-cache-2.json
  changelog/@unreleased/pr-5021.v2.yml
Labels: autorelease, long-lived, merge when ready
