Repository palantir/atlasdb, pull requests merged in 2022-01, with the labels that each got.

#5828 don't spam gc logging
  .circleci/config.yml
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog, merge when ready

#5821 Handle null ConflictDetectionManagers + fix ancient ConflictDetectionManagers bug
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  changelog/@unreleased/pr-5821.v2.yml
Labels: autorelease, merge when ready

#5833 Check if people are still using non-Conjure clients to talk to AtlasDB
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/ProtocolAwareExceptionMapper.java
Labels: no changelog, autorelease, merge when ready

#5840 Change retry of TSI to 3 days
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/TransactionSchemaInstaller.java
  changelog/@unreleased/pr-5840.v2.yml
Labels: autorelease, merge when ready

#5836 ABR7: CqlSession and CqlMetadata
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/ClusterMetadataUtils.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlCluster.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlMetadata.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlSession.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions1TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions2TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/TransactionsTableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/LightweightOppToken.java
  atlasdb-cassandra/src/test/java/com/datastax/driver/core/CassandraTokenRanges.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/ClusterMetadataUtilsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/CqlMetadataTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions1TableInteractionTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions2TableInteractionTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteractionTest.java
  atlasdb-ete-tests/build.gradle
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
Labels: no changelog, merge when ready

#5841 ABR8: Pull out session-scoped classes
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraServersConfigs.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlCluster.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/RepairRangeFetcher.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcher.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/ClusterFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
Labels: no changelog, merge when ready

#5812 [LW] Improve performance for long running transactions
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImplTest.java
  changelog/@unreleased/pr-5812.v2.yml
Labels: autorelease, merge when ready

#5829 [Exclusion Hunter] Part 23: Too Many Arguments
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/IndexMetadata.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultLockAndTimestampServiceFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  build.gradle
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: no changelog

#5843 Use singleton for default table factory
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableFactoryRenderer.java
  changelog/@unreleased/pr-5843.v2.yml
Labels: autorelease, merge when ready

#5728 [contentious] Remove unused legacy k8s support
  timelock-agent/src/main/java/com/palantir/timelock/config/ClusterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/KubernetesClusterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/utils/KubernetesHostnames.java
  timelock-agent/src/test/java/com/palantir/timelock/config/ClusterConfigurationDeserializationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/utils/KubernetesHostnamesTest.java
  timelock-agent/src/test/resources/cluster-configuration-kubernetes.yml
Labels: no changelog, merge when ready

#5754 Exclusion Hunter XIV: InflineFormatString
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/queries/GetQuerySpec.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ranges/DbKvsGetRanges.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQLUtils.java
Labels: no changelog

#5826 [Transactions3] A Delightful/Disastrous/Documentary Reading
  docs/source/conf.py
  docs/source/miscellaneous/doc/adr/0017-transactions3.md
  docs/source/miscellaneous/doc/adr/index.rst
Labels: no changelog

#5820 Exclusion Hunter XV: PreconditionsConstantMessage
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcAtlasDbFactory.java
  build.gradle
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/logging/NonBlockingFileAppenderFactory.java
Labels: no changelog, merge when ready

#5847 [Transactions3/ABR] Need to abort at the put timestamp or higher
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteraction.java
  changelog/@unreleased/pr-5847.v2.yml
Labels: autorelease, merge when ready

#5842 ABR9: CleanTransactionsTablesTask
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasRestoreService.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/AtlasRestoreServiceTest.java
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlCluster.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlSession.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TransactionAborter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions1TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions2TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/TransactionsTableInteraction.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/TransactionAborterTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/transaction/TransactionsTableInteractionTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
Labels: no changelog, merge when ready

#5848 Configurable GzipCompressingInputStream compression buffer size
  atlasdb-commons/src/main/java/com/palantir/common/compression/GzipCompressingInputStream.java
  atlasdb-commons/src/main/java/com/palantir/common/compression/StreamCompression.java
  atlasdb-commons/src/test/java/com/palantir/common/compression/StreamCompressionTests.java
  changelog/@unreleased/pr-5848.v2.yml
Labels: autorelease, merge when ready

#5849 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no changelog, merge when ready

#5846 ABR 10a: Unit tests for RangeFetcher classes
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/ClusterMetadataUtils.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlMetadata.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/BackupTestUtils.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/ClusterMetadataUtilsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/RepairRangeFetcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcherTest.java
Labels: no changelog, autorelease, merge when ready

#5845 [Exclusion Hunter] Part 24: Mixed Mutability Return Types
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTableMetadata.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TaskRunner.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/ColumnMetadataDescription.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/RowsColumnRangeBatchRequests.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleOverflowValueLoader.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcKeyValueService.java
  build.gradle
  commons-executors-api/src/main/java/com/palantir/common/concurrent/ExecutorInheritableThreadLocal.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogImpl.java
Labels: no changelog

#5852 Make LockWatchCachingConfig serialisable
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/LockWatchCachingConfig.java
  changelog/@unreleased/pr-5852.v2.yml
Labels: autorelease, merge when ready

#5853 [Transactions3/ABR] Hard delete things to be aborted in Transactions3
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteraction.java
  changelog/@unreleased/pr-5853.v2.yml
Labels: autorelease, merge when ready

#5854 Get the retry policies right
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteraction.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/transaction/TransactionsTableInteraction.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/RepairRangeFetcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/transaction/Transactions3TableInteractionTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
Labels: no changelog, autorelease, merge when ready

#5861 [LW] Add some more logging
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/ResilientLockWatchProxy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  changelog/@unreleased/pr-5861.v2.yml
Labels: autorelease, merge when ready

#5865 Full Circle: Reading the host location is now asynchronous
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/AsyncSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/AsyncSupplierTests.java
  changelog/@unreleased/pr-5865.v2.yml
Labels: autorelease, merge when ready

#5868 Upgrade AssertJ to 3.22.0
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#5867 [LW] Fix Validation for getRows
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/util/ByteArrayUtilities.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/util/ByteArrayUtilitiesTests.java
  changelog/@unreleased/pr-5867.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: autorelease, merge when ready

#5869 Log number of lock descriptors
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-5869.v2.yml
Labels: autorelease, merge when ready

#5866 ABR 11: DisabledNamespaces
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimelockNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DisabledNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DisabledNamespacesUpdaterResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/TimelockNamespacesTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/DisabledNamespacesTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/DiskNamespaceLoaderTest.java
Labels: no changelog, merge when ready

#5855 Use ArrayListMultimap when values are ColumnValue
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/AllValueTypesTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/ApiTestTableFactory.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/HashComponentsTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestTable.java
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/SchemaApiTestV2Table.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/Renderers.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableClassRendererV2.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableFactoryRenderer.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableRenderer.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemaTest.java
Labels: no changelog, merge when ready

#5830 Remove remoting2 dependency
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/BlockingTimeoutExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/ExceptionMappers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotCurrentLeaderExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/NotInitializedExceptionMapper.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/ProtocolAwareExceptionMapper.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/ExceptionMappersSerializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/ExceptionMappersTest.java
  atlasdb-config/src/test/resources/fixtures/service-unavailable-exception.json
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TooManyRequestsExceptionMapper.java
  timelock-server/build.gradle
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#5872 Remove PDS-146088 magic
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  changelog/@unreleased/pr-5872.v2.yml
Labels: autorelease, merge when ready

#5874 Remove replication factor specified check
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifierTest.java
  changelog/@unreleased/pr-5874.v2.yml
Labels: autorelease, merge when ready

#5871 [LW] Rely on locally written values instead of the cache
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionCacheValueStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionCacheValueStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionCacheValueStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImplTest.java
  changelog/@unreleased/pr-5871.v2.yml
Labels: autorelease, merge when ready

#5877 Tasks which rename threads avoid updating the OS thread
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AnnotatedCallable.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AnnotatedRunnable.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  changelog/@unreleased/pr-5877.v2.yml
  commons-api/src/main/java/com/palantir/common/concurrent/ThreadNamingCallable.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQLUtils.java
  commons-executors/src/main/java/com/palantir/common/concurrent/AtlasRenamingExecutorService.java
  commons-executors/src/main/java/com/palantir/common/concurrent/ThreadNames.java
  commons-executors/src/test/java/com/palantir/common/concurrent/ThreadNamesTest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
Labels: autorelease, merge when ready

#5879 Fix Hyperlink in ThreadNames Javadoc
  commons-executors/src/main/java/com/palantir/common/concurrent/ThreadNames.java
Labels: no changelog, merge when ready

#5882 Fix race condition causing 'pool not open' errors
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-5882.v2.yml
Labels: autorelease, merge when ready

#5875 [Exclusion Hunter] Part 25 and 26: ReturnValueIgnored and ReadReturnedValueIgnored
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/TwoNodesDownGetTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/stream/BlockConsumingInputStreamTest.java
  atlasdb-commons/src/main/java/com/palantir/util/crypto/Sha256Hash.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CoalescingSupplierTest.java
  atlasdb-commons/src/test/java/com/palantir/util/CachedComposedSupplierTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQLUtils.java
Labels: no changelog
