Repository palantir/atlasdb, pull requests merged in 2022-03, with the labels that each got.

#5930 [AtlasDB Proxy & DbKVS] Part 1: Long Identifier Support in Oracle
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleIdentifierLengthLimitOptions.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleIdentifierLengthLimits.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfigTest.java
  changelog/@unreleased/pr-5930.v2.yml
Labels: autorelease, merge when ready

#5931 Gradle 7.4
  atlasdb-backup/build.gradle
  atlasdb-cassandra/build.gradle
  atlasdb-client/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-perf/build.gradle
  build.gradle
  gradle/publish-jars.gradle
  lock-impl/build.gradle
  timelock-server/build.gradle
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#5933 Streamline SQL BLOB cleanup
  changelog/@unreleased/pr-5933.v2.yml
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java
Labels: autorelease, merge when ready

#5939 encrypted-config-value 4.0.0
  changelog/@unreleased/pr-5939.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#5934 Reduce tolerance of bad Cassandra hosts
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServices.java
  changelog/0.561.0-rc1/pr-5924.v2.yml
  changelog/@unreleased/pr-5934.v2.yml
Labels: autorelease, merge when ready

#5941 [AtlasDB Proxy & DbKVS] Part 6: Deserialisable Internal Configs
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/LocalConnectionConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/SharedResourcesConfig.java
  changelog/@unreleased/pr-5941.v2.yml
Labels: autorelease, merge when ready

#5940 Fix NPE caused by txn commit race condition
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTableTest.java
  changelog/@unreleased/pr-5940.v2.yml
Labels: autorelease, merge when ready

#5943 Add metrics to Cassandra reads and writes
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/InstrumentedTSocket.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TSocketFactory.java
  changelog/@unreleased/pr-5943.v2.yml
Labels: autorelease, merge when ready

#5950 Upgrade the AtlasDB Base Docker Image
  .circleci/config.yml
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleTestSuite.java
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
Labels: no changelog, merge when ready

#5946 Remove Absent hosts from consideration
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraAbsentHostTracker.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraPoolReaper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraAbsentHostTrackerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraPoolReaperTest.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainer.java
  changelog/@unreleased/pr-5946.v2.yml
Labels: autorelease, merge when ready

#5954 Optimize a few hot code paths
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  changelog/@unreleased/pr-5954.v2.yml
Labels: autorelease, merge when ready

#5956 Support Intellij Gradle integration
  atlasdb-client/build.gradle
Labels: no changelog, merge when ready

#5958 Trim log line
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog, merge when ready

#5957 Bump version of Postgres to 42.3.3
  changelog/@unreleased/pr-5957.v2.yml
  gradle/versions.gradle
  versions.lock
Labels: do not merge

#5942 [AtlasDB Proxy & DbKVS] Part 7: Allow Namespace Overrides for Oracle Connection Config
  atlasdb-dbkvs-hikari/src/test/java/com/palantir/nexus/db/pool/config/OracleConnectionConfigTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceConfig.java
  atlasdb-ete-tests/docker/conf/atlasdb-ete.timelock.dbkvs.yml
  changelog/@unreleased/pr-5942.v2.yml
  docs/source/configuration/key_value_service_configs/db_key_value_services_config.rst
  docs/source/configuration/key_value_service_configs/index.rst
  docs/source/configuration/key_value_service_configs/oracle_key_value_service_config.rst
  docs/source/configuration/key_value_service_configs/postgres_key_value_service_config.rst
Labels: autorelease, merge when ready

#5963 use unique pool names
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  changelog/@unreleased/pr-5963.v2.yml
Labels: merge when ready

#5964 [Alta DbKVS] Part 8: Serialization of Oracle Config Change
  atlasdb-dbkvs/build.gradle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleIdentifierLengthLimits.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfigTest.java
  changelog/@unreleased/pr-5964.v2.yml
Labels: autorelease, merge when ready

#5972 Fix tokenRangesToHost emitted log line by swapping host and range in formatted string
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
Labels: no changelog, merge when ready

#5975 Reduce CassandraLogHelper.host(InetSocketAddress) memory allocations
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelperTest.java
  changelog/@unreleased/pr-5975.v2.yml
Labels: component: performance, autorelease, merge when ready

#5980 Simulate shuffling token range endpoints
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TokenRangeResolution.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TokenRangeResolutionTest.java
Labels: merge when ready

#5969 [PDS-253270] Treat matching tokens and number of hosts across token ranges as sufficient for consistency
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TokenRangeResolution.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TokenRangeResolutionTest.java
  changelog/@unreleased/pr-5969.v2.yml
Labels: autorelease, merge when ready

#5983 Don't load metadata on conflicts
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/Cells.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/KeyValueServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-5983.v2.yml
Labels: autorelease, merge when ready

#5971 Cass client pool refactor
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/Blacklist.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraAbsentHostTracker.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPool.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellDeleter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoadingBatcher.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellRangeDeleter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellValuePutter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutorImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/HostPartitioner.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RetryableCassandraRequest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/paging/RowGetter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetrics.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/HostnamesByIpSupplier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/WeightedServers.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/BlacklistTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraAbsentHostTrackerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoadingBatcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/RetryableCassandraRequestTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/WeightedServersTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
  changelog/0.580.0/pr-5971.v2.yml
  changelog/0.581.0-rc1/pr-5971.v2.yml
  changelog/0.581.0-rc2/pr-5971.v2.yml
  changelog/0.581.0-rc3/pr-5967.v2.yml
  changelog/0.581.0-rc3/pr-5969.v2.yml
  changelog/0.581.0-rc3/pr-5971.v2.yml
  changelog/0.581.0-rc3/pr-5975.v2.yml
  changelog/0.581.0-rc4/pr-5971.v2.yml
  changelog/0.581.0-rc6/pr-5971.v2.yml
  changelog/0.581.0-rc8/pr-5971.v2.yml
  changelog/@unreleased/pr-5971.v2.yml
Labels: autorelease, merge when ready, :white_check_mark: Prod validated

#5985 Add telemetry around client destruction in the Cassandra client poolls
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolHostLevelMetric.java
  changelog/@unreleased/pr-5985.v2.yml
Labels: autorelease, merge when ready
