Repository palantir/atlasdb, pull requests merged in 2022-11, with the labels that each got.

#6343 Fix logging level of lock watch events
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
Labels: no changelog, autorelease, merge when ready

#6298 Add cluster topology check
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/HostIdResult.java
  atlasdb-cassandra/src/main/metrics/atlasdb-cassandra-metrics.yml
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/HostIdResultTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6346 Fix ConcurrentModificationException in ResilientCommitTimestampAtomicTableIntegrationTest
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTableIntegrationTest.java
Labels: flaky test, no changelog, merge when ready

#6349 Bump docker-proxy-rule to latest
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6341 Test connection sets fetch size to one
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  changelog/@unreleased/pr-6341.v2.yml
Labels: merge when ready

#6323 Avoid NPE in CassandraClientPoolImpl.cleanUpOnInitFailure
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  commons-executors/src/main/java/com/palantir/common/concurrent/InitializeableScheduledExecutorServiceSupplier.java
  commons-executors/src/main/java/com/palantir/common/concurrent/ScheduledExecutorServiceFactory.java
  commons-executors/src/test/java/com/palantir/common/concurrent/InitializeableScheduledExecutorServiceSupplierTest.java
Labels: no changelog, merge when ready

#6317 Remove token range checks, validate new servers on their topology
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TokenRangeResolution.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TokenRangeResolutionTest.java
  changelog/@unreleased/pr-6317.v2.yml
Labels: autorelease, merge when ready

#6350 Use DefaultHostnameVerifier
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#6348 LockDescriptor is @unsafe
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/RowLockDescriptorMapping.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshotState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogState.java
  lock-api-objects/src/main/java/com/palantir/lock/LockDescriptor.java
  lock-api-objects/src/main/java/com/palantir/lock/LockResponse.java
  lock-api-objects/src/main/java/com/palantir/lock/LockWithClient.java
  lock-api-objects/src/main/java/com/palantir/lock/LockWithMode.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/LockRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/WaitForLocksRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/CommitUpdate.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockEvent.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchCreatedEvent.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockWatchStateUpdate.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/UnlockEvent.java
  lock-api/src/main/java/com/palantir/lock/client/IdentifiedLockRequest.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceStateDebugger.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockEvents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
Labels: no changelog, merge when ready

#6351 [LW] Rate limited log + metric
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbMetricNames.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
Labels: no changelog, autorelease, merge when ready

#6352 RLLW3 (post-credits scene): Bump timelock dependency
  changelog/@unreleased/pr-6352.v2.yml
  lock-api-objects/build.gradle
Labels: component: timelock, autorelease, merge when ready

#6356 Fix dependency for jepsen tests
  atlasdb-jepsen-tests/build.gradle
Labels: no changelog, merge when ready

#6332 [TEX] Part 1b: TrackingKeyValueService: utilities for byte size (1)
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CandidateCellForSweeping.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Cell.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RowResult.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TableReference.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Value.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/Measurable.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CandidateCellForSweepingTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CellTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/TableReferenceTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/ValueTest.java
  changelog/@unreleased/pr-6332.v2.yml
Labels: autorelease, merge when ready

#6334 [TEX] Part 1c: TrackingKeyValueService: utilities for byte size (2)
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/util/MeasuringUtils.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/util/MeasuringUtilsTest.java
  changelog/@unreleased/pr-6334.v2.yml
Labels: autorelease, merge when ready

#6344 Oracle DbKvs allow for tables to be altered to match their metadata
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleTestSuite.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleAlterTableIntegrationTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleNamespaceDeleterTests.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleErrorConstants.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/cleaner/DbKvsNamespaceDeleterFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/OracleDbTableFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableValueStyleCache.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableValueStyleCacheImpl.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleCellTsPageLoader.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleGetRange.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableValueStyleCacheImplTest.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTableTest.java
  changelog/@unreleased/pr-6344.v2.yml
Labels: merge when ready

#6336 [TEX] Part 3: TrackingKeyValueService: tracking iterator utils
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingClosableIterator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingIterator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingRowColumnRangeIterator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingClosableIteratorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingIteratorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingRowColumnRangeIteratorTest.java
  changelog/@unreleased/pr-6336.v2.yml
Labels: autorelease, merge when ready

#6362 Fix typo in SQLString.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java
Labels: no changelog, merge when ready

#6335 [TEX] Part 2: TrackingKeyValueService: KeyValueServiceDataTracker
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/KvsCallReadInfo.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/TransactionReadInfo.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/expectations/ExpectationsApiTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/BytesReadTracker.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/KeyValueServiceDataTracker.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/KeyValueServiceDataTrackerTest.java
Labels: no changelog, merge when ready

#6368 Optimize VersionedEventStore retentionEventsInternal
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  changelog/@unreleased/pr-6368.v2.yml
Labels: merge when ready

#6369 SerializableTransaction#isSerializableTable avoids Optional allocations
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  changelog/@unreleased/pr-6369.v2.yml
Labels: merge when ready

#6307 TTS | Validation mode base
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/metrics/transactions4-knowledge.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTableTest.java
  changelog/@unreleased/pr-6307.v2.yml
Labels: merge when ready

#6371 Add rev api for api/cassandra
  atlasdb-api/build.gradle
  atlasdb-cassandra/build.gradle
  build.gradle
Labels: no changelog, merge when ready

#6327 [TTS] Ete tests
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/InstrumentedConsensusForgettingStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/encoding/V4ProgressEncodingStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/mcas/MarkAndCasConsensusForgettingStoreTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/service/TransactionServicesTest.java
  changelog/@unreleased/pr-6327.v2.yml
Labels: autorelease, merge when ready

#6374 [TEX] Part 6: Temporarily removing TEX code
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/ExpectationsAwareTransaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/ExpectationsConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/ExpectationsStatistics.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/expectations/ExpectationsApiTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsAwareTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsTask.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsViolation.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsManagerTest.java
Labels: no changelog, merge when ready

#6337 [TEX] Part 4: TrackingKeyValueService: putting it all together
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingKeyValueServiceImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingKeyValueServiceForwardingTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingKeyValueServiceReadInfoTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingKeyValueServiceTestUtils.java
Labels: no changelog, merge when ready

#6380 Fix supplement for CoordinationAwareKnownConcludedTransactionsStore
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/coordinated/CoordinationAwareKnownConcludedTransactionsStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/coordinated/CoordinationAwareKnownConcludedTransactionsStoreTest.java
  changelog/@unreleased/pr-6380.v2.yml
Labels: merge when ready

#6381 [TEX] TableReference#stringSizeInBytes fix
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TableReference.java
Labels: no changelog, merge when ready

#6223 Prefer safe logging preconditions in more places
  .gitattributes
  atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/ColumnRangeSelection.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TableReference.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestSingleBackendCommand.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/StreamStoreRenderer.java
  atlasdb-commons/src/main/java/com/palantir/util/OptionalResolver.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/CallChainTest.java
  atlasdb-commons/src/test/java/com/palantir/common/base/BatchingVisitablesTest.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CoalescingSupplierTest.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataStreamStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/monitoring/TimestampTrackerTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsStreamStore.java
  changelog/@unreleased/pr-6223.v2.yml
  commons-executors/src/test/java/com/palantir/common/concurrent/ExecutorInheritableThreadLocalTest.java
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosStreamStore.java
Labels: merge when ready

#6384 Make more noise if there is an illegal state
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/TimestampExtractingAtomicTable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/TimestampExtractingAtomicTableTest.java
  changelog/@unreleased/pr-6384.v2.yml
Labels: autorelease, merge when ready

#6378 [PDS-306496] | Add max event config
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/LockWatchCachingConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  changelog/0.771.0-rc1/pr-6378.v2.yml
  changelog/0.771.0-rc2/pr-6378.v2.yml
  changelog/@unreleased/pr-6378.v2.yml
Labels: no changelog, autorelease, merge when ready

#6379 Add minimum timestamp to TimestampRange
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/ConcludedRangeState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactions.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/TimestampRangeSet.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/coordinated/CoordinationAwareKnownConcludedTransactionsStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/ConcludedRangeStateTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsStoreConcurrencyTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsStoreTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/TimestampRangeSetTest.java
  changelog/@unreleased/pr-6379.v2.yml
Labels: merge when ready
