Repository palantir/atlasdb, pull requests merged in 2022-05, with the labels that each got.

#6013 ABR25: Copy over internal tests
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/CoordinationServiceUtilitiesTest.java
Labels: no changelog, merge when ready

#6019 Style: AbstractTransactionTest
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
Labels: no changelog, merge when ready

#6022 [PDS-265137 -> Develop] Accept Staging Reads on Version Three
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/InternalSchemaConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTableTest.java
  changelog/@unreleased/pr-6022.v2.yml
Labels: autorelease, merge when ready

#6021 Latest gradle-baseline
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/thrift/ThriftQueryWeighers.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/DistributionOutlierControllerTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/SweepStatsKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/sweep/queue/id/SweepTableIdentifier.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schema.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowMetricsInvocationHandler.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TaggedMetricsInvocationEventHandler.java
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/SerializingUtils.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunner.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableMetadataCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/WriteBatchingTransactionService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/pue/CassandraImitatingConsensusForgettingStore.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/impl/TableMetadataCache.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweeperServiceImplIntegrationTest.java
  build.gradle
  commons-api/src/main/java/com/palantir/util/jmx/AbstractOperationStats.java
  commons-db/src/main/java/com/palantir/nexus/db/pool/CloseTracking.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/AgnosticResultRowImpl.java
  commons-db/src/main/java/com/palantir/nexus/db/sql/BasicSQL.java
  gradle/versions.gradle
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarterHelper.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClientsTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/FeedbackAnalysisTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/adjudicate/PointHealthReportAnalysisTest.java
Labels: no changelog, merge when ready

#6024 Fix: Don't run scrub, even once, if scrub is disabled
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/Scrubber.java
  changelog/@unreleased/pr-6024.v2.yml
Labels: autorelease, merge when ready

#6020 DbKvs Timelock: support async initialization
  atlasdb-api/src/main/java/com/palantir/atlasdb/timestamp/DbTimeLockFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/memory/InMemoryDbTimeLockFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/RelationalDbTimeLockFactory.java
  timelock-agent/src/main/java/com/palantir/timelock/ServiceDiscoveringDatabaseTimeLockSupplier.java
  timelock-agent/src/main/java/com/palantir/timelock/config/DatabaseTsBoundPersisterConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/test/java/com/palantir/timelock/ServiceDiscoveringDatabaseTimeLockSupplierTest.java
  timelock-server-distribution/var/conf/timelock-postgres.yml
Labels: no changelog, merge when ready

#6030 PDS-266092 | Log txn time for aborts
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog, autorelease, merge when ready

#6033 [Runtime config] Part 2f: Generify reloading container
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ReloadingCloseableContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ReloadingCqlClusterContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/ReloadingCloseableContainerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/ReloadingCqlClusterContainerTest.java
Labels: no changelog, merge when ready

#6038 [LW] Add further telemetry when clearing caches
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-6038.v2.yml
Labels: autorelease, merge when ready

#6041 Downgrade noisy info logs
  changelog/@unreleased/pr-6041.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockAcquirer.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
Labels: autorelease, merge when ready

#6048 [PDS-269760] Reduce max rows scanned by single Timelock Corruption verifier run from 250 -> 10
  changelog/@unreleased/pr-6048.v2.yml
  timelock-corruption-detection/src/main/java/com/palantir/timelock/history/PaxosLogHistoryProgressTracker.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/history/PaxosLogHistoryProviderTest.java
Labels: autorelease, merge when ready

#6034 [Runtime config] Part 2g: Async KVS supports reloading CQL clients
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AsyncKeyValueService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsAsyncFallbackMechanismsTests.java
  atlasdb-cassandra-integration-tests/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ReloadingCloseableContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CassandraAsyncKeyValueService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CassandraAsyncKeyValueServiceFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/DefaultCassandraAsyncKeyValueServiceFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/ThrowingCqlClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/CqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CassandraAsyncKeyValueServiceTests.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CqlClientImplTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/ThrowingCqlClientTest.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainer.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraResource.java
  changelog/@unreleased/pr-6034.v2.yml
Labels: merge when ready

#6042 [Runtime Config] Part 3a: Passing around refreshable runtime config to atlas db factory
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactoryTest.java
  changelog/@unreleased/pr-6042.v2.yml
Labels: merge when ready

#6043 [Runtime Config] Part 3b: Require runtime config for Cass KVS
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraBackgroundSweeperIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceSweepTaskRunnerIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTableCreationIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceTransactionIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsAsyncFallbackMechanismsTests.java
  atlasdb-cassandra-multinode-tests/build.gradle
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/CassandraSchemaLockTest.java
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/NodesDownTestSetup.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-container-test-utils/build.gradle
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainer.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraResource.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ThreeNodeCassandraCluster.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ThreeNodeCassandraResource.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/UninitializedCassandraResource.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/AtlasDbServicesConnector.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/CassandraKeyValueServiceInstrumentation.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/KeyValueServiceInstrumentation.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/PostgresKeyValueServiceInstrumentation.java
  atlasdb-perf/src/test/java/com/palantir/atlasdb/performance/backend/MockKeyValueServiceInstrumentation.java
  changelog/@unreleased/pr-6043.v2.yml
Labels: merge when ready

#6044 [Runtime Config] Part 3c: CCPI refreshable runtime config
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  changelog/@unreleased/pr-6044.v2.yml
Labels: merge when ready

#6045 [Runtime Config] Part 3d: Cass service runtime config refreshable
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
  changelog/@unreleased/pr-6045.v2.yml
Labels: merge when ready

#6046 [Runtime Config] Part 3e: Cass verifier runtime config refreshable
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  changelog/@unreleased/pr-6046.v2.yml
Labels: merge when ready

#6035 Remove unused dependency
  lock-api/build.gradle
Labels: no changelog, merge when ready

#6054 Cassandra CellLoader lazily computes read-only result lists
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoaderTest.java
  changelog/@unreleased/pr-6054.v2.yml
Labels: merge when ready

#6052 fix NPE
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcher.java
  changelog/@unreleased/pr-6052.v2.yml
Labels: autorelease, merge when ready

#6050 [Runtime config] Part 4!: Switch to using runtime config for replication factor and servers!
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKvsAsyncFallbackMechanismsTests.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ForwardingCassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ReloadingCloseableContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ReloadingCloseableContainerImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/Blacklist.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellValuePutter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/CassandraAsyncKeyValueService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/ClusterFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/sweep/CandidateRowsForSweepingIterator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/sweep/GetCandidateRowsForSweeping.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/sweep/GetCellTimestamps.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactoryTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfigsTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraReloadableKeyValueServiceRuntimeConfigTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraReloadableKvsConfigTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/ReloadingCloseableContainerImplTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/BackupTestUtils.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/RepairRangeFetcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/BlacklistTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceConfigTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServicesSchemaConsensusTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandlerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/async/CassandraAsyncKeyValueServiceTests.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  atlasdb-cassandra/src/test/resources/testRuntimeConfig.yml
  atlasdb-config/readme.md
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainer.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ThreeNodeCassandraCluster.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/UninitializedCassandraResource.java
  atlasdb-ete-tests/docker/conf/atlasdb-ete.cassandra-async.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.multiple-cassandra-async.yml
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/CassandraKeyValueServiceInstrumentation.java
  changelog/0.612.0-rc1/pr-6034.v2.yml
  changelog/0.612.0-rc1/pr-6042.v2.yml
  changelog/0.612.0-rc1/pr-6043.v2.yml
  changelog/0.612.0-rc1/pr-6044.v2.yml
  changelog/0.612.0-rc1/pr-6045.v2.yml
  changelog/0.612.0-rc1/pr-6046.v2.yml
  changelog/0.612.0-rc1/pr-6050.v2.yml
  changelog/0.612.0-rc2/pr-6050.v2.yml
  changelog/@unreleased/pr-6050.v2.yml
Labels: autorelease, merge when ready

#6040 BackupService backwards compatibility
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/ExternalBackupPersister.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/ExternalBackupPersisterTest.java
  changelog/0.610.0-rc1/pr-6040.v2.yml
  changelog/@unreleased/pr-6040.v2.yml
Labels: autorelease, merge when ready

#6056 Triggers.getAllTriggers does not allocate when there are no triggers
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/generation/Triggers.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/generation/TriggersTest.java
  changelog/@unreleased/pr-6056.v2.yml
Labels: merge when ready

#6061 add throwable arg to not initialized exception
  atlasdb-commons/src/main/java/com/palantir/exception/NotInitializedException.java
  changelog/@unreleased/pr-6061.v2.yml
Labels: autorelease, merge when ready

#6018 Don't let Hikari treat SQLTimeoutException an evictable
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  changelog/@unreleased/pr-6018.v2.yml
Labels: merge when ready

#6065 CassandraServer memoizes lazily computed hash code
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServer.java
  changelog/@unreleased/pr-6065.v2.yml
Labels: merge when ready

#6066 Change TS shard allocation daily
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CellReference.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfo.java
  changelog/@unreleased/pr-6066.v2.yml
Labels: autorelease, merge when ready

#6063 Add `RefreshableWithInitialValue` to encapsulate CassAtlasDbFactory runtime config reloading behaviour
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/RefreshableWithInitialValue.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/RefreshableWithInitialValueTest.java
  changelog/@unreleased/pr-6063.v2.yml
Labels: merge when ready

#6067 Log the current perceived Timelock config when encountering unknown remote exception
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/UnknownRemoteDebuggingProxy.java
  changelog/@unreleased/pr-6067.v2.yml
Labels: autorelease, merge when ready
