Repository palantir/atlasdb, pull requests merged in 2022-07, with the labels that each got.

#6113 [TTS] Kill redundant Oldest TS ts tracker
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/OldestTargetedSweepTrackedTimestamp.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/OldestTargetedSweepTrackedTimestampTest.java
Labels: no changelog

#6026 [Txn3] Do not spam LWTs on staging values
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraBackedPueTableTest.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/pue/KvsConsensusForgettingStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/metrics/put-unless-exists-table.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTableIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/pue/ResilientCommitTimestampPutUnlessExistsTableTest.java
  changelog/0.618.0-rc1/pr-6026.v2.yml
  changelog/@unreleased/pr-6026.v2.yml
Labels: autorelease, merge when ready

#6088 [TTS] Sweep must process writes done by all txns
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/0.639.0-rc1/pr-6088.v2.yml
  changelog/0.639.0-rc1/pr-6106.v2.yml
  changelog/@unreleased/pr-6088.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchEventIntegrationTest.java
Labels: autorelease, merge when ready

#6105 [TTS] Track last seen commit timestamp by conservative sweep across shards
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepBatch.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepBatchAccumulator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TimestampsToSweep.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ShardProgressTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractTargetedSweepTest.java
  changelog/@unreleased/pr-6105.v2.yml
Labels: autorelease, merge when ready

#6098 Remove H2 dependency
  atlasdb-dbkvs-hikari/build.gradle
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/H2ConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/PostgresConnectionConfig.java
  changelog/@unreleased/pr-6098.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#6119 [TTS] | Wire MCAS | CassandraKvs impl
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/MultiCheckAndSetException.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/MultiCheckAndSetRequest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DualWriteKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableRemappingKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableSplittingKeyValueService.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  changelog/@unreleased/pr-6119.v2.yml
Labels: autorelease, merge when ready

#6122 fix typo in benchmarking.rst
  docs/source/performance/benchmarking.rst
Labels: merge when ready

#6139 Bump Rescue version to one that exists
  atlasdb-cassandra/build.gradle
  changelog/@unreleased/pr-6139.v2.yml
Labels: autorelease, merge when ready

#6137 TransactionStarterHelper avoids Set copies
  changelog/@unreleased/pr-6137.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarterHelper.java
Labels: autorelease, merge when ready

#6136 RowColumnRangeExtractor uses smaller presized IdentityHashMaps
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RowColumnRangeExtractor.java
  changelog/@unreleased/pr-6136.v2.yml
Labels: component: performance, merge when ready

#6127 [TTS] Force enable sweep queue writes
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/ShouldRunBackgroundSweepSupplier.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/ShouldRunBackgroundSweepSupplierTest.java
  atlasdb-ete-tests/docker/conf/atlasdb-ete.multiple-cassandra-async.yml
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepInstallConfig.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-6127.v2.yml
Labels: merge when ready

#6112 [Transaction Table Sweep] Part 2: DefaultKnownConcludedTransactions
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/DefaultKnownConcludedTransactions.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactions.java
  atlasdb-impl-shared/src/main/metrics/transactions4-knowledge.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/DefaultKnownConcludedTransactionsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsStoreConcurrencyTest.java
Labels: no changelog, autorelease, merge when ready

#6126 [Transaction Table Sweep] Part 3: Extract TicketsCellEncodingStrategy From Transactions2
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/encoding/TicketsCellEncodingStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/encoding/TicketsEncodingStrategy.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/encoding/TicketsCellEncodingStrategyTest.java
Labels: no changelog, autorelease, merge when ready

#6138 AbstractKVS.internalTableName avoids expensive regex matcher
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableNameTest.java
  changelog/@unreleased/pr-6138.v2.yml
Labels: component: performance, merge when ready

#6157 Timelock topology metric
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-6157.v2.yml
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
  lock-api/src/main/metrics/metric-schema.yml
Labels: autorelease, merge when ready

#6153 Optimize Timelock
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TaggedMetricsInvocationEventHandler.java
  changelog/@unreleased/pr-6153.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/HeldLocksGrant.java
  lock-api-objects/src/main/java/com/palantir/lock/HeldLocksToken.java
  lock-api-objects/src/main/java/com/palantir/lock/LockDescriptor.java
  lock-api-objects/src/main/java/com/palantir/lock/LockRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/LockResponse.java
  lock-api-objects/src/main/java/com/palantir/lock/SimpleTimeDuration.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/v1/ConjureLockV1Resource.java
Labels: autorelease, merge when ready

#6142 [TTS] | Task to update KCT
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/ConcludedTransactionsUpdaterTask.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/CoordinationAwareKnownConcludedTransactionsStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/TimestampRangeSet.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/ConcludedTransactionsUpdaterTaskTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/CoordinationAwareKnownConcludedTransactionsStoreTest.java
  changelog/@unreleased/pr-6142.v2.yml
Labels: merge when ready

#6160 [C2B2/TimeLock Serialization] Phase 2a: Days of Ruin (Server-Side)
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/TimeoutSensitiveConjureTimelockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/LockDiagnosticConjureTimelockService.java
  changelog/@unreleased/pr-6149.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/DialogueAdaptingConjureTimelockService.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/ConjureTimelockResourceTest.java
Labels: autorelease

#6151 [C2B2/TimeLock Serialization] Phase 1b: One Shotters (Client-Side)
  changelog/@unreleased/pr-6151.v2.yml
  lock-api-objects/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/DialogueAdaptingConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockServiceImpl.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/TimestampCorroboratingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/TimestampCorroboratingTimelockServiceTest.java
  timelock-agent/src/main/java/com/palantir/timelock/invariants/TimeLockActivityChecker.java
  timelock-agent/src/test/java/com/palantir/timelock/invariants/TimeLockActivityCheckerTest.java
  timestamp-api/src/main/java/com/palantir/timestamp/TimestampRange.java
Labels: autorelease, merge when ready

#6168 [C2B2/TimeLock Serialization] Phase 2b: Days of Ruin (Client-Side)
  changelog/@unreleased/pr-6168.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/DialogueAdaptingConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/LeaderElectionReportingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockServiceImpl.java
  lock-api/src/main/java/com/palantir/lock/client/TimestampCorroboratingTimelockService.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
Labels: autorelease
