Repository palantir/atlasdb, pull requests merged in 2022-09, with the labels that each got.

#6143 [Transactions Table Sweep] Part 4: Futile Timestamps Store
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/encoding/TicketsCellEncodingStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTables.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/AbandonedTimestampStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/DefaultAbandonedTimestampStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/encoding/TicketsCellEncodingStrategyTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/DefaultAbandonedTimestampStoreTest.java
Labels: no changelog, autorelease, merge when ready

#6198 Optimize CassandraService port checks
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-6198.v2.yml
Labels: merge when ready

#6200 Minor tracing perf tweak & add row counting on getRange
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueServiceTest.java
  changelog/@unreleased/pr-6200.v2.yml
Labels: merge when ready

#6208 TTS | Knowledge respecting TsExtractingTable
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-commons/src/main/java/com/palantir/atlasdb/futures/AtlasFutures.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/InternalSchemaInstallConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/encoding/TwoPhaseEncodingStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownAbortedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/CassandraImitatingConsensusForgettingStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTableTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownAbortedTransactionsImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImplTest.java
  changelog/@unreleased/pr-6208.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AtlasBackupResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AtlasRestoreResource.java
Labels: autorelease, merge when ready

#6219 Fix KeyValueService typo
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
Labels: no changelog, merge when ready

#6211 Remove unnecessary atlasdb-processors dependency
  atlasdb-cassandra/build.gradle
Labels: no changelog, autorelease, merge when ready

#6186 [PDS-265616] Handle runtime config in migration CLI
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/AbstractCommand.java
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestKvsMigrationCommand.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/runner/InMemoryTestRunner.java
  atlasdb-cli/src/test/resources/cli_test_runtime_config.yml
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/compact/CompactorConfig.java
  changelog/@unreleased/pr-6186.v2.yml
  docs/source/cluster_management/kvs-migration.rst
Labels: merge when ready

#6221 [TTS] Merge Futile and abandoned ts stores
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/AbortedTransactionSoftCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/FutileTimestampStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownAbortedTransactionsImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/AbortedTransactionSoftCacheTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownAbortedTransactionsImplTest.java
  changelog/@unreleased/pr-6221.v2.yml
Labels: merge when ready

#6225 Flaky eventLogDoesNotDeadlockUnderConcurrentLoad test retries
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogTest.java
Labels: no changelog, merge when ready

#6213 Remove the conjure-java-jersey-server dependency
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweeperServiceImpl.java
Labels: no changelog, merge when ready

#6231 Reduce number of cycles by 90%
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogTest.java
Labels: no changelog, merge when ready

#6228 [TTS] TransactionStatus FTW
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/service/AsyncTransactionService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/service/TransactionService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/service/TransactionStatus.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/PreStartHandlingTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SplitKeyDelegatingTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/WriteBatchingTransactionService.java
  changelog/@unreleased/pr-6228.v2.yml
Labels: merge when ready

#6230 Reduce Value Caching Validation by default to 10%
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/LockWatchCachingConfig.java
  changelog/@unreleased/pr-6230.v2.yml
Labels: autorelease, merge when ready

#6233 Fix writing locks by explicitly specifying versions for glassfish/jakarta
  versions.lock
  versions.props
Labels: no changelog

#6236 Order matters for AssertJ tests
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/TimestampExtractingAtomicTableTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
Labels: no changelog

#6234 [Drop Keyspace] Oracle Part 1: Simple refactoring
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleTestSuite.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/ConnectionManagerAwareDbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/SimpleTimedSqlConnectionSupplier.java
Labels: no changelog, merge when ready

#6235 [Drop Keyspace] Oracle Part 2: Reversing table name mappings
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-dbkvs/build.gradle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameGetter.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameGetterTest.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapperTest.java
Labels: no changelog, merge when ready

#6237 Specify libthrift version as 0.9.2
  changelog/@unreleased/pr-6237.v2.yml
  versions.lock
  versions.props
Labels: merge when ready

#6240 [Drop Keyspace] Oracle Part 3a: Add OracleTableNameGetter interface for mocks
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameGetter.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameGetterImpl.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameGetterImplTest.java
Labels: no changelog, merge when ready

#6204 Update docs to point to Maven Central instead of Bintary (and fix our release process docs)
  README.md
  docs/source/cluster_management/clis.rst
  docs/source/overview/getting_started.rst
  docs/source/release_notes/release-process.rst
  docs/source/troubleshooting/index.rst
Labels: no changelog, merge when ready

#6242 Fix doc typo
  docs/source/miscellaneous/doc/adr/0003-tagging-for-releases-and-long-term-support.md
Labels: merge when ready

#6212 [TTS] Readonly transactions on TTS
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionStatusUtils.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/AtlasDbServices.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/KeyValueServiceModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/InternalSchemaInstallConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadOnlyTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownAbortedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/TransactionKnowledgeComponents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTableTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ShardProgressTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CommitTimestampLoaderTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableTasksTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/service/TransactionServicesTest.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
Labels: autorelease, merge when ready

#6247 [PDS-299976] Rate limit noisy logline
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog, autorelease, merge when ready

#6239 [Drop Keyspace] Oracle Part 3: Make Drop retriable.
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTableTest.java
  changelog/@unreleased/pr-6239.v2.yml
Labels: merge when ready

#6232 [Sweep Metrics Task] last swept timestamp metric is scheduled to update periodically by reading from the shard progress table
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdater.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdaterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  changelog/@unreleased/pr-6232.v2.yml
Labels: do not merge, autorelease

#6243 [TTS] InMemory implementation of MCAS
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/CheckAndSetCompatibility.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CheckAndSetCompatibilityTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueService.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  changelog/@unreleased/pr-6243.v2.yml
Labels: merge when ready

#6254 Revert "[TTS] Readonly transactions on TTS (#6212)"
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionStatusUtils.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/AtlasDbServices.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/KeyValueServiceModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/InternalSchemaInstallConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadOnlyTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownAbortedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/TransactionKnowledgeComponents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/SimpleTransactionService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/service/TransactionServices.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/KnowledgeableTimestampExtractingAtomicTableTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/ShardProgressTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CommitTimestampLoaderTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableTasksTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/service/TransactionServicesTest.java
  changelog/@unreleased/pr-6254.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
Labels: autorelease, merge when ready

#6256 Have better async initialisation tests
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/TransactionManagersAsyncInitializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/keyvalue/impl/AsyncInitializeableInMemoryKvs.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/keyvalue/impl/AsyncInitializeableInMemoryKvsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbConfig.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactoryTest.java
Labels: no changelog
