Repository palantir/atlasdb, pull requests merged in 2022-04, with the labels that each got.

#5994 Cache persisted schema version locally
  changelog/@unreleased/pr-5994.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PersistedSchemaVersion.java
Labels: autorelease, merge when ready

#5995 [Runtime Config] Part 1: Merge semantics, abstracting merged config and exposing DerivedSnapshotConfig.
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/AtlasDbFactory.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/DerivedSnapshotConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/KeyValueServiceConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/KeyValueServiceConfigHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ForwardingCassandraKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraAtlasDbFactoryTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraReloadableKeyValueServiceRuntimeConfigTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbServiceDiscovery.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplier.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AutoServiceAnnotatedAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplierTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbConfig.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactoryTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactoryTest.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbAtlasDbFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/RelationalDbTimeLockFactory.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcAtlasDbFactory.java
  atlasdb-jdbc/src/main/java/com/palantir/atlasdb/keyvalue/jdbc/JdbcKeyValueConfiguration.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
Labels: no changelog, merge when ready

#6006 ABR 23: Store completed backups in parallel
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/AtlasBackupServiceTest.java
  changelog/@unreleased/pr-6006.v2.yml
Labels: autorelease, merge when ready

#6000 [Runtime Config][Part 2a] Wiring up restore, and making CqlCluster live reloadable
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasRestoreService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraServersConfigs.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/ReloadingCqlClusterContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CassandraRepairHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/ClusterMetadataUtils.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlCluster.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/CqlMetadata.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/RepairRangeFetcher.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcher.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/backup/TransactionAborter.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/ClusterFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/async/client/creation/DefaultCqlClientFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/ReloadingCqlClusterContainerTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/BackupTestUtils.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/RepairRangeFetcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/TokenRangeFetcherTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/backup/TransactionAborterTest.java
  atlasdb-cassandra/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/CassandraRepairEteTest.java
  changelog/@unreleased/pr-6000.v2.yml
Labels: merge when ready

#5999 fix workaround for hikari executor leak
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  changelog/@unreleased/pr-5999.v2.yml
Labels: autorelease, merge when ready

#6007 update ojdbc
  atlasdb-dbkvs-hikari/build.gradle
  changelog/@unreleased/pr-6007.v2.yml
  commons-db/build.gradle
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#6003 [Runtime Config][Part 2b] Wiring up Cassandra Verifier
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifierTest.java
Labels: no changelog, merge when ready

#6011 Add cleanupBackup
  atlasdb-backup/src/main/java/com/palantir/atlasdb/backup/AtlasBackupService.java
  atlasdb-backup/src/test/java/com/palantir/atlasdb/backup/AtlasBackupServiceTest.java
  changelog/@unreleased/pr-6011.v2.yml
Labels: priority: P0, must be merged, P0 follow-up, autorelease, merge when ready
