Repository palantir/atlasdb, pull requests merged in 2022-10, with the labels that each got.

#6258 Bump versions for module substitution
  build.gradle
Labels: no changelog

#6193 [TTS] MCAS batching
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/MarkAndCasConsensusForgettingStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/mcas/CasRequest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/mcas/CasRequestBatch.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/mcas/MarkAndCasConsensusForgettingStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/mcas/UpdateRank.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/encoding/TwoPhaseEncodingStrategy.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/MarkAndCasConsensusForgettingStoreTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/mcas/CasRequestBatchTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/mcas/CasRequestTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/mcas/MarkAndCasConsensusForgettingStoreTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/mcas/TestBatchElement.java
  changelog/@unreleased/pr-6193.v2.yml
Labels: autorelease, merge when ready

#6241 [Drop Keyspace] Oracle Part 4: Sqlite Oracle Adapter for tests
  atlasdb-dbkvs-tests/build.gradle
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/SqliteOracleAdapter.java
  commons-db/src/main/java/com/palantir/nexus/db/DBType.java
Labels: no changelog, merge when ready

#6266 Fix AtlasDB build
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/SqliteOracleAdapter.java
  changelog/@unreleased/pr-6266.v2.yml
Labels: merge when ready

#6267 [PDS-295687] Explicitly declare corner cases in KVS get APIs as undefined behaviour
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Cell.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  changelog/@unreleased/pr-6267.v2.yml
Labels: merge when ready

#6274 Best ever
  atlasdb-cli/src/test/resources/cli_test_runtime_config.yml
Labels: no changelog, merge when ready

#6272 [AtomicTable] Fix old bug
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/SimpleCommitTimestampAtomicTable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/SimpleCommitTimestampAtomicTableTest.java
  changelog/@unreleased/pr-6272.v2.yml
Labels: autorelease, merge when ready

#6261 [TTS] Sweep Unsweepable
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdater.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepInstallConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdaterTest.java
  changelog/@unreleased/pr-6261.v2.yml
Labels: merge when ready

#6255 Oracle truncate should release space
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  changelog/@unreleased/pr-6255.v2.yml
Labels: merge when ready

#6273 [TTS] Mark in progress
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/coordination/CoordinationResource.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/coordination/SimpleCoordinationResource.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/coordination/MultipleSchemaVersionsCoordinationEteTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-6273.v2.yml
Labels: autorelease, merge when ready

#6282 Downgrade snakeyaml
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#6283 Revert "Downgrade snakeyaml (#6282)"
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#6285 [Drop Keyspace] Namespace Deleter interface
  atlasdb-api/src/main/java/com/palantir/atlasdb/namespacedeleter/NamespaceDeleter.java
Labels: no changelog, merge when ready

#6288 Endpoint verification for thrift connections
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
  atlasdb-commons/src/main/java/com/palantir/exception/SafeSSLPeerUnverifiedException.java
  atlasdb-commons/src/test/java/com/palantir/exception/SafeSSLPeerUnverifiedExceptionTest.java
  changelog/@unreleased/pr-6288.v2.yml
Labels: autorelease, merge when ready

#6291 [TS] Make Sweep Resistant to Dropped Tables With Metadata
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTargetedSweepIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueDeleter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueUtils.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractTargetedSweepTest.java
  changelog/@unreleased/pr-6291.v2.yml
Labels: autorelease, merge when ready

#6292 Fix CassandraClientFactory.verifyEndpoint
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
Labels: no changelog, autorelease, merge when ready

#6286 Removing unused ReadOnlyTransactionManager
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadOnlyTransactionManager.java
  changelog/@unreleased/pr-6286.v2.yml
Labels: merge when ready

#6295 Include StrictHostnameVerifier on Classpath
  atlasdb-cassandra/build.gradle
  changelog/@unreleased/pr-6295.v2.yml
Labels: autorelease, merge when ready

#6279 [Log Safety] AtlasDB Log Safety Surge
  atlasdb-api/src/main/java/com/palantir/atlasdb/factory/TransactionManagerConsistencyResult.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlExecutorImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServer.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/logging/LoggingArgs.java
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/debug/TransactionPostMortemRunner.java
  atlasdb-conjure/src/main/java/com/palantir/atlasdb/http/v2/ResultOrThrowable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/compact/CompactPriorityCalculator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/ClientLockDiagnosticCollector.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/debug/FullDiagnosticDigest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CellsSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/lock/SingleLockService.java
  build.gradle
  changelog/@unreleased/pr-6279.v2.yml
  gradle/conjure.gradle
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-conjure-api/build.gradle
  lock-conjure-api/src/main/conjure/lock-api.yml
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-api/build.gradle
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-api/src/main/conjure/timelock-feedback.yml
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-api/src/main/conjure/timelock-paxos-api.yml
  timelock-corruption-detection/build.gradle
Labels: autorelease, merge when ready

#6259 RLLW1: Caching and Snapshotting row-level locks
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtils.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/lock/watch/LockWatchReferenceTableExtractor.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImplTest.java
Labels: no changelog, autorelease, merge when ready

#6300 [Drop Keyspace] Oracle add case insensitive metadata deletion
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTableTest.java
Labels: no changelog, merge when ready

#6313 [Backport][0.708.x] Bump Timelock and disable API guesser (#6309)
  changelog/@unreleased/pr-6309.v2.yml
  lock-api-objects/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/DialogueAdaptingConjureTimelockService.java
Labels: backport, merge when ready

#6289 [Drop Keyspace] Cassandra's turn!
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraNamespaceDeleterIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraNamespaceDeleter.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraNamespaceDeleterTest.java
Labels: no changelog, merge when ready

#6316 CassandraNamespaceDeleterIntegrationTest merge conflict fix
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraNamespaceDeleterIntegrationTest.java
Labels: no changelog, autorelease, merge when ready

#6297 [TTS] | Refactor all layers
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/ConcludedTransactionsUpdaterTask.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactions.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/coordinated/CoordinationAwareKnownConcludedTransactionsStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/ConcludedTransactionsUpdaterTaskTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/coordinated/CoordinationAwareKnownConcludedTransactionsStoreTest.java
  changelog/@unreleased/pr-6297.v2.yml
Labels: merge when ready

#6264 [Drop Keyspace] Oracle wrap up
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleTestSuite.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleNamespaceDeleterIntegrationTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleNamespaceDeleterTests.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/SqliteOracleAdapter.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/cleaner/OracleNamespaceDeleter.java
Labels: no changelog, merge when ready

#6293 [TTS] Metrics and telemetry
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/AbandonedTransactionSoftCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownAbandonedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/KnownConcludedTransactionsImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/knowledge/coordinated/CoordinationAwareKnownAbandonedTransactionsStore.java
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
  atlasdb-impl-shared/src/main/metrics/transactions4-knowledge.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/AbandonedTransactionSoftCacheTest.java
  changelog/@unreleased/pr-6293.v2.yml
Labels: autorelease, merge when ready

#6314 Better logging for endpoint verification
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
  changelog/@unreleased/pr-6314.v2.yml
Labels: autorelease, merge when ready

#6304 [TEX] Part 1a: ExpectationsManager implementation
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/ExpectationsConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/ExpectationsStatistics.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/KvsCallReadInfo.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/TransactionReadInfo.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/expectations/ExpectationsApiTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsAwareTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsTask.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsViolation.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingKeyValueService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/ExpectationsManagerTest.java
  changelog/@unreleased/pr-6304.v2.yml
Labels: merge when ready

#6318 [Drop Keyspace] Discovery for NamespaceDeleterFactory
  atlasdb-api/src/main/java/com/palantir/atlasdb/namespacedeleter/NamespaceDeleterFactory.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/KeyValueServiceConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/KeyValueServiceConfigHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfigsTest.java
  atlasdb-cassandra/src/test/resources/testConfig.yml
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbServiceDiscovery.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/memory/InMemoryAtlasDbConfig.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbServiceDiscoveryTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AutoServiceAnnotatedNamespaceDeleterFactory.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceConfig.java
Labels: no changelog, merge when ready

#6319 [Drop Keyspace] Cassandra namespace deleter factory
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraNamespaceDeleterIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraNamespaceDeleterFactory.java
Labels: no changelog, autorelease, merge when ready

#6269 remove more spans
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-commons/src/main/java/com/palantir/util/TimedRunner.java
  changelog/0.736.0-rc1/pr-6269.v2.yml
  changelog/0.742.0-rc1/pr-6269.v2.yml
  changelog/0.742.0-rc1/pr-6304.v2.yml
  changelog/@unreleased/pr-6269.v2.yml
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
  commons-executors/src/test/java/com/palantir/common/concurrent/PTExecutorsTest.java
Labels: autorelease, merge when ready
