Repository palantir/atlasdb, pull requests merged in 2023-01, with the labels that each got.

#6408 Optimize Thrift column sizing
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/thrift/ThriftObjectSizeUtils.java
  changelog/@unreleased/pr-6408.v2.yml
Labels: merge when ready

#6402 Prefer tagged metrics
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricNameCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/util/MetricsManager.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetrics.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/MetricsManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/internalschema/metrics/MetadataCoordinationServiceMetricsTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/monitoring/TimestampTrackerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  changelog/@unreleased/pr-6402.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackSink.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/TimelockNamespacesTest.java
Labels: merge when ready

#6404 Use the latest javax-compatible undertow release without forcing incompatible jakarta dependencies
  changelog/@unreleased/pr-6404.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#6412 Circular Crop Rotation
  .circleci/config.yml
Labels: no changelog, merge when ready

#6397 Intern Namespace and TableReference names
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Namespace.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TableReference.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/NamespaceTest.java
  changelog/@unreleased/pr-6397.v2.yml
Labels: merge when ready

#6409 Reduce allocations from observability
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CellLoader.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelperTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  changelog/@unreleased/pr-6409.v2.yml
Labels: merge when ready

#6426 ETE uses adoptopenjdk/openjdk11:x86_64-debian-jre-11.0.18_10
  atlasdb-ete-tests/Dockerfile
Labels: no changelog, merge when ready

#6420 Reduce lock state logging allocations
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  lock-impl/src/main/java/com/palantir/lock/logger/LockServiceStateLogger.java
  lock-impl/src/main/java/com/palantir/lock/logger/LogState.java
  lock-impl/src/test/java/com/palantir/lock/logger/LockServiceStateLoggerTest.java
Labels: no changelog, merge when ready

#6415 [PDS-321180] Permit Cluster Switches/Additions, Where New Nodes Agree With Old Nodes
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  changelog/@unreleased/pr-6415.v2.yml
Labels: autorelease, merge when ready

#6427 create test case which shows quorum calculation is wrong
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  changelog/@unreleased/pr-6427.v2.yml
Labels: merge when ready

#6413 [REVERT] Avoid NPE in CassandraClientPoolImpl.cleanUpOnInitFailure #6323
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  changelog/@unreleased/pr-6413.v2.yml
  commons-executors/src/main/java/com/palantir/common/concurrent/InitializeableScheduledExecutorServiceSupplier.java
  commons-executors/src/main/java/com/palantir/common/concurrent/ScheduledExecutorServiceFactory.java
  commons-executors/src/test/java/com/palantir/common/concurrent/InitializeableScheduledExecutorServiceSupplierTest.java
Labels: merge when ready

#6424 Fix #6422 (and more!): Row Column Range Sadness
  atlasdb-commons/src/main/java/com/palantir/common/base/ClosableIterators.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6424.v2.yml
Labels: autorelease, merge when ready

#6421 Bump libthrift
  .palantir/revapi.yml
  atlasdb-backup/baseline-class-uniqueness.lock
  atlasdb-cassandra/baseline-class-uniqueness.lock
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/InstrumentedTSocket.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TSocketFactory.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
  atlasdb-cli-distribution/baseline-class-uniqueness.lock
  atlasdb-cli/baseline-class-uniqueness.lock
  atlasdb-console-distribution/baseline-class-uniqueness.lock
  atlasdb-container-test-utils/baseline-class-uniqueness.lock
  atlasdb-ete-tests/baseline-class-uniqueness.lock
  atlasdb-perf/baseline-class-uniqueness.lock
  changelog/0.788.0-rc2/pr-6421.v2.yml
  changelog/@unreleased/pr-6421.v2.yml
  timelock-server-benchmark-client/baseline-class-uniqueness.lock
  timelock-server-benchmark-cluster/baseline-class-uniqueness.lock
  timelock-server-distribution/baseline-class-uniqueness.lock
  timelock-server/baseline-class-uniqueness.lock
  versions.lock
  versions.props
Labels: merge when ready
