Repository palantir/atlasdb, pull requests merged in 2023-05, with the labels that each got.

#6530 Add and run ring workflow
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/TransactionStoreFactory.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowConfiguration.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerInstallConfiguration.java
  atlasdb-workload-server-distribution/src/test/resources/workload-server.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.yml
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/SingleRowTwoCellsWorkflowConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflowConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflows.java
Labels: no changelog, merge when ready

#6562 Avoid boxing for Cassandra known port checks
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  changelog/@unreleased/pr-6562.v2.yml
Labels: merge when ready

#6563 [PDS-350703 and Others | i like trains] Part 4: The Meaning of What 'Is' Is / Hotfix Boolean Serialization
  changelog/@unreleased/pr-6563.v2.yml
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/LockServerOptions.java
  lock-api/src/main/java/com/palantir/lock/LockState.java
  lock-api/src/test/java/com/palantir/lock/LockServerOptionsTest.java
  lock-api/src/test/resources/lock-server-options.json
Labels: autorelease, merge when ready

#6551 Improve unsuccessful lock logging
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AdvisoryLockConditionSuppliers.java
  changelog/@unreleased/pr-6551.v2.yml
Labels: autorelease, merge when ready

#6558 Buggify utility helpers
  atlasdb-buggify/build.gradle
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/api/Buggify.java
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/api/BuggifyFactory.java
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/impl/DefaultBuggify.java
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/impl/DefaultBuggifyFactory.java
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/impl/NoOpBuggify.java
  atlasdb-buggify/src/test/java/com/palantir/atlasdb/buggify/impl/DefaultBuggifyFactoryTest.java
  atlasdb-buggify/src/test/java/com/palantir/atlasdb/buggify/impl/DefaultBuggifyTest.java
  atlasdb-buggify/src/test/java/com/palantir/atlasdb/buggify/impl/NoOpBuggifyTest.java
  settings.gradle
Labels: no changelog

#6567 Explicitly use NativePRNG for Buggify
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/api/NativeSamplingSecureRandomFactory.java
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/impl/DefaultBuggifyFactory.java
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/impl/DefaultNativeSamplingSecureRandomFactory.java
  atlasdb-workload-server/build.gradle
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingGraph.java
Labels: no changelog

#6569 [CBT] Split test into multiple workflows
  .circleci/config.yml
  changelog/@unreleased/pr-6569.v2.yml
  gradle/shared.gradle
  scripts/circle-ci/run-circle-tests.sh
Labels: merge when ready

#6570 Skramer/cassandra chaos
  atlasdb-buggify/src/main/java/com/palantir/atlasdb/buggify/AlwaysBuggifyFactory.java
  atlasdb-workload-server-antithesis/var/compact.sh
  atlasdb-workload-server-antithesis/var/docker-compose.yml
  atlasdb-workload-server-antithesis/var/flush.sh
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/resource/CassandraSidecarResource.java
  atlasdb-workload-server-distribution/build.gradle
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/background/BackgroundCassandraJob.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/resource/AntithesisCassandraSidecarResource.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/background/BackgroundCassandraJobTest.java
Labels: no changelog, merge when ready

#6564 Avoid Stream overhead in getRandomHostByActiveConnections
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-6564.v2.yml
Labels: merge when ready

#6538 Bump testing to Oracle 19.19 Apr 2023
  atlasdb-ete-tests/docker-compose.oracle.yml
Labels: no changelog, merge when ready

#6525 Explicitly pin guava versions to avoid slow dependency resolution
  versions.props
Labels: no changelog, merge when ready

#6576 held locks is a multimap (multiple read locks)
  lock-impl/src/main/java/com/palantir/lock/logger/LockServiceStateLogger.java
  lock-impl/src/main/java/com/palantir/lock/logger/LockServiceTestUtils.java
  lock-impl/src/main/java/com/palantir/lock/logger/LogState.java
  lock-impl/src/test/java/com/palantir/lock/logger/LockServiceSerDeTest.java
  lock-impl/src/test/java/com/palantir/lock/logger/LockServiceStateLoggerTest.java
Labels: no changelog, autorelease, merge when ready

#6410 Use Caffeine instead of Guava caches
  .baseline/checkstyle/custom-suppressions.xml
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManagers.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/NoDuplicateWritesTransaction.java
  atlasdb-commons/build.gradle
  atlasdb-commons/src/main/java/com/palantir/common/exception/TableMappingNotFoundException.java
  atlasdb-commons/src/main/java/com/palantir/util/MutuallyExclusiveSetLock.java
  atlasdb-container-test-utils/build.gradle
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/Containers.java
  atlasdb-dbkvs/build.gradle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapper.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableMetadataCache.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/TableValueStyleCacheImpl.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapperTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/CachingPuncherStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/CommitTsCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitioner.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitionerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManagerTest.java
  atlasdb-service/build.gradle
  atlasdb-service/src/main/java/com/palantir/atlasdb/impl/AtlasDbServiceImpl.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/impl/TableMetadataCache.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestConflictDetectionManagers.java
  changelog/@unreleased/pr-6410.v2.yml
  commons-db/build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/pool/RetriableTransactions.java
  leader-election-impl/src/main/java/com/palantir/paxos/CoalescingPaxosLatestRoundVerifier.java
  lock-impl/build.gradle
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
Labels: merge when ready

#6580 add flush and compact to antithesis config image
  atlasdb-workload-server-antithesis/Dockerfile
  atlasdb-workload-server-antithesis/build.gradle
Labels: no changelog, merge when ready

#6566 Initialize workload server asynchronously
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.yml
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
Labels: no changelog, merge when ready

#6585 Use subclass mock maker in atlasdb-commons
  .java-version
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CheckedRejectionExecutorServiceTest.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CoalescingSupplierTest.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ExperimentRunningProxyTest.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/PredicateSwitchedProxyTest.java
  atlasdb-commons/src/test/java/com/palantir/common/proxy/ReplaceIfExceptionMatchingProxyTest.java
  atlasdb-commons/src/test/java/com/palantir/util/CachedComposedSupplierTest.java
  atlasdb-commons/src/test/java/com/palantir/util/SafeShutdownRunnerTest.java
  atlasdb-commons/src/test/java/com/palantir/util/TimedRunnerTest.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6506 Optimize TimestampMapping::leader to avoid stream overhead
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampMapping.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampMappingTest.java
  changelog/@unreleased/pr-6506.v2.yml
Labels: merge when ready

#6554 Add current pool size metric
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetrics.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraClientPoolMetricsTest.java
  changelog/@unreleased/pr-6554.v2.yml
Labels: merge when ready

#6584 [CBT] Split up container 3 and add more max heap to timelock integTest
  .circleci/config.yml
  changelog/@unreleased/pr-6584.v2.yml
  scripts/circle-ci/run-circle-tests.sh
Labels: merge when ready

#6586 Lower gc grace for C* tables for antithesis workflows/tests
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
Labels: no changelog, merge when ready

#6468 Avoid string case conversion when parsing token ring
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/LightweightOppToken.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/Tokens.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/LightweightOppTokenTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TokensTest.java
  changelog/@unreleased/pr-6468.v2.yml
Labels: merge when ready

#6590 Modify script to support webhook integration for Antithesis
  atlasdb-workload-server-distribution/build.gradle
  gradle/docker.gradle
  scripts/circle-ci/publish-to-antithesis.sh
  timelock-server-distribution/build.gradle
Labels: no changelog, merge when ready

#6588 Print index for single row two cell workflow for successful transactions
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/SingleRowTwoCellsWorkflows.java
Labels: no changelog, merge when ready

#6595 [TEX] Report transaction level metrics
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/metrics/expectations.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ExpectationsMetricsReportingTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  changelog/@unreleased/pr-6595.v2.yml
Labels: autorelease, merge when ready

#6581 Hint away NESTED LOOP SEMI on overflow delete
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleOverflowWriteTable.java
  changelog/@unreleased/pr-6581.v2.yml
Labels: autorelease, merge when ready

#6582 Add snapshot isolation invariant
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/invariant/MismatchedValue.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/invariant/TransactionInvariant.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/invariant/ValueAndMaybeTimestamp.java
  atlasdb-workload-server-api/src/test/java/com/palantir/atlasdb/workload/invariant/MismatchedValueTest.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/SerializableInvariant.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/SnapshotInvariant.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/SnapshotInvariantVisitor.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/VersionedTableView.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/invariant/SnapshotInvariantTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/invariant/VersionedTableViewTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/WitnessedTransactionsBuilder.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/WorkloadTestHelpers.java
Labels: no changelog, merge when ready

#6594 Completely random workflow that will hopefully find us a bug!
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerInstallConfiguration.java
  atlasdb-workload-server-distribution/src/test/resources/workload-server.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.yml
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/RandomWorkflowConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/RandomWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/RandomWorkflowsTest.java
Labels: no changelog
