Repository palantir/atlasdb, pull requests merged in 2023-10, with the labels that each got.

#6761 Validate initial server list, before refreshing pools (but after creating keyspace)
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  changelog/@unreleased/pr-6761.v2.yml
Labels: merge when ready, 🤖 fix nits

#6756 Delay absent marking of missing cassandra servers till after validation
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
Labels: no changelog, autorelease, merge when ready

#6766 [PDS-403847] [III] Part 1: Model Plausible Evolutions in CassandraTopologyValidator
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/HostIdEvolution.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/HostIdEvolutionTest.java
  changelog/@unreleased/pr-6766.v2.yml
Labels: autorelease

#6767 [PDS-403847] [III] Part 2: Update Stored Topology To Reflect Admissions During NO_QUORUM
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  changelog/@unreleased/pr-6767.v2.yml
Labels: autorelease, merge when ready

#6770 Update targeted sweep docs to mention 16 shards
  docs/source/cluster_management/sweep/targeted-sweep.rst
Labels: merge when ready

#6768 [PDS-403847] [III] Part 3: Accept Nodes Presenting Plausible-Evolution IDs Even If Not In Quorum
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/HostIdEvolution.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/NonSoftFailureHostIdResult.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/HostIdEvolutionTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/NonSoftFailureHostIdResultTest.java
  changelog/@unreleased/pr-6768.v2.yml
Labels: autorelease, merge when ready

#6773 add QoS config for DBKvs parallel operations
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/KeyValueServices.java
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/BlockingWorkerPool.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DdlConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/batch/ParallelTaskRunner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/table/common/RangeVisitor.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/table/common/TableTasks.java
  changelog/@unreleased/pr-6773.v2.yml
Labels: autorelease, merge when ready

#6706 Maybe log SQLException error cause
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
Labels: no changelog, merge when ready

#6769 Add logging upon validation
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigrators.java
  atlasdb-cli/src/main/java/com/palantir/atlasdb/cli/command/KvsMigrationCommand.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/schema/KeyValueServiceMigrator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/schema/KeyValueServiceMigratorUtils.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/schema/KeyValueServiceValidator.java
  changelog/@unreleased/pr-6769.v2.yml
Labels: autorelease, merge when ready

#6786 remove tests.gradle file
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-ete-tests/build.gradle
  atlasdb-workload-server-distribution/build.gradle
  gradle/tests.gradle
  timelock-agent/build.gradle
  timelock-impl/build.gradle
  timelock-server-benchmark-client/build.gradle
  timelock-server-benchmark-cluster/build.gradle
  timelock-server-distribution/build.gradle
  timelock-server/build.gradle
Labels: no changelog, merge when ready

#6787 Boyoruk/junit5 atlasdb api
  atlasdb-api/build.gradle
  atlasdb-api/src/test/java/com/palantir/atlasdb/config/LeaderConfigTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/AtlasLockDescriptorUtilsTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CandidateCellForSweepingTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CellReferenceTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CellTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CheckAndSetCompatibilityTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/ClusterAvailabilityStatusTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/KeyAlreadyExistsExceptionTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/RetryLimitReachedExceptionTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/SweepResultsTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/TableReferenceTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/TargetedSweepMetadataTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/ValueTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValueTests.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ReadOnlyTransactionScopedCacheTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/DisjointUnionTaggedMetricSetTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/FilteredTaggedMetricSetTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/metrics/MetricPublicationArbiterTest.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/transaction/api/KeyValueServiceStatusTest.java
  atlasdb-autobatch/build.gradle
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/AutobatchersTests.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/BatchSizeRecorderTest.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/CoalescingBatchingEventHandlerTests.java
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/TracingEventHandlerTest.java
  atlasdb-buggify/build.gradle
  atlasdb-buggify/src/test/java/com/palantir/atlasdb/buggify/impl/DefaultBuggifyFactoryTest.java
  atlasdb-buggify/src/test/java/com/palantir/atlasdb/buggify/impl/DefaultBuggifyTest.java
  atlasdb-buggify/src/test/java/com/palantir/atlasdb/buggify/impl/NoOpBuggifyTest.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6789 Throw QosException if autobatcher is shutdown
  atlasdb-autobatch/build.gradle
  atlasdb-autobatch/src/main/java/com/palantir/atlasdb/autobatch/DisruptorAutobatcher.java
Labels: no changelog, autorelease, merge when ready

#6792 timelock-server junit5
  timelock-server-benchmark-client/build.gradle
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/runner/BenchmarksRunner.java
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/runner/SlaVerifier.java
  timelock-server-benchmark-cluster/build.gradle
  timelock-server-distribution/build.gradle
  timelock-server/build.gradle
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AbstractAsyncTimelockServiceIntegrationTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/DbTimeLockSingleLeaderPaxosStressTests.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/suite/DbTimeLockSingleLeaderPaxosSuite.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/config/DatabaseTsBoundPersisterConfigurationTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/ExclusiveLockTests.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/HeldLocksCollectionTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/HeldLocksTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/ImmutableTimestampTrackerTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/LeaseExpirationTimerTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/LockAcquirerTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/LockCollectionTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/ParameterInjector.java
  versions.lock
Labels: no changelog, merge when ready

#6793 timestamp
  timestamp-api/build.gradle
  timestamp-api/src/test/java/com/palantir/timestamp/TimestampRangeTest.java
  timestamp-api/src/test/java/com/palantir/timestamp/TimestampStoreInvalidatorTest.java
  timestamp-client/build.gradle
  timestamp-client/src/test/java/com/palantir/timestamp/DelegatingManagedTimestampServiceTest.java
  timestamp-client/src/test/java/com/palantir/timestamp/RequestBatchingTimestampServiceTest.java
  timestamp-impl/build.gradle
  timestamp-impl/src/test/java/com/palantir/timestamp/AbstractTimestampServiceTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/AtomicTimestampTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/ErrorCheckingTimestampBoundStoreTest.java
  timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceMockingTest.java
  timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/PersistentUpperLimitTest.java
  timestamp-impl/src/test/java/com/palantir/timestamp/TimestampAllocationFailuresTest.java
  timestamp-impl/src/test/java/com/palantir/timestamp/TimestampRangesTest.java
Labels: no changelog, merge when ready

#6783 Log UserAgent for new timelock namespaces
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/InMemoryTimelockServices.java
  changelog/@unreleased/pr-6783.v2.yml
  lock-conjure-api/src/main/conjure/lock-api.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureLockWatchingResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/JerseyAsyncTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/LockV1Resource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimelockNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimestampManagementResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimestampResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/UndertowAsyncTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/v1/ConjureLockV1Resource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/NamespacedConsensus.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/ConjureTimelockResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/TimelockNamespacesTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
Labels: autorelease, merge when ready

#6794 lock junit5
  lock-api-objects/build.gradle
  lock-api-objects/src/test/java/com/palantir/lock/watch/LockEventTest.java
  lock-api-objects/src/test/java/com/palantir/util/IndexEncodingUtilsTest.java
  lock-api/build.gradle
  lock-api/src/test/java/com/palantir/lock/AtlasLockDescriptorRangesTest.java
  lock-api/src/test/java/com/palantir/lock/HeldLocksTokenTest.java
  lock-api/src/test/java/com/palantir/lock/LockClientTest.java
  lock-api/src/test/java/com/palantir/lock/LockDescriptorTest.java
  lock-api/src/test/java/com/palantir/lock/LockServerOptionsTest.java
  lock-api/src/test/java/com/palantir/lock/client/AsyncTimeLockUnlockerTest.java
  lock-api/src/test/java/com/palantir/lock/client/BatchingCommitTimestampGetterTest.java
  lock-api/src/test/java/com/palantir/lock/client/BlockEnforcingLockServiceTest.java
  lock-api/src/test/java/com/palantir/lock/client/ConjureLockV1ResourceTest.java
  lock-api/src/test/java/com/palantir/lock/client/IdentifiedLockRequestTest.java
  lock-api/src/test/java/com/palantir/lock/client/LeaderElectionReportingTimelockServiceTest.java
  lock-api/src/test/java/com/palantir/lock/client/LeasedLockTokenTest.java
  lock-api/src/test/java/com/palantir/lock/client/LockLeaseServiceTest.java
  lock-api/src/test/java/com/palantir/lock/client/LockRefresherTest.java
  lock-api/src/test/java/com/palantir/lock/client/LockTokenShareTest.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientCommitTimestampGetterTest.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientTimeLockUnlockerTest.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientTransactionStarterTest.java
  lock-api/src/test/java/com/palantir/lock/client/ProfilingTimelockServiceTest.java
  lock-api/src/test/java/com/palantir/lock/client/ReferenceTrackingWrapperTest.java
  lock-api/src/test/java/com/palantir/lock/client/TimeLockClientTest.java
  lock-api/src/test/java/com/palantir/lock/client/TimestampCorroboratingTimelockServiceTest.java
  lock-api/src/test/java/com/palantir/lock/client/TransactionStarterTest.java
  lock-api/src/test/java/com/palantir/lock/client/UnreliableTimelockClientTest.java
  lock-api/src/test/java/com/palantir/lock/v2/IdentifiedTimeLockRequestSerializationDeserializationTest.java
  lock-api/src/test/java/com/palantir/lock/v2/LeadershipIdTest.java
  lock-api/src/test/java/com/palantir/lock/v2/LeaseTest.java
  lock-api/src/test/java/com/palantir/lock/v2/LockResponseV2Test.java
  lock-api/src/test/java/com/palantir/lock/v2/PartitionedTimestampsTest.java
  lock-api/src/test/java/com/palantir/lock/watch/ConjureLockRequestMetadataUtilsTest.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchCacheImplTest.java
  lock-impl/build.gradle
  lock-impl/src/test/java/com/palantir/lock/AllLockTests.java
  lock-impl/src/test/java/com/palantir/lock/client/LockRefreshingLockServiceTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/AdjustableBackgroundTaskTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ClientAwareLockTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/LegacyTimelockServiceTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/LockServiceImplTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/LockTokenConverterTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ThreadInfoLockServiceImplTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ThreadPooledWrapperTest.java
  lock-impl/src/test/java/com/palantir/lock/logger/LockServiceSerDeTest.java
  lock-impl/src/test/java/com/palantir/lock/logger/LockServiceStateLoggerTest.java
Labels: no changelog, merge when ready

#6799 commons junit5
  commons-db/build.gradle
  commons-db/src/test/java/com/palantir/nexus/db/ThreadConfinedProxyTest.java
  commons-db/src/test/java/com/palantir/nexus/db/sql/BasicSQLTest.java
  commons-db/src/test/java/com/palantir/nexus/db/sql/SQLStringTest.java
  commons-executors/build.gradle
  commons-executors/src/test/java/com/palantir/common/concurrent/ExecutorInheritableThreadLocalTest.java
  commons-executors/src/test/java/com/palantir/common/concurrent/InitializeableScheduledExecutorServiceSupplierTest.java
  commons-executors/src/test/java/com/palantir/common/concurrent/PTExecutorsTest.java
Labels: no changelog, merge when ready

#6798 Boy/subdirectory creater
  atlasdb-tests-shared/src/main/java/com/palantir/test/utils/SubdirectoryCreator.java
  leader-election-impl/build.gradle
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SplittingPaxosStateLogTest.java
  timelock-agent/build.gradle
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosInstallConfigurationIntegrationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
  timelock-impl/build.gradle
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
Labels: no changelog, merge when ready

#6797 leader election
  atlasdb-buggify/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/test/utils/SubdirectoryCreator.java
  examples/profile-client/build.gradle
  examples/profile-client/src/test/java/com/palantir/example/profile/CookiesIdxColumnTest.java
  examples/profile-client/src/test/java/com/palantir/example/profile/ProfileStoreTest.java
  examples/profile-client/src/test/java/com/palantir/example/profile/WritesDigestTest.java
  flake-rule/build.gradle
  leader-election-api/build.gradle
  leader-election-impl/build.gradle
  leader-election-impl/src/test/java/com/palantir/leader/LeadershipEventRecorderTest.java
  leader-election-impl/src/test/java/com/palantir/leader/PingResultTest.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AsyncRetrierTest.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/AllLeaderElectionTests.java
  leader-election-impl/src/test/java/com/palantir/paxos/CoalescingPaxosLatestRoundVerifierTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/GreenNodeLeadershipAttemptHistoryTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosAcceptorStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusSlowTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosLatestRoundVerifierTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogBatchReaderTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PersistedRateLimitingLeadershipPrioritiserTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SingleLeaderPingerTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SplittingPaxosStateLogTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogMigrationStateTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SqlitePaxosStateLogTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/persistence/ProtobufTest.java
  timelock-agent/build.gradle
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosInstallConfigurationIntegrationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
  timelock-impl/build.gradle
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
Labels: no changelog, merge when ready

#6774 Add safe logging of NotCurrentLeader exception messages in timelock
  atlasdb-commons/src/main/java/com/palantir/common/remoting/ServiceNotAvailableException.java
  atlasdb-commons/src/main/java/com/palantir/leader/NotCurrentLeaderException.java
  leader-election-impl/build.gradle
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipCoordinator.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/transaction/timestamp/LeadershipGuardedClientAwareManagedTimestampServiceTest.java
Labels: no changelog, merge when ready

#6758 Simplify Alter Table workflow
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleAlterTableIntegrationTest.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/AlterTableMetadataReference.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleDdlConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/AlterTableMetadataReferenceTest.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTableTest.java
Labels: no changelog, merge when ready

#6778 Update Oracle image to support x86 and ARM CPU, and stanardise image across dev, Gotham III and k8
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleTestSuite.java
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-dbkvs-tests/src/test/resources/docker-startup/01_create_user.sql
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
  atlasdb-ete-tests/docker/conf/atlasdb-ete.embedded-and-oracle.yml
  docs/source/configuration/key_value_service_configs/oracle_key_value_service_config.rst
  timelock-server-distribution/var/conf/timelock-oracle.yml
Labels: no changelog
