Repository palantir/atlasdb, pull requests merged in 2023-06, with the labels that each got.

#6601 [Antithesis] Actually be concurrent 😱
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
Labels: no changelog

#6598 Add metric for number of commit lock acquisition failures
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcome.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetrics.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetricsAssert.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetricsTest.java
  changelog/@unreleased/pr-6598.v2.yml
Labels: merge when ready

#6600 Upgrade sqlite-jdbc from 3.36.0 to 3.42.0.0
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#6599 [Antithesis] Transient Rows Workflow: Fix Inconsistent Reads
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflowsTest.java
Labels: no changelog, merge when ready

#6625 [LockV1] Add async thread info snapshotting (disabled by default)
  changelog/@unreleased/pr-6625.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/LockClientAndThread.java
  lock-api/src/main/java/com/palantir/lock/DebugThreadInfoConfiguration.java
  lock-api/src/main/java/com/palantir/lock/LockServerOptions.java
  lock-impl/build.gradle
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockThreadInfoSnapshotManager.java
  lock-impl/src/test/java/com/palantir/lock/impl/ThreadInfoLockServiceImplTest.java
Labels: merge when ready

#6605 Remove DefaultLocale override
  build.gradle
Labels: no changelog, merge when ready

#6544 always run gradlew with --scan in tests
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog, merge when ready

#6623 [LockV1] Log lock holder thread info on timeout, slow lock acquisition and contention
  changelog/@unreleased/pr-6623.v2.yml
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockThreadInfoSnapshotManager.java
  lock-impl/src/test/java/com/palantir/lock/impl/LockServiceImplTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ThreadInfoLockServiceImplTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/LockCreator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/BlockingTimeLimitedLockService.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/BlockingTimeLimitedLockServiceTest.java
Labels: merge when ready

#6602 Add metrics for number of requested cell/row-level commit locks
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/TransactionCommitLockInfo.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ExpectationsAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingExpectationsAwareTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/metrics/expectations.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ExpectationsMetricsReportingTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6602.v2.yml
Labels: merge when ready

#6626 [LockV1] Pass refreshable thread info configuration
  changelog/@unreleased/pr-6626.v2.yml
  lock-api/src/main/java/com/palantir/lock/DebugThreadInfoConfiguration.java
  lock-api/src/main/java/com/palantir/lock/LockServerConfigs.java
  lock-impl/build.gradle
  lock-impl/src/main/java/com/palantir/lock/impl/AdjustableBackgroundTask.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
  lock-impl/src/main/java/com/palantir/lock/impl/LockThreadInfoSnapshotManager.java
  lock-impl/src/test/java/com/palantir/lock/impl/AdjustableBackgroundTaskTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ThreadInfoLockServiceImplTest.java
  timelock-agent/src/main/java/com/palantir/timelock/config/RestrictedTimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/LockCreator.java
Labels: merge when ready

#6641 Optimize CassandraService#refreshTokenRangesAndGetServers
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-6641.v2.yml
Labels: merge when ready

#6624 improvement: Don't check immutable timestamp lock on non empty reads from thoroughly swept tables
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DualWriteKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/SweepStrategy.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/SweepStrategyManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableRemappingKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableSplittingKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTaskRunner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitioner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitionerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6624.v2.yml
Labels: autorelease, merge when ready

#6648 Optimize CassandraService#getAddressForHost
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  changelog/@unreleased/pr-6648.v2.yml
Labels: merge when ready

#6649 Bump snappy-java to 1.1.10.1
  changelog/@unreleased/pr-6649.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#6644 [LWMeta] Create LockRequestMetadata and ChangeMetadata
  changelog/@unreleased/pr-6644.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/watch/ChangeMetadata.java
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockRequestMetadata.java
Labels: merge when ready

#6646 [LWMeta] Add metadata to LockEvent
  changelog/@unreleased/pr-6646.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockEvent.java
Labels: merge when ready

#6647 [LWMeta] Add LockMetadata to IdentifiedLockRequest
  changelog/@unreleased/pr-6647.v2.yml
  lock-api-objects/build.gradle
  lock-api-objects/src/main/java/com/palantir/lock/watch/LockRequestMetadata.java
  lock-api/src/main/java/com/palantir/lock/client/IdentifiedLockRequest.java
  lock-api/src/test/java/com/palantir/lock/client/IdentifiedLockRequestTest.java
  lock-api/src/test/resources/identified-lock-request-wire-format/baseline.json
Labels: merge when ready
