Repository palantir/atlasdb, pull requests merged in 2023-11, with the labels that each got.

#6805 Allow Atlasdb code to execute on JDK-21 to unblock testing
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-6805.v2.yml
Labels: autorelease, merge when ready

#6807 Update to Oracle 19.21 release
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
Labels: no changelog, merge when ready

#6809 junit5 config and conjure
  atlasdb-config/build.gradle
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbConfigDeserializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbConfigTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbConfigsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfigDeserializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfigTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/ServerListConfigsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/TimeLockClientConfigTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/TimeLockClientConfigsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/TransactionManagersAsyncInitializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProviderTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbServiceDiscoveryTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/PersistentStoragePathSanitizerTests.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/ServiceDiscoveringAtlasSupplierTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/startup/ConsistencyCheckRunnerTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/startup/TimeLockMigratorTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/ShortAndLongTimeoutServicesTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timelock/TimeoutSensitiveLockRpcClientTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/timestamp/FreshTimestampSupplierAdapterTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpProtocolVersionTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/ProtocolAwarenessTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/RedirectRetryTargeterTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/keyvalue/impl/AsyncInitializeableInMemoryKvsTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAsyncAtlasDbFactoryTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAtlasDbConfigTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/memory/InMemoryAtlasDbFactoryTest.java
  atlasdb-conjure/build.gradle
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/ClientOptionsTest.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/DialogueClientOptionsTest.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/FastFailoverProxyTest.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/RetryOnSocketTimeoutExceptionProxyTest.java
  atlasdb-conjure/src/test/java/com/palantir/atlasdb/http/v2/UnknownRemoteDebuggingProxyTest.java
  atlasdb-console-distribution/build.gradle
  atlasdb-console/build.gradle
  atlasdb-container-test-utils/build.gradle
  atlasdb-coordination-impl/build.gradle
  atlasdb-coordination-impl/src/test/java/com/palantir/atlasdb/coordination/keyvalue/CoordinationServiceImplTest.java
  atlasdb-coordination-impl/src/test/java/com/palantir/atlasdb/coordination/keyvalue/KeyValueServiceCoordinationStoreTest.java
  atlasdb-coordination-impl/src/test/java/com/palantir/atlasdb/coordination/keyvalue/TransformingCoordinationServiceTest.java
  atlasdb-dagger/build.gradle
  atlasdb-dagger/src/test/java/com/palantir/atlasdb/services/AtlasDbServicesTest.java
  atlasdb-dagger/src/test/java/com/palantir/atlasdb/services/RawKeyValueServiceModuleTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/test/utils/SubdirectoryCreator.java
  leader-election-impl/src/test/java/com/palantir/paxos/FileToSqlitePaxosStateLogIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosStateLogMigratorTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/SplittingPaxosStateLogTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/PaxosInstallConfigurationIntegrationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockInstallConfigurationTest.java
  timelock-agent/src/test/java/com/palantir/timelock/paxos/TimeLockAgentTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponentsTest.java
Labels: no changelog, merge when ready

#6812 tests shared
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractGetCandidateCellsForSweepingTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractMultiCasTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractBackgroundSweeperIntegrationTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTaskRunnerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractTargetedSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/progress/AbstractSweepProgressStoreTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/timestamp/AbstractDbTimestampBoundStoreTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/InMemoryTimeLockRule.java
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/InMemoryTimelockServices.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AllAtlasDbFastTests.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cache/RocksDbOffHeapTimestampCacheIntegrationTests.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/AsyncPuncherTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/InMemorySweepTaskRunnerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/PuncherTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/compress/CompressionUtilsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/health/MetricsBasedTimelockHealthCheckTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/internalschema/TransactionSchemaManagerIntegrationTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemorySerializableTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/MemoryTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/ColumnRangeSelectionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/InMemoryGetCandidateCellsForSweepingTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueServiceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/RangeRequestTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/RangeRequestsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableSplittingKeyValueServiceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableTasksTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TracingKvsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/persistent/rocksdb/RocksDbPersistentStoreTests.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/ptobject/EncodingUtilsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/AbstractTaskCheckpointerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/NamespaceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/indexing/IndexTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/StreamTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/priority/SweepPriorityStoreTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/progress/SweepProgressStoreTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweepTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CachingTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionSchemaVersionEnforcementTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/UnstableOrderedIterableTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetricsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/service/TransactionServicesTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/timelock/paxos/InMemoryTimelockServicesTest.java
Labels: no changelog, merge when ready

#6814 flaky retry extension
  flake-extension/build.gradle
  flake-extension/src/main/java/com/palantir/flake/FlakeRetryExtension.java
  flake-extension/src/main/java/com/palantir/flake/FlakeRetryTest.java
  flake-extension/src/test/java/com/palantir/flake/FlakeRetryTestTest.java
  flake-extension/src/test/java/com/palantir/flake/example/BeforeAndAfterTest.java
  flake-extension/src/test/java/com/palantir/flake/example/StringSupplierTest.java
  flake-extension/src/test/java/com/palantir/flake/fail/ExpectedFailure.java
  flake-extension/src/test/java/com/palantir/flake/fail/ExpectedFailureExtension.java
  flake-rule/build.gradle
  settings.gradle
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6813 Boy/first iteration wrap up
  atlasdb-cassandra-integration-tests/build.gradle
  atlasdb-dbkvs-hikari/build.gradle
  atlasdb-service/build.gradle
  atlasdb-workload-server-distribution/build.gradle
  commons-executors/build.gradle
  examples/profile-client/build.gradle
  gradle/shared.gradle
  timestamp-impl/build.gradle
Labels: no changelog, merge when ready

#6775 Safe logs for KeyAlreadyExistsException
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyAlreadyExistsException.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
Labels: no changelog, merge when ready, 🤖 fix nits

#6719 Reduce boilerplate code when creating transaction stores
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/TransactionStoreFactory.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
Labels: no changelog, autorelease, merge when ready

#6738 Clarify instruction in automated embedded -> server timelock migration runbook
  docs/source/services/timelock_service/migration.rst
Labels: merge when ready

#6818 flaky retry replace
  atlasdb-api/build.gradle
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CellReferenceTest.java
  atlasdb-cli/build.gradle
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestTimestampCommand.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/KeyValueServiceDataTrackerTest.java
  timelock-server/build.gradle
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
Labels: no changelog, merge when ready

#6815 Boy/parametrized junit5
  atlasdb-cassandra/build.gradle
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/LightweightOppTokenTest.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestSweepCommand.java
  atlasdb-client/build.gradle
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/IterablePartitionerTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableNameTest.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/TableMetadataPersistenceTest.java
  atlasdb-commons/src/test/java/com/palantir/common/compression/StreamCompressionTests.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/CoalescingSupplierTest.java
  atlasdb-dbkvs/build.gradle
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/AlterTableMetadataReferenceTest.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/RowsColumnRangeBatchRequestsTest.java
  lock-api-objects/build.gradle
  lock-api-objects/src/test/java/com/palantir/util/IndexEncodingUtilsTest.java
  timelock-impl/build.gradle
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosStateLogMigrationIntegrationTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: no changelog, merge when ready

#6817 parametrize with mockitoextension
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdaterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingKeyValueServiceReadInfoTest.java
Labels: no changelog, merge when ready

#6816 impl shared
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTableTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/SimpleCommitTimestampAtomicTableTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/cleaner/ScrubberTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/SweepableCellFilterParametrizedTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
Labels: no changelog, merge when ready

#6824 [PDS-435038] Close Only Relevant Delegates On Encountering (Suspected)NotCurrentLeaderException False Alarms
  atlasdb-commons/src/main/java/com/palantir/leader/SuspectedNotCurrentLeaderException.java
  changelog/@unreleased/pr-6824.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease, merge when ready

#6825 Hint GET_ROWS_COLUMN_RANGE in Oracle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleQueryFactory.java
  changelog/@unreleased/pr-6825.v2.yml
Labels: merge when ready

#6831 Fix Oracle hint
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleQueryFactory.java
Labels: no changelog, merge when ready

#6819 suite classes junit5
  atlasdb-commons/src/test/java/com/palantir/common/base/ThrowablesTest.java
  atlasdb-commons/src/test/java/com/palantir/util/AllAtlasCommonsTests.java
  atlasdb-commons/src/test/java/com/palantir/util/crypto/Sha256HashTest.java
  atlasdb-commons/src/test/java/com/palantir/util/paging/PageDrainerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/AllLeaderElectionTests.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusFastTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/PaxosConsensusSlowTest.java
  leader-election-impl/src/test/java/com/palantir/paxos/persistence/ProtobufTest.java
  lock-impl/build.gradle
  lock-impl/src/test/java/com/palantir/lock/AllLockTests.java
  lock-impl/src/test/java/com/palantir/lock/LockServiceTest.java
  lock-impl/src/test/java/com/palantir/lock/client/LockRefreshingLockServiceTest.java
  lock-impl/src/test/java/com/palantir/lock/impl/ClientAwareLockTest.java
  lock-impl/src/test/java/com/palantir/lock/logger/LockServiceStateLoggerTest.java
Labels: no changelog, merge when ready

#6820 remaining junit5
  atlasdb-autobatch/build.gradle
  atlasdb-autobatch/src/test/java/com/palantir/atlasdb/autobatch/TracingEventHandlerTest.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/AsyncInitializerTest.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/CallChainTest.java
  atlasdb-config/build.gradle
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProviderTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/http/AtlasDbHttpClientsTest.java
  atlasdb-console/build.gradle
  atlasdb-console/src/test/groovy/com/palantir/atlasdb/console/AtlasConsoleServiceTest.java
  atlasdb-console/src/test/groovy/com/palantir/atlasdb/console/groovy/AtlasConsoleServiceWrapperTest.groovy
  atlasdb-console/src/test/groovy/com/palantir/atlasdb/console/groovy/AtlasConsoleTestRunner.groovy
  atlasdb-console/src/test/groovy/com/palantir/atlasdb/console/groovy/TableTest.groovy
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/util/DropwizardClientRule.java
  atlasdb-perf/build.gradle
  atlasdb-perf/src/test/java/com/palantir/atlasdb/performance/PerformanceResultsTest.java
  atlasdb-perf/src/test/java/com/palantir/atlasdb/performance/backend/KeyValueServiceInstrumentationTest.java
  atlasdb-workload-server-distribution/build.gradle
  atlasdb-workload-server-distribution/src/test/java/com/palantir/atlasdb/workload/WorkloadServerLauncherTest.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-corruption-detection/build.gradle
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/CorruptionDetectionIntegrationTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/HistoryAnalyzerTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/LocalTimestampInvariantsVerifierTest.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionDetectionHelper.java
  timelock-corruption-detection/src/test/java/com/palantir/timelock/corruption/detection/TimeLockCorruptionTestSetup.java
  timelock-server/build.gradle
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6826 trivial
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/cleaner/InMemorySweepTaskRunnerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/InMemoryGetCandidateCellsForSweepingTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueServiceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TracingKvsTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/AbstractTaskCheckpointerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/indexing/IndexTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/StreamTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/progress/SweepProgressStoreTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweepTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
Labels: no changelog, merge when ready

#6834 fix(oracle): namespace deleter tests were not included
  atlasdb-dbkvs-tests/build.gradle
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/SqliteOracleAdapter.java
Labels: no changelog, merge when ready

#6821 Remove useless enableErrorProne property
  gradle.properties
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog, merge when ready

#6846 fix: Add setup_remote_docker statement to CircleCI config and check for CIRCLE_TAG existence before publish
  .circleci/config.yml
Labels: no changelog, autorelease, merge when ready

#6837 Change TransactionOutcomeMetrics to classify outcomes as success and fail for better aggregations
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcome.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetrics.java
  atlasdb-impl-shared/src/main/metrics/transaction.yml
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetricsAssert.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/metrics/TransactionOutcomeMetricsTest.java
Labels: no changelog, autorelease, merge when ready

#6850 TimeLockMigrationEteTest junit5
  atlasdb-ete-tests/build.gradle
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/standalone/TimeLockMigrationEteTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/utilities/DockerClientOrchestrationExtension.java
Labels: no changelog, merge when ready

#6857 Clarify and add tests for ColumnRangeSelections.createPrefixRange
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/ColumnRangeSelections.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RangeRequests.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/RangeRequestsTest.java
Labels: no changelog, merge when ready

#6851 Boy/ete junit5
  atlasdb-ete-tests/build.gradle
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractCassandraTimestampTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractLockWithTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractLockWithoutTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractMultiCassandraDoubleNodeDownTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractMultiCassandraSingleNodeDownTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractMultipleSchemaVersionsCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractTargetedSweepTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suiteclasses/AbstractTodoTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/utilities/CassandraCommandsV2.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/utilities/EteExtension.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/utilities/MultiCassandraUtilsV2.java
  versions.lock
Labels: no changelog, merge when ready

#6852 Boy/actual ete junit5
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/MultiClientWithPostgresTimelockAndPostgresTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/MultiClientWithTimelockAndCassandraTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/SingleClientWithEmbeddedAndCassandraTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraCassandraTimestampsTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraLockWithTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraMultipleSchemaVersionsCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraTargetedSweepTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndCassandraTodoTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndPostgresCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndPostgresLockWithTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndPostgresTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/MultiClientWithTimelockAndPostgresTodoTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndCassandraCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndCassandraMultipleSchemaVersionsCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndCassandraTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndCassandraTodoTest.java
Labels: no changelog, merge when ready

#6855 Boy/2actual ete junit5
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/SingleClientWithEmbeddedAndOracleTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/SingleClientWithEmbeddedAndPostgresTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/SingleClientWithEmbeddedAndThreeNodeCassandraTestSuite.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndOracleCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndOracleLockWithoutTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndOracleTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndOracleTodoTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndPostgresCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndPostgresLockWithoutTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndPostgresTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndPostgresTodoTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraLockWithoutTimelockTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraMultiCassandraDoubleNodeDownTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraMultiCassandraSingleNodeDownTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraMultipleSchemaVersionsCoordinationTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraTimestampManagementTest.java
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/tests/SingleClientWithEmbeddedAndThreeNodeCassandraTodoTest.java
Labels: no changelog, merge when ready

#6877 atlasdb-dbkvs-tests
  atlasdb-dbkvs-tests/build.gradle
  atlasdb-dbkvs-tests/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/AbstractDbKvsKeyValueServiceTest.java
  atlasdb-dbkvs-tests/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/AbstractDbKvsKeyValueServiceTestV2.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleKeyValueServiceTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/DbKvsPostgresKeyValueServiceTest.java
Labels: no changelog, merge when ready

#6876 atlasdb-container-test-utils
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/CassandraSchemaLockTest.java
  atlasdb-cassandra-multinode-tests/src/test/java/com/palantir/cassandra/multinode/NodesDownTestSetup.java
  atlasdb-container-test-utils/build.gradle
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainer.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraContainerV2.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/CassandraResource.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/Container.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ContainerV2.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/Containers.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ContainersV2.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/InterruptibleFileLogCollector.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ThreeNodeCassandraCluster.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ThreeNodeCassandraResource.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/UninitializedCassandraResource.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/ContainerTest.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/ContainerV2Test.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/ContainersTest.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/ContainersV2Test.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/FirstNginxContainer.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/FirstNginxContainerV2.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/SecondNginxContainer.java
  atlasdb-container-test-utils/src/test/java/com/palantir/atlasdb/containers/SecondNginxContainerV2.java
Labels: no changelog, merge when ready

#6873 Boy/timelock suite test
  scripts/circle-ci/run-circle-tests.sh
  timelock-server/build.gradle
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedTimestampSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedTimestampSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/DbTimelockSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/MultiLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/MultiLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/NonBatchedTimestampSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/NonBatchedTimestampSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/suite/SingleLeaderPaxosSuite.java
Labels: no changelog, merge when ready
