Repository palantir/atlasdb, pull requests merged in 2023-04, with the labels that each got.

#6500 CR comments
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/ColumnMetadataDescription.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTableTest.java
Labels: no changelog, merge when ready

#6488 Improve Sqlite namespace loader implementation
  changelog/@unreleased/pr-6488.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/PersistentNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoader.java
Labels: autorelease, merge when ready

#6501 Fix printing when durable writes invariant violated
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/DurableWritesMetricInvariantReporter.java
Labels: no changelog, merge when ready

#6499 Improve DB KVS default config
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/H2ConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/OracleConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/PostgresConnectionConfig.java
  changelog/@unreleased/pr-6499.v2.yml
Labels: autorelease

#6503 dump transaction log by default for workload server
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/RunOnceWorkflowRunner.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/server/RunOnceWorkflowRunnerTest.java
Labels: no changelog, autorelease, merge when ready

#6505 [0.780.x] Use undertow 2.2.24.Final
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#6511 Stop faults when validating invariants in Antithesis
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/AntithesisWorkflowRunner.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/AntithesisWorkflowRunnerTest.java
Labels: no changelog, merge when ready

#6504 create script to easily push to antithesis
  scripts/circle-ci/publish-to-antithesis.sh
Labels: no changelog, merge when ready

#6509 [release/0.756.x] Improve Sqlite namespace loader implementation
  changelog/@unreleased/pr-6488.v2.yml
  leader-election-impl/src/main/java/com/palantir/paxos/SqlitePaxosStateLog.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/PersistentNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoader.java
Labels: merge when ready

#6510 Fix bug in workload server when failing to fetch commit timestamp due to network errors
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStore.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreTest.java
Labels: no changelog, merge when ready

#6512 Add JNA and instrumentation jar to classpaths for timelock/workload server
  atlasdb-workload-server-distribution/Dockerfile
  timelock-server-distribution/Dockerfile
Labels: no changelog, merge when ready

#6514 fix antithesis script
  scripts/circle-ci/publish-to-antithesis.sh
Labels: no changelog, merge when ready

#6508 Use bindargs for rownum/limit in dbkvs
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/FullQuery.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleCellTsPageLoader.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleGetRange.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleQueryFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresCellTsPageLoader.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresGetRange.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresQueryFactory.java
  changelog/@unreleased/pr-6508.v2.yml
Labels: merge when ready

#6498 Choose optimal IOT compression based on table params
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/ColumnMetadataDescription.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTableTest.java
  changelog/@unreleased/pr-6498.v2.yml
Labels: merge when ready

#6522 Interactive transactions for workload server
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/InteractiveTransactionStore.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/InteractiveTransaction.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbInteractiveTransaction.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStore.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/AtlasDbInteractiveTransactionTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/WorkloadTestHelpers.java
Labels: no changelog, merge when ready

#6515 Simplify sweep enabled configuration
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/ShouldRunBackgroundSweepSupplier.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/SweepConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfigTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/ShouldRunBackgroundSweepSupplierTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweepThread.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/BackgroundSweeperImpl.java
Labels: no changelog, merge when ready

#6521 Make test query optional
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/HikariCPConnectionManager.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
Labels: no changelog, merge when ready

#6527 Use debian images instead of alpine
  atlasdb-workload-server-distribution/Dockerfile
  changelog/@unreleased/pr-6527.v2.yml
  timelock-server-distribution/Dockerfile
Labels: merge when ready

#6526 Check for serializable invariant for the single row two cells workflow
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/DurableWritesInvariantMetricReporter.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/SerializableInvariantLogReporter.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/invariant/DurableWritesInvariantMetricReporterTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/invariant/SerializableInvariantLogReporterTest.java
Labels: no changelog, merge when ready

#6524 Ring workflow for workload server
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/KeyedTransactionTask.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ConcurrentTransactionRunner.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/DefaultWorkflow.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingGraph.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingValidationException.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflowConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/ConcurrentTransactionRunnerTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/DefaultWorkflowTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/ring/RingGraphTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflowsTest.java
Labels: no changelog

#6518 [PDS-350703 and Others | i like trains] Part 1: Conjure Undertow, and Flattening Subresource Locators
  changelog/@unreleased/pr-6518.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/NonConjureTimelockResources.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimelockUndertowExceptionWrapper.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/LockV1Resource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimeLockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimestampManagementResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimestampResource.java
Labels: merge when ready

#6528 [PDS-350703 and Others | i like trains] Part 3: e pluribus nullum (Optionals and Nulls)
  changelog/@unreleased/pr-6528.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/LockV1Resource.java
Labels: autorelease, merge when ready

#6540 [CBT] Run build with 2xlarge
  .circleci/config.yml
  changelog/@unreleased/pr-6540.v2.yml
Labels: merge when ready

#6541 [CBT] Retry flaky tests
  atlasdb-api/build.gradle
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/CellReferenceTest.java
  atlasdb-cli/build.gradle
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/TestTimestampCommand.java
  changelog/@unreleased/pr-6541.v2.yml
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: merge when ready

#6548 [CBT] Reorganize test job parallelism
  .circleci/config.yml
  atlasdb-cassandra-integration-tests/build.gradle
  changelog/@unreleased/pr-6548.v2.yml
  scripts/circle-ci/run-circle-tests.sh
Labels: merge when ready

#6550 Use three timelocks for antithesis tests
  atlasdb-workload-server-antithesis/var/docker-compose.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  timelock-server-distribution/var/conf/timelock.distributed.yml
Labels: no changelog, merge when ready

#6552 Proper tag publishing for antithesis
  scripts/circle-ci/publish-to-antithesis.sh
Labels: no changelog, merge when ready

#6529 Workflow validators
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowAndInvariants.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowHistoryValidator.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowValidatorRunner.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/runner/AntithesisWorkflowRunner.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/runner/AntithesisWorkflowValidatorRunner.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/runner/AntithesisWorkflowRunnerTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/runner/AntithesisWorkflowValidatorRunnerTest.java
Labels: no changelog, merge when ready

#6491 Eliminate duplicate executor instrumentation
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  commons-executors/src/main/java/com/palantir/common/concurrent/PTExecutors.java
Labels: no changelog, merge when ready
