Repository palantir/atlasdb, pull requests merged in 2023-02, with the labels that each got.

#6414 SQLString skips cache lookup when not caching unregistered queries
  changelog/@unreleased/pr-6414.v2.yml
  commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java
Labels: merge when ready

#6435 Cleanup SQLString generation
  commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java
  commons-db/src/test/java/com/palantir/nexus/db/sql/SQLStringTest.java
Labels: no changelog, merge when ready

#6434 Delete timelock APIs for backup/restore
  changelog/@unreleased/pr-6434.v2.yml
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AtlasBackupResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AtlasRestoreResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/DelegatingBackupTimeLockServiceView.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimelockNamespaces.java
  timelock-impl/src/test/java/com/palantir/atlasdb/backup/AtlasBackupResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/backup/AtlasRestoreResourceTest.java
Labels: autorelease, merge when ready

#6406 [Docs] ADR 18 Part 1 - Lock Watches
  docs/source/miscellaneous/doc/adr/0018-allow-for-value-caching-with-lock-watches.md
Labels: merge when ready

#6398 Removing unused ShouldNotDeleteAndRollbackTransaction
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ShouldNotDeleteAndRollbackTransaction.java
Labels: no changelog

#6439 Bump Oracle E2E testing to 19.18
  atlasdb-ete-tests/docker-compose.oracle.yml
Labels: no changelog, merge when ready

#6438 Delete unused DisabledNamespaces code
  changelog/@unreleased/pr-6438.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/management/AllNodesDisabledNamespacesUpdaterFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClients.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/backup/AuthHeaderValidator.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/BackupTimeLockServiceView.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimeLockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimelockNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/AllNodesDisabledNamespacesUpdater.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DatabaseNamespaceLoader.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DisableNamespaceResponses.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DisabledNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/DisabledNamespacesUpdaterResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/ReEnableNamespaceResponses.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-impl/src/test/java/com/palantir/atlasdb/backup/AuthHeaderValidatorTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/TimelockNamespacesTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/AllNodesDisabledNamespacesUpdaterTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/DisabledNamespacesTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResourceTest.java
Labels: autorelease, merge when ready

#6440 Clean up remaining ABR loose ends
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/LightweightOppToken.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/TargetedSweepTables.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/ServerListConfigs.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/InternalSchemaMetadataState.java
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/InMemoryTimelockServices.java
  timelock-agent/src/main/java/com/palantir/timelock/config/RestrictedTimeLockRuntimeConfiguration.java
  timelock-agent/src/main/java/com/palantir/timelock/config/TimeLockRuntimeConfiguration.java
  timelock-agent/src/test/java/com/palantir/timelock/config/TimeLockRuntimeConfigurationTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/UpdateFailureRecord.java
Labels: no changelog, merge when ready

#6441 Retry tests in LWVIT when they flake for timelock timeouts or other reasons
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: no changelog, merge when ready

#6445 Workload service transaction store atlasdb
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/TransactionStore.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/DeleteTransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/ReadTransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/TransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/WriteTransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/witnessed/WitnessedDeleteTransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/witnessed/WitnessedReadTransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/witnessed/WitnessedTransactionAction.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/transaction/witnessed/WitnessedWriteTransactionAction.java
  atlasdb-workload-server/build.gradle
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStore.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/transaction/WitnessToActionVisitor.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/util/AtlasDbUtils.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/WitnessToActionVisitorTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/util/AtlasDbUtilsTest.java
  settings.gradle
Labels: no changelog, merge when ready

#6450 Make the message for async init not completed a lot clearer.
  atlasdb-commons/src/main/java/com/palantir/exception/NotInitializedException.java
  atlasdb-commons/src/test/java/com/palantir/exception/NotInitializedExceptionTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  changelog/@unreleased/pr-6450.v2.yml
Labels: merge when ready

#6451 Optimize CassandraService::getKnownPort
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
  changelog/@unreleased/pr-6451.v2.yml
Labels: autorelease, merge when ready

#6457 [TTS/Backup & Restore] Prevent rollout of TTS without consideration of backup and restore
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionConstants.java
Labels: no changelog, merge when ready

#6458 [PDS-336637, PDS-335142 and friends] Verify a new server list against a previously accepted topology, if one exists, by tracking the origin of new cass servers
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraServerOrigin.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  changelog/@unreleased/pr-6455.v2.yml
Labels: autorelease, merge when ready
