Repository palantir/atlasdb, pull requests merged in 2023-03, with the labels that each got.

#6461 [PDS-335555] getRange() and Friends Return Unwanted Columns From Local Writes
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  changelog/@unreleased/pr-6461.v2.yml
Labels: autorelease, merge when ready

#6459 DurableWrites invariant check
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/StructureHolder.java
  atlasdb-workload-server-api/build.gradle
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/invariant/Invariant.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/invariant/MismatchedValue.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/TableAndWorkloadCell.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/ValidationStore.java
  atlasdb-workload-server-api/src/test/java/com/palantir/atlasdb/workload/invariant/MismatchedValueTest.java
  atlasdb-workload-server/build.gradle
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/DurableWritesInvariant.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/transaction/InMemoryValidationStore.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/invariant/DurableWritesInvariantTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/InMemoryValidationStoreTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/WorkloadTestHelpers.java
  changelog/@unreleased/pr-6459.v2.yml
Labels: merge when ready

#6467 Remove slf4j javadocs link
  changelog/@unreleased/pr-6467.v2.yml
  gradle/javadoc.gradle
Labels: merge when ready

#6471 Add workload server interfaces to help modularity
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/invariant/InvariantReporter.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/IndexTable.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/IsolationLevel.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/TransactionStoreFactory.java
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowRunner.java
  atlasdb-workload-server-api/src/test/java/com/palantir/atlasdb/workload/store/IndexTableTest.java
  changelog/@unreleased/pr-6471.v2.yml
Labels: merge when ready

#6473 Use AtlasDbDependencyException when no hosts available
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RetryLimitReachedException.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-commons/src/main/java/com/palantir/exception/NotInitializedException.java
  changelog/@unreleased/pr-6473.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/InvalidAcceptorCacheKeyException.java
Labels: autorelease, merge when ready

#6474 Add getActiveNamespaces endpoint
  changelog/@unreleased/pr-6474.v2.yml
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
  timelock-server/src/suiteTest/java/com/palantir/atlasdb/timelock/MultiNodePaxosTimeLockServerIntegrationTest.java
Labels: autorelease, merge when ready

#6478 Batch hint is now marked as nullable for RangeRequest
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RangeRequest.java
Labels: no changelog, autorelease, merge when ready

#6481 Add @Nullable to (Batch)ColumnRangeSelection and the puncher store
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/BatchColumnRangeSelection.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/ColumnRangeSelection.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/KeyValueServicePuncherStore.java
Labels: no changelog, autorelease, merge when ready

#6475 [TEX] Wrap KVS service reads and track bytes read (no metrics)
  .palantir/revapi.yml
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CallbackAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ExpectationsAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingCallbackAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingExpectationsAwareTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-6475.v2.yml
Labels: autorelease, merge when ready

#6480 Add docker-compose file for workload server / antithesis testing
  atlasdb-workload-server-antithesis/Dockerfile
  atlasdb-workload-server-antithesis/build.gradle
  atlasdb-workload-server-antithesis/var/docker-compose.yml
  atlasdb-workload-server-distribution/Dockerfile
  atlasdb-workload-server-distribution/build.gradle
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.yml
  atlasdb-workload-server-distribution/var/security/keyStore.jks
  atlasdb-workload-server-distribution/var/security/trustStore.jks
  settings.gradle
Labels: no changelog, merge when ready

#6483 Add container names and use scratch image for config
  atlasdb-workload-server-antithesis/Dockerfile
  atlasdb-workload-server-antithesis/var/docker-compose.yml
Labels: no changelog, merge when ready

#6484 log durable writes violations
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/invariant/DurableWritesMetricInvariantReporter.java
Labels: no changelog, merge when ready

#6489 Since Atlas tables are append only, reserve no space for row growth on Oracle
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  changelog/@unreleased/pr-6489.v2.yml
Labels: merge when ready

#6493 Bump tritium 0.64.0
  atlasdb-commons/src/test/java/com/palantir/common/base/BatchingVisitablesTest.java
  atlasdb-dbkvs/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/OracleTableNameUnmapperTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/knowledge/KnownAbandonedTransactionsImplTest.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosRemoteClientsTest.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6497 Upgrade dependencies
  versions.lock
  versions.props
Labels: no changelog, merge when ready
