Repository palantir/atlasdb, pull requests merged in 2023-09, with the labels that each got.

#6727 Move IndexEncodingUtils to lock-api-objects
  lock-api-objects/build.gradle
  lock-api-objects/src/main/java/com/palantir/util/IndexEncodingUtils.java
  lock-api-objects/src/test/java/com/palantir/util/IndexEncodingUtilsTest.java
Labels: no changelog, autorelease, merge when ready

#6726 Add UniqueIds to generate UUIDs with fewer scalability bottlenecks
  atlasdb-api/build.gradle
  atlasdb-api/src/main/java/com/palantir/atlasdb/persistent/api/PersistentStore.java
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategy.java
  atlasdb-service/build.gradle
  atlasdb-service/src/main/java/com/palantir/atlasdb/impl/AtlasDbServiceImpl.java
  changelog/@unreleased/pr-6726.v2.yml
  lock-api-objects/build.gradle
  lock-api-objects/src/main/java/com/palantir/lock/v2/IdentifiedTimeLockRequest.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/StartTransactionRequestV4.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/WaitForLocksRequest.java
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/ConjureLockRequests.java
  lock-api/src/main/java/com/palantir/lock/client/IdentifiedLockRequest.java
  lock-api/src/main/java/com/palantir/lock/client/LeasedLockToken.java
  lock-api/src/main/java/com/palantir/lock/client/LockLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/LockTokenShare.java
  lock-api/src/main/java/com/palantir/lock/client/MultiClientTransactionStarter.java
  lock-api/src/main/java/com/palantir/lock/client/metrics/TimeLockFeedbackBackgroundTask.java
  timelock-impl/build.gradle
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/adjudicate/TimeLockClientFeedbackSink.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/AcceptorCacheKey.java
  timelock-server-benchmark-client/build.gradle
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/benchmarks/AbstractRangeScanBenchmark.java
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/benchmarks/KvsWriteBenchmark.java
  versions.lock
  versions.props
Labels: autorelease, merge when ready, 🤖 fix nits

#6720 fix annoying typo
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
Labels: no changelog, merge when ready

#6710 Fix gradle-baseline excavator
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/InterruptibleFuture.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/timestamp/InDbTimestampBoundStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-service/src/main/java/com/palantir/atlasdb/proto/fork/ForkedJsonFormat.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/StreamTest.java
  build.gradle
  commons-db/src/main/java/com/palantir/nexus/db/sql/SQLString.java
Labels: no changelog, merge when ready, 🤖 fix nits

#6736 Upgrade baseline 5.21.0
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RowColumnRangeExtractor.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/stream/AbstractGenericStreamStore.java
  atlasdb-commons/src/main/java/com/palantir/common/base/Throwables.java
  atlasdb-commons/src/main/java/com/palantir/util/JMXUtils.java
  atlasdb-commons/src/main/java/com/palantir/util/crypto/Sha256Hash.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/Containers.java
  atlasdb-container-test-utils/src/main/java/com/palantir/atlasdb/containers/ThreeNodeCassandraCluster.java
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/ete/Gradle.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManagerTest.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/backend/DockerizedDatabase.java
  build.gradle
  flake-rule/src/test/java/com/palantir/flake/example/StringSupplierTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/LockV1Resource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/SqliteNamespaceLoader.java
Labels: no changelog, merge when ready

#6739 Optimize InternalSchemaMetadataPayloadCodec serDe
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/InternalSchemaMetadataPayloadCodec.java
Labels: no changelog, merge when ready

#6709 Upgrade dependencies
  gradle/tests.gradle
  timelock-server/build.gradle
  versions.lock
  versions.props
Labels: no changelog, merge when ready, update me, 🤖 fix nits

#6746 Try to close all resources even if one throws
  changelog/@unreleased/pr-6746.v2.yml
  lock-impl/src/main/java/com/palantir/lock/impl/LockServiceImpl.java
Labels: autorelease, merge when ready

#6721 [PDS-403847] CCPI Resource Management, Part 2: AbsentHosts Not Cleaned Up On Failed Starts
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  changelog/@unreleased/pr-6721.v2.yml
Labels: autorelease, merge when ready

#6743 ConflictDetectionManager should not cache negative lookups
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManagers.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionConflictDetectionManagerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestConflictDetectionManagers.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/WrappingTestTransactionManager.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6743.v2.yml
Labels: autorelease, merge when ready

#6748 [Fix] Start running workload-server-distribution tests
  atlasdb-workload-server-distribution/build.gradle
Labels: no changelog, merge when ready

#6752 Add CacheValue::toString
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValue.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/CacheValueTests.java
  changelog/@unreleased/pr-6752.v2.yml
Labels: merge when ready

#6751 Fix: AdjustableBackgroundTask aggressively closes executor
  changelog/@unreleased/pr-6751.v2.yml
  lock-impl/src/main/java/com/palantir/lock/impl/AdjustableBackgroundTask.java
  lock-impl/src/test/java/com/palantir/lock/impl/AdjustableBackgroundTaskTest.java
Labels: autorelease, merge when ready

#6749 [PDS-417767] Prevent Atlas from running in JDK 21
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-6749.v2.yml
Labels: autorelease, merge when ready

#6754 Refresh quickly when no nodes in the pool
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  changelog/@unreleased/pr-6754.v2.yml
Labels: merge when ready

#6755 [PDS-403847] [II.IV] Topology Validator++
  .palantir/revapi.yml
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  changelog/@unreleased/pr-6755.v2.yml
Labels: autorelease, merge when ready

#6757 Update snappy to resolve CVE
  changelog/@unreleased/pr-6757.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready
