Repository palantir/atlasdb, pull requests merged in 2023-12, with the labels that each got.

#6880 flake-rule
  flake-rule/build.gradle
  flake-rule/src/main/java/com/palantir/flake/FlakeRetryingRule.java
  flake-rule/src/main/java/com/palantir/flake/ShouldRetry.java
  flake-rule/src/test/java/com/palantir/flake/BeforeClassFlakeTest.java
  flake-rule/src/test/java/com/palantir/flake/FlakeRetryingRuleClassAnnotationTest.java
  flake-rule/src/test/java/com/palantir/flake/FlakeRetryingRuleTest.java
  flake-rule/src/test/java/com/palantir/flake/example/BeforeAndAfterTest.java
  flake-rule/src/test/java/com/palantir/flake/example/StringSupplierTest.java
  flake-rule/src/test/java/com/palantir/flake/fail/ExpectedFailure.java
  flake-rule/src/test/java/com/palantir/flake/fail/ExpectedFailureRule.java
  settings.gradle
  timelock-server/build.gradle
  versions.lock
Labels: no changelog, merge when ready

#6883 timelock-server
  timelock-server/build.gradle
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedTimestampSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/BatchedTimestampSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/DbTimelockSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/MultiLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/MultiLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/NonBatchedTimestampSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/NonBatchedTimestampSingleLeaderMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AbstractAsyncTimelockServiceIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceTransactionIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/IsolatedPaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchEventIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchIntegrationTestUtilities.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/PaxosTimeLockServerIntegrationTest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/TimeLockServerDownIntegrationTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/AbstractPaxosStressTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/BatchedPaxosStressTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/BatchedTimestampPaxosStressTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/DbTimeLockSingleLeaderPaxosStressTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/MultiLeaderPaxosStressTest.java
  timelock-server/src/stressTest/java/com/palantir/atlasdb/timelock/stress/NonBatchedTimestampPaxosStressTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/DbKvsRule.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClientsV2.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolder.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TemporaryConfigurationHolderV2.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockClusterV2.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockServerV2.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolderV2.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockTestUtilsV2.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/ParameterInjector.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/util/TestProxiesV2.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready

#6889 [PDS-435038] revert
  atlasdb-commons/src/main/java/com/palantir/leader/SuspectedNotCurrentLeaderException.java
  changelog/@unreleased/pr-6889.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease, merge when ready

#6870 Added strongly typed exceptions for cassandra client pool validation
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-commons/src/main/java/com/palantir/exception/CassandraAllHostsUnresponsiveException.java
  atlasdb-commons/src/main/java/com/palantir/exception/CassandraInvalidPartitionerException.java
Labels: no changelog, autorelease, merge when ready, 🤖 fix nits

#6853 [PDS-444232] Rethrow SuspectedNotCurrentLeaderException From PersistentTimestampServices
  atlasdb-commons/src/main/java/com/palantir/leader/SuspectedNotCurrentLeaderException.java
  changelog/@unreleased/pr-6853.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
  timestamp-impl/src/main/java/com/palantir/timestamp/TimestampAllocationFailures.java
  timestamp-impl/src/test/java/com/palantir/timestamp/PersistentTimestampServiceTests.java
  timestamp-impl/src/test/java/com/palantir/timestamp/TimestampAllocationFailuresTest.java
Labels: autorelease

#6898 remove remaining junit4 deps
  atlasdb-console/build.gradle
  atlasdb-console/src/test/groovy/com/palantir/atlasdb/console/groovy/AtlasConsoleServiceWrapperTest.groovy
  atlasdb-console/src/test/groovy/com/palantir/atlasdb/console/groovy/TableTest.groovy
  versions.lock
Labels: no changelog, merge when ready
