Repository palantir/atlasdb, pull requests merged in 2023-08, with the labels that each got.

#6691 bump commons-text to 1.10.0
  versions.lock
  versions.props
Labels: no changelog

#6681 [Antithesis] Part 12: too much experimentation
  atlasdb-ete-tests/src/test/java/com/palantir/atlasdb/ete/suites/MultiClientWithTimelockAndCassandraTestSuite.java
Labels: no changelog, merge when ready

#6671 [LWMeta] Pass Metadata through SnapshotTransaction
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/ValueAndChangeMetadata.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LocksAndMetadata.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/LocalWriteBuffer.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/LocalWriteBufferTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CachingTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6671.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/LockRequest.java
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchEventIntegrationTest.java
Labels: merge when ready

#6674 multi-node embedded is not supported
  atlasdb-api/src/main/java/com/palantir/atlasdb/config/LeaderConfig.java
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultLockAndTimestampServiceFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/Leaders.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/LocalOrRemoteProxy.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/SinglePingableLeaderTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/TransactionManagersAsyncInitializationTest.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/LeadersTest.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-6674.v2.yml
Labels: autorelease, merge when ready

#6698 fix: fix TransactionManagers ABI break
  .palantir/revapi.yml
  atlasdb-config/build.gradle
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-6698.v2.yml
Labels: autorelease, merge when ready

#6701 use default revapi config
  atlasdb-config/build.gradle
Labels: no changelog, merge when ready

#6669 [LWMeta] Add metadata to expectations metrics
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/ExpectationsData.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/expectations/TransactionWriteMetadataInfo.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ExpectationsAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingExpectationsAwareTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/LocalWriteBuffer.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/LockAndChangeMetadataCount.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/metrics/expectations.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ExpectationsMetricsReportingTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/LocalWriteBufferTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6669.v2.yml
Labels: merge when ready

#6700 ignore LockWatchValueIT#valueStressTest
  timelock-server/src/integTest/java/com/palantir/atlasdb/timelock/LockWatchValueIntegrationTest.java
Labels: no changelog, merge when ready

#6703 Refactor bank balance to allow errors to be consumed rather than just logged
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/bank/BankBalanceWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/bank/BankBalanceWorkflowsTest.java
Labels: no changelog, merge when ready

#6702 Refactor ring test to allow external error detection
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingGraph.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingValidationException.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/ring/RingGraphTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflowsTest.java
Labels: no changelog, merge when ready

#6704 create an abstract class for stoppable transaction tasks
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/StoppableKeyedTransactionTask.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/bank/BankBalanceWorkflows.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/ring/RingWorkflows.java
Labels: no changelog, merge when ready

#6711 throw only once when leadership is lost
  changelog/@unreleased/pr-6711.v2.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStoreTest.java
Labels: autorelease, merge when ready

#6705 Make transient rows validate after N iterations
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflowConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflowsTest.java
Labels: no changelog, merge when ready

#6655 feature: Expose API to let client define number of expected values in a Get.
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/NoOpTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ReadOnlyTransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/annotations/ReviewedRestrictedApiUsage.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/exceptions/MoreCellsPresentThanExpectedException.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-commons/src/main/java/com/palantir/util/result/Err.java
  atlasdb-commons/src/main/java/com/palantir/util/result/Ok.java
  atlasdb-commons/src/main/java/com/palantir/util/result/Result.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCache.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/CellCountValidator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/TransactionScopedCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/ValidatingTransactionScopedCacheTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/CellCountValidatorTest.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionTest.java
  changelog/@unreleased/pr-6655.v2.yml
Labels: autorelease, merge when ready

#6716 [PDS-403847] CCPI Resource Management, Part 1: AsyncInitializer Resource Leak
  atlasdb-commons/src/main/java/com/palantir/async/initializer/AsyncInitializer.java
  atlasdb-commons/src/test/java/com/palantir/async/initializer/AsyncInitializerTest.java
  changelog/@unreleased/pr-6716.v2.yml
Labels: autorelease, merge when ready
