Repository palantir/atlasdb, pull requests merged in 2024-03, with the labels that each got.

#6985 Provide Undertow exclusive TimeLockAgent#create
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: no changelog, autorelease, merge when ready

#7010 Add observability to TransactionKeyValueServiceManagerFactory.
  .palantir/revapi.yml
  atlasdb-api/build.gradle
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/TransactionKeyValueServiceManagerFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
Labels: no changelog, merge when ready

#7012 Pass internal KVS to timelock consistency checker.
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
Labels: no changelog

#7013 Async initialization for TransactionKeyValueServiceManager.
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/TransactionKeyValueServiceManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingTransactionKeyValueServiceManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
Labels: no changelog, merge when ready

#7014 Wire internal KVS to TargetedSweeper.
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKvsSerializableTransactionTest.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractTargetedSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
Labels: no changelog, autorelease, merge when ready

#7002 improvement: Resolve flakes in AMNPTLSIT (AbstractMultiNodePaxosTimeLockServerIntegrationTest)
  changelog/@unreleased/pr-7002.v2.yml
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TestableTimelockCluster.java
Labels: no changelog

#6943 Log hostsTried in retry limit exception
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RetryLimitReachedException.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/RetryLimitReachedExceptionTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraRequestExceptionHandler.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RetryableCassandraRequest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTableTest.java
Labels: no changelog, autorelease, merge when ready

#7021 [KeyValueSnapshotReader Phase I] Part 3: TransactionKeyValueService No Longer Supports Synchronous Get
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/TransactionKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingTransactionKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/KeyValueServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueServiceImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueServiceForwardingTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueServiceReadInfoTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/WrapperWithTracker.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AsyncSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SyncSnapshotTransactionTest.java
Labels: no changelog, merge when ready

#7019 [Antithesis] Randomise number of threads used in workflows
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  changelog/@unreleased/pr-7019.v2.yml
Labels: merge when ready

#7020 [Antithesis] Multiple Busy Cell Workflow for Sweep
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerInstallConfiguration.java
  atlasdb-workload-server-distribution/src/test/resources/workload-server.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.yml
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/MultipleBusyCellWorkflowConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/MultipleBusyCellWorkflows.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/workflow/MultipleBusyCellWorkflowsTest.java
Labels: no changelog, merge when ready

#7030 Pass internal kvs to TransactionManagers#createClearsTable.
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
Labels: no changelog, autorelease, merge when ready

#7034 improvement: bump postgresql for CVE-2024-1597
  changelog/@unreleased/pr-7034.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#7016 [KeyValueSnapshotReader Phase I] Part 1: Extract Commit Timestamp Loading
  atlasdb-api/build.gradle
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/CommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/CommitTimestampLoaderFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/DefaultCommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/DefaultCommitTimestampLoaderTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
Labels: no changelog

#7041 Revert protobuf upgrade
  gradle/protobuf.gradle
  versions.lock
  versions.props
Labels: no changelog, autorelease, merge when ready

#7036 improvement: Fix flakiness on CassandraClientPoolTest resilientToRollingRestarts method
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  changelog/@unreleased/pr-7036.v2.yml
Labels: merge when ready

#7017 [KeyValueSnapshotReader Phase I] Part 2: ReadValidationCommitTimestampLoader
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/CommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/DefaultCommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadValidationCommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/DefaultCommitTimestampLoaderTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ReadValidationCommitTimestampLoaderTest.java
Labels: no changelog

#7024 [KeyValueSnapshotReader Phase I] Part 4: KeyValueSnapshotEventRecorder
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/metrics/KeyValueSnapshotMetricRecorder.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/DefaultKeyValueSnapshotMetricRecorder.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/metrics/SnapshotTransactionMetricFactory.java
Labels: no changelog

#7026 [KeyValueSnapshotReader Phase I] Part 5: ImmutableTimestampLockManager
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ImmutableTimestampLockManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultLockValidityChecker.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/LockValidityChecker.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ImmutableTimestampLockManagerTest.java
Labels: no changelog

#7027 [KeyValueSnapshotReader Phase I] Part 6: PreCommitRequirementValidator
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/precommit/PreCommitRequirementValidator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultPreCommitRequirementValidator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultPreCommitRequirementValidatorTest.java
Labels: no changelog

#7047 [Workload Server] move workflow creation out of distribution module
  atlasdb-workload-server-distribution/build.gradle
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/DefaultWorkflowExecutorFactory.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/config/WorkflowExecutionConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerInstallConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerRuntimeConfiguration.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowExecutorFactory.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowFactory.java
  changelog/@unreleased/pr-7047.v2.yml
Labels: autorelease, merge when ready

#7046 Remove ordinal calls
  atlasdb-client/src/integrationInput/java/com/palantir/atlasdb/table/description/generated/AllValueTypesTestTable.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/ApiTestSchema.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/compact/BackgroundCompactor.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/compact/CompactionOutcomeMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcome.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/SweepOutcomeMetrics.java
Labels: no changelog, merge when ready

#7051 [Caching] Check Validity of TransactionKeyValueService Before Commit
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/TransactionKeyValueService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/exceptions/SafeTransactionFailedRetriableException.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/transaction/api/exceptions/SafeTransactionFailedRetriableExceptionTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingTransactionKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/InvalidatableTransactionKeyValueService.java
Labels: no changelog, autorelease, merge when ready

#7052 Revert "Excavator: Update policy-bot config"
  .policy.yml
Labels: no changelog

#7040 [KeyValueSnapshotReader Phase I] Part 7: ReadSnapshotValidator
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultReadSnapshotValidator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/ReadSnapshotValidator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultReadSnapshotValidatorTest.java
Labels: no changelog

#7055 [KeyValueSnapshotReader Phase I] Part 8: ReadSentinelHandler... and fixing a subtle 🐛
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/OrphanedSentinelDeleter.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/DefaultOrphanedSentinelDeleter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadSentinelHandler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ReadSentinelHandlerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/UncommittedValueType.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ThrowingSweepStrategyManager.java
  changelog/@unreleased/pr-7055.v2.yml
Labels: autorelease

#7066 [Antithesis] Add generated version.txt file to docker images
  gradle/docker.gradle
Labels: no changelog, merge when ready

#7067 templatized distributed timelock config
  atlasdb-workload-server-antithesis/var/docker-compose.yml
  timelock-server-distribution/var/conf/timelock.distributed.yml
Labels: no changelog, autorelease, merge when ready
