Repository palantir/atlasdb, pull requests merged in 2024-11, with the labels that each got.

#7415 Fix key value service annotation/comments
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
Labels: no changelog, merge when ready

#7418 Add explicit hints
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleQueryFactory.java
  changelog/@unreleased/pr-7418.v2.yml
Labels: autorelease, merge when ready

#7420 Migrate squareup javapoet to Palantir javapoet
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/Renderers.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableClassRendererV2.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/render/TableFactoryRenderer.java
  atlasdb-processors/build.gradle
  atlasdb-processors/src/main/java/com/palantir/processors/AutoDelegateProcessor.java
  atlasdb-processors/src/main/java/com/palantir/processors/ProcessorUtils.java
  changelog/@unreleased/pr-7420.v2.yml
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#7423 [ASTS] improvement: Initial buckets for sweeping should include strategy in heuristic
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSweepStateCoordinator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSweepStateCoordinatorTest.java
Labels: no changelog, merge when ready

#7425 [ASTS] Reduce log noise
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DynamicTaskScheduler.java
Labels: no changelog, merge when ready

#7427 Remove `TimestampLeaseAwareTransactionManger`
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TimestampLeaseAwareTransaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TimestampLeaseAwareTransactionManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-7427.v2.yml
Labels: autorelease, merge when ready

#7405 bring concurrent range scans limit down to 100 by default
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraClientRateLimitingConfig.java
  changelog/@unreleased/pr-7405.v2.yml
Labels: merge when ready

#7428 Unblock dropwizard and test infra dependencies
  atlasdb-cassandra/build.gradle
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteConfiguration.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerConfiguration.java
  lock-impl/build.gradle
  lock-impl/src/test/java/com/palantir/lock/impl/LockServiceImplTest.java
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/TimelockBenchmarkClientLauncher.java
  timelock-server-benchmark-client/src/main/java/com/palantir/atlasdb/timelock/benchmarks/config/TimelockBenchmarkClientConfig.java
  timelock-server-benchmark-cluster/src/main/java/com/palantir/atlasdb/timelock/benchmarks/server/TimelockBenchmarkServerLauncher.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractSingleLeaderMultiNodePaxosTimeLockIntegrationTest.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/config/CombinedTimeLockServerConfiguration.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/logging/NonBlockingFileAppenderFactory.java
  versions.lock
  versions.props
Labels: no changelog, merge when ready, 🤖 fix nits

#7434 Propagate exception on deleteAllTimestamps failure within sweep
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueDeleter.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepQueueDeleterTest.java
Labels: no changelog, merge when ready

#7433 Bump jdbc driver for oracle+postgres/oracle image for testing
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
  changelog/@unreleased/pr-7433.v2.yml
  versions.lock
  versions.props
Labels: merge when ready, 🤖 fix nits

#7422 [ASTS] Fix: ensure forward progress even if a single window does not have enough timestamps
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculatorTest.java
Labels: no changelog, merge when ready

#7443 fix docstring for `TransactionService#markInProgress`
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/service/TransactionService.java
Labels: no changelog, merge when ready
