Repository palantir/atlasdb, pull requests merged in 2024-02, with the labels that each got.

#6931 Avoid reflection when rethrowing exceptions
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategy.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategyTest.java
  atlasdb-commons/src/main/java/com/palantir/common/proxy/InterruptibleProxy.java
  leader-election-impl/src/main/java/com/palantir/paxos/PaxosStateLogImpl.java
  leader-election-impl/src/main/java/com/palantir/paxos/SingleLeaderPinger.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/GetSuspectedLeaderWithUuid.java
Labels: no changelog, autorelease, merge when ready

#6945 fix: Remove unnecessary BiMap from RedirectRetryTargeter
  atlasdb-config/src/main/java/com/palantir/atlasdb/http/RedirectRetryTargeter.java
  changelog/@unreleased/pr-6945.v2.yml
Labels: autorelease, merge when ready

#6951 fix: Forward timestamp on Antithesis workload server to use txn3
  atlasdb-workload-server-antithesis/src/test/java/AntithesisDockerTest.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
  changelog/@unreleased/pr-6951.v2.yml
Labels: merge when ready

#6950 fix: Start Antithesis fuzzer before selecting workflow
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/workflow/WorkflowValidatorRunner.java
  atlasdb-workload-server-distribution/build.gradle
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/logging/LoggingUtils.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/runner/AntithesisWorkflowValidatorRunner.java
  changelog/@unreleased/pr-6950.v2.yml
Labels: autorelease, merge when ready

#6946 feature: Allow configurable table mapper caching
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/TableMappingCacheConfiguration.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingServiceTest.java
  changelog/@unreleased/pr-6946.v2.yml
Labels: autorelease

#6886 add debug/trace logging for table creation/deletion
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleDdlTable.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresDdlTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingService.java
Labels: no changelog, merge when ready

#6960 [JUnit5] Postgres ETE tests flup
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/DbTimestampStoreInvalidatorCreationTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresEmbeddedDbTimestampBoundStoreTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresMultiSeriesDbTimestampBoundStoreTest.java
Labels: no changelog, merge when ready

#6962 Refactor DeleteExecutor.
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/DefaultDeleteExecutor.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/DeleteExecutor.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
Labels: no changelog, merge when ready

#6974 Fix flakiness on poisoningMultipleTimesIsAllowed test
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/DbKvsPostgresInvalidationRunnerTest.java
Labels: no changelog, merge when ready

#6976 Bump JVM heap for test Suite 3 to avoid Flakiness
  scripts/circle-ci/run-circle-tests.sh
Labels: no changelog, merge when ready

#6944 Add conjure-undertow annotations to (Batch)PingableLeader
  leader-election-api/build.gradle
  leader-election-api/src/main/java/com/palantir/leader/PingableLeader.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-api/build.gradle
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/BatchPingableLeader.java
Labels: no changelog, merge when ready

#6952 Add conjure-undertow annotations to LeaderLearnerResource
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderLearnerResource.java
Labels: no changelog, merge when ready

#6959 Flatten TimestampPaxosResource and add Undertow support
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResourcesFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimestampPaxosAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimestampPaxosLearnerResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/TimestampPaxosResource.java
Labels: no changelog, merge when ready

#6975 Flatten UseCaseAwareBatchPaxosResource and register it on Undertow
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosResources.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosAcceptorResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosComponents.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/UseCaseAwareBatchPaxosLearnerResource.java
Labels: no changelog, merge when ready

#6986 [CONTENTIOUS 🌶️] feature: Standalone Lock Factory
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultLockAndTimestampServiceFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/LockServices.java
  changelog/@unreleased/pr-6986.v2.yml
Labels: autorelease

#6984 TransactionKeyValueServiceFactory and service loading.
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/KeyValueServiceManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/TransactionKeyValueServiceConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/TransactionKeyValueServiceManagerFactory.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/TransactionKeyValueServiceRuntimeConfig.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbServiceDiscovery.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultKeyValueServiceManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/CoordinationServices.java
Labels: no changelog, merge when ready

#6999 FLUP renames from #6980.
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/KeyValueServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ColumnRangeBatchProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/RowRangeBatchProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueServiceImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/GetRowsColumnRangeIteratorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueServiceForwardingTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingTransactionKeyValueServiceReadInfoTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/WrapperWithTracker.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SyncSnapshotTransactionTest.java
Labels: no changelog, merge when ready

#6993 fix: Forcibly conclude transactions in antithesis workload server before performing durable write invariant validation
  atlasdb-workload-server-api/src/main/java/com/palantir/atlasdb/workload/store/ReadableTransactionStore.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionConcluder.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStore.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/ReadOnlyTransactionStore.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/transaction/witnessed/OnlyCommittedWitnessedTransactionVisitor.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionConcluderTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/witnessed/OnlyCommittedWitnessedTransactionVisitorTest.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/transaction/witnessed/WitnessedTransactionsTest.java
  changelog/@unreleased/pr-6993.v2.yml
Labels: autorelease

#6989 Refactor DdlManager.
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/DdlManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/TransactionKeyValueServiceManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/TransactionKeyValueServiceManagerFactory.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingDdlManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingTransactionKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingTransactionKeyValueServiceManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schemas.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/table/description/SchemasTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagersInitializer.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/GetRowsColumnRangeIteratorTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableTasksTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
Labels: no changelog, autorelease, merge when ready

#6972 Do not use javax UriBuilder in PaxosRemotingUtils
  timelock-agent/src/main/java/com/palantir/timelock/paxos/PaxosRemotingUtils.java
Labels: no changelog, autorelease, merge when ready
