Repository palantir/atlasdb, pull requests merged in 2024-05, with the labels that each got.

#7106 Adding more logs to transaction lifecycle of Antithesis Workload Server
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbInteractiveTransaction.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStore.java
Labels: no changelog, autorelease, merge when ready

#7111 Allow disabling validating locks on reads on a per transaction basis
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultReadSnapshotValidator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/ReadSnapshotValidator.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  changelog/@unreleased/pr-7111.v2.yml
Labels: autorelease, merge when ready

#7116 Fix docs build by upgrading python and dependencies
  changelog/@unreleased/pr-7116.v2.yml
  scripts/circle-ci/run-circle-tests.sh
Labels: autorelease, merge when ready

#7109 Report conflicting table as arg in transaction conflict exceptions
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionConflictException.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionSerializableConflictException.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadValidationCommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog, autorelease, merge when ready

#7114 Add args to config validation errors
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraReloadableKeyValueServiceRuntimeConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraTracingConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/TimeLockClientConfig.java
Labels: no changelog, autorelease, merge when ready

#7121 [Antithesis] Transient Rows: Make it clearer where violations are found
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflows.java
Labels: no changelog, merge when ready

#7123 Disable dependency-upgrader for Goethe
  versions.props
Labels: no changelog, merge when ready

#7112 CassandraKeyValueServiceImpl uses CellLoader::flattenReadOnlyLists
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-7112.v2.yml
Labels: merge when ready

#6828 Immediately invalidate on lost leadership
  changelog/@unreleased/pr-6828.v2.yml
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipCoordinator.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
Labels: autorelease, merge when ready

#7105 Test and optimize Sha256Hash.toString()
  atlasdb-commons/src/main/java/com/palantir/util/crypto/Sha256Hash.java
  atlasdb-commons/src/test/java/com/palantir/util/crypto/Sha256HashTest.java
  changelog/@unreleased/pr-7105.v2.yml
Labels: merge when ready

#7117 Reduce startup contention in Timelock ConcurrentHashMaps
  atlasdb-commons/src/main/java/com/palantir/common/concurrent/ConcurrentMaps.java
  atlasdb-commons/src/test/java/com/palantir/common/concurrent/ConcurrentMapsTest.java
  changelog/@unreleased/pr-7117.v2.yml
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeaderElectionServiceFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimelockNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/LocalPaxosComponents.java
Labels: autorelease, merge when ready

#7129 Revert "Immediately invalidate on lost leadership"
  leader-election-impl/src/main/java/com/palantir/leader/proxy/AwaitingLeadershipProxy.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipCoordinator.java
  leader-election-impl/src/main/java/com/palantir/leader/proxy/LeadershipStateManager.java
  leader-election-impl/src/test/java/com/palantir/leader/proxy/AwaitingLeadershipProxyTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/paxos/PaxosTimestampBoundStore.java
Labels: no changelog, merge when ready

#7125 Tombstone Tracing
  atlasdb-config/src/test/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfigDeserializationTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueDeleter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
Labels: no changelog, merge when ready

#7130 Add Value.Default to new sweep config
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
Labels: no changelog, autorelease, merge when ready
