Repository palantir/atlasdb, pull requests merged in 2024-10, with the labels that each got.

#7288 [ASTS] Foreground Task II: SingleBucketSweepTaskIntegrationTest
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueDeleter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueReader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueWriter.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/SingleBucketSweepTaskIntegrationTest.java
Labels: no changelog, merge when ready

#7310 Fix semantic merge conflict on develop
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTaskTest.java
Labels: no changelog, merge when ready

#7300 feat(bucket-assigner): Persisters for the various value types
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/TimestampRange.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketStateAndIdentifier.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/ObjectPersister.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketIdentifierPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketStateAndIdentifierPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/ObjectPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/TimestampRangePersisterTest.java
Labels: no changelog, merge when ready

#7309 TransactionManagers#createInMemory uses synchronous unlocker.
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  changelog/@unreleased/pr-7309.v2.yml
Labels: autorelease, merge when ready

#7303 [ASTS] clamp to boundaries
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculatorTest.java
Labels: no changelog, merge when ready

#7311 [ASTS] Bucket tables: Key Persisters
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepAssignedBucketStoreKeyPersister.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/DefaultBucketKeySerializer.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepAssignedBucketStoreKeyPersisterTest.java
Labels: no changelog, merge when ready

#7307 rename TransactionKeyValueService to DataKeyValueService
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/DataKeyValueService.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/DataKeyValueServiceManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/DataKeyValueServiceConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/DataKeyValueServiceManagerFactory.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/spi/DataKeyValueServiceRuntimeConfig.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/snapshot/KeyValueSnapshotReaderManagerFactory.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingDataKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingDataKeyValueServiceManager.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/config/AtlasDbRuntimeConfig.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbServiceDiscovery.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagersInitializer.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/CoordinationServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ColumnRangeBatchProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadSentinelHandler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/RowRangeBatchProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingDataKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingDataKeyValueServiceImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/snapshot/DefaultKeyValueSnapshotReader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/snapshot/DefaultKeyValueSnapshotReaderManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/GetRowsColumnRangeIteratorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ReadSentinelHandlerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingDataKeyValueServiceForwardingTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/expectations/TrackingDataKeyValueServiceReadInfoTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableTasksTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/FakeDataKeyValueServiceManager.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/InvalidatableDataKeyValueService.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TestKeyValueSnapshotReaderManagers.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/@unreleased/pr-7307.v2.yml
Labels: autorelease, merge when ready

#7312 [ASTS] Sweep Bucket Records Table + Assigner usage
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssigner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketRecordsTable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssignerTest.java
Labels: no changelog, merge when ready

#7197 [ASTS] Preliminaries I: deleteFromAtomicTable
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/KeyValueService.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTimestampUtils.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CqlUtilities.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/cas/CheckAndSetQueries.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/cas/SinglePartitionAtomicTableCellDeleter.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CqlUtilitiesTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DualWriteKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/ProfilingKeyValueService.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueService.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/keyvalue/impl/TracingKeyValueServiceTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableRemappingKeyValueService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/TableSplittingKeyValueService.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/AbstractKeyValueServiceTest.java
  changelog/@unreleased/pr-7197.v2.yml
Labels: merge when ready

#7315 fix antithesis trigger
  .circleci/config.yml
  scripts/circle-ci/trigger-antithesis-simulation.sh
Labels: no changelog, merge when ready

#7324 [Named min timestamp leases] Client API
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/InstrumentedTimelockService.java
  lock-api-objects/src/main/java/com/palantir/lock/annotations/ReviewedRestrictedApiUsage.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/AcquireNamedMinTimestampLeaseResult.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  lock-api/src/main/java/com/palantir/lock/client/UnreliableTimeLockService.java
  lock-impl/src/main/java/com/palantir/lock/impl/LegacyTimelockService.java
Labels: no changelog, merge when ready, 🤖 fix nits

#7330 [Named min timestamp leases] Extract exclusive lock collection to its own class
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/ExclusiveLockCollection.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockCollection.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/LockCollectionTest.java
Labels: no changelog, merge when ready, 🤖 fix nits

#7326 Fix ClassInitializationDeadlock error and bump gradle-baseline-java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TargetedSweepMetadata.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/api/StoredWriteReference.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/sweep/queue/id/SweepTableIdentifier.java
  build.gradle
  changelog/@unreleased/pr-7326.v2.yml
Labels: autorelease, merge when ready

#7314 [ASTS] Foreground Task Part IV: Decoupling Reader Timestamps
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTask.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepBatchAccumulator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueReader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableTimestamps.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTaskTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/SingleBucketSweepTaskIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepBatchAccumulatorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/SweepableCellsTest.java
Labels: no changelog

#7323 [ASTS] Consistent Ordering Object Mapper
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/ConsistentOrderingObjectMappers.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/ObjectPersister.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/DefaultBucketProgressStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketIdentifierPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketStateAndIdentifierPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/ConsistentOrderingObjectMappersTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/ObjectPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepAssignedBucketStoreKeyPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/TimestampRangePersisterTest.java
Labels: no changelog, merge when ready

#7350 Remove sverma30 from PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no changelog, merge when ready

#7346 [ASTS] Bucket Assigner Metrics
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
Labels: merge when ready

#7331 [Named min timestamp leases] Move `ImmutableTimestampTracker` usage to `LockCollection`
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockManager.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceEteTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/AsyncLockServiceTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/LockCollectionTest.java
Labels: no changelog, merge when ready

#7322 Call SnapshotTransaction#close() on OpenTransaction codepath
  .java-version
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CallbackAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingCallbackAwareTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ThreadSafeCloser.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ThreadSafeCloserTest.java
Labels: merge when ready

#7341 [Named min timestamp leases] Server API skeletons
  timelock-api/build.gradle
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-api/src/main/java/com/palantir/atlasdb/timelock/api/TimestampLeaseName.java
  timelock-api/src/test/java/com/palantir/atlasdb/timelock/api/TimestampLeaseNameTest.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
Labels: no changelog, merge when ready

#7342 [Named min timestamp leases] Wire server API calls
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceFactory.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureLockWatchDiagnosticsResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureLockWatchingResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/RemotingMultiClientTimestampLeaseServiceAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/RemotingTimestampLeaseServiceAdapter.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
Labels: no changelog, merge when ready

#7333 [Named min timestamp leases] Generify timestamp trackers
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/ExclusiveLock.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockManager.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampLock.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampLockCollection.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampTracker.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampTrackerImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/util/LoggableIllegalStateException.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampLockCollectionTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampLockTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampTrackerTest.java
  timelock-server/src/test/java/com/palantir/atlasdb/timelock/lock/ImmutableTimestampTrackerTest.java
Labels: no changelog, merge when ready, 🤖 fix nits

#7317 [ASTS] Implementation of SweepBucketAssignerStateMachineTable
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketAssignerStateMachineTable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssignerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStoreTest.java
Labels: no changelog, merge when ready

#7349 [Named min timestamp leases] Async timelock service implementation
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImplTest.java
Labels: no changelog, merge when ready

#7318 [ASTS] Implementation of SweepBucketPointerTable
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStoreTest.java
Labels: no changelog, merge when ready

#7319 [ASTS] Implementation of SweepBucketsTable
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStoreTest.java
Labels: no changelog, merge when ready

#7320 [ASTS] Implementation of SweepBucketRecordsTable
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStoreTest.java
Labels: no changelog, merge when ready

#7354 [ASTS] New SweepableBucketRetriever
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSweepableBucketRetriever.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSweepableBucketRetrieverTest.java
Labels: no changelog, merge when ready

#7357 [ASTS] Targeted Sweeper refactor: Part 1
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedStrategySpecificBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
Labels: no changelog, merge when ready

#7347 [ASTS] Exclusive task primitive
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DynamicTaskScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ExclusiveTask.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DynamicTaskSchedulerTest.java
Labels: no changelog, merge when ready

#7356 [ASTS] Foreground task selects correct timestamp
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTask.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTaskTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/SingleBucketSweepTaskIntegrationTest.java
Labels: no changelog, merge when ready

#7358 [ASTS] Targeted Sweeper refactor part 2: splitting out the logic for getting number of shards
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdater.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/NumberOfShardsProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedStrategySpecificBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdaterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/NumberOfShardsProviderTest.java
Labels: no changelog, merge when ready, 🤖 fix nits

#7359 [ASTS] Targeted Sweeper Part 3: Split out resetting
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/DefaultSweepProgressResetter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepProgressResetter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/DefaultSweepProgressResetterTest.java
Labels: no changelog, merge when ready

#7363 [ASTS] Targeted Sweeper Part 4: Separating out the single batch sweeper
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/DefaultSingleBatchSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedStrategySpecificBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SingleBatchSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
Labels: no changelog, merge when ready

#7364 [ASTS] Targeted Sweeper Part 5: Separating the queue from the sweeper
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/DelegatingMultiTableSweepQueueWriter.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/DelegatingMultiTableSweepQueueWriterTest.java
Labels: no changelog, merge when ready

#7365 [ASTS] Targeted Sweeper Part 6: Split out the SweepQueueFactory
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKvsSerializableTransactionTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueComponents.java
Labels: no changelog, merge when ready

#7370 [ASTS] no timestamp record throws NoSuchElementException
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraDefaultSweepAssignedBucketStoreTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/DbKvsPostgresDefaultSweepAssignedBucketStoreTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketRecordsTable.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/AbstractDefaultSweepAssignedBucketStoreTest.java
Labels: no changelog, merge when ready

#7304 [ASTS] Background Task I: The Probe
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultShardProgressUpdater.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ShardProgressUpdater.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueCleaner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueProgressUpdater.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultShardProgressUpdaterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTaskTest.java
Labels: no changelog, merge when ready

#7373 [ASTS] Config
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/AutoScalingTargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepInstallConfig.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
Labels: no changelog, merge when ready

#7366 [ASTS] Targeted Sweep Part 7: Deleting Sweep Queue
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKvsSerializableTransactionTest.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTargetedSweepIntegrationTest.java
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/todo/TodoClient.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/DefaultBucketProgressStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/DelegatingMultiTableSweepQueueWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/MultiTableSweepQueueWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedStrategySpecificBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueue.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractTargetedSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweepTest.java
Labels: no changelog, merge when ready

#7367 [ASTS] Initial bootstrap task
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/InitialBucketAssignerStateMachineBootstrapTask.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketAssignerStateMachineTable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/InitialBucketAssignerStateMachineBootstrapTaskTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssignerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/AbstractDefaultSweepAssignedBucketStoreTest.java
Labels: merge when ready

#7376 [ASTS] ASTS background sweeper impl
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/BucketBasedTargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultCandidateSweepableBucketRetriever.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssigner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssignerTest.java
Labels: no changelog, merge when ready

#7377 [ASTS] Add puncherstore as argument to targeted sweeper
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/cleaner/DefaultCleanerBuilder.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
Labels: no changelog, merge when ready

#7378 [ASTS] Background impl switcher
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/BackgroundTargetedSweeperFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssigner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/locks/Lockable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/locks/LockableFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/ShardedBackgroundSweepScheduler.java
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
Labels: no changelog, merge when ready

#7379 [ASTS] Wiring up ASTS to be enabled
  atlasdb-cli/src/test/java/com/palantir/atlasdb/cli/command/KeyValueServiceMigratorsTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-ete-tests/build.gradle
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/AtlasDbEteServer.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/BackgroundTargetedSweeperFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/DefaultSweepProgressResetter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/NumberOfShardsProvider.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepProgressResetter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/NumberOfShardsProviderTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/AbstractTargetedSweepTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/SweepTestUtils.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweepTest.java
Labels: no changelog, merge when ready

#7385 [Named min timestamp Leases] Acquire single lease per transaction-shaped batch
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/RemotingMultiClientTimestampLeaseServiceAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/RemotingTimestampLeaseServiceAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
Labels: no changelog, merge when ready

#7388 [Named min timestamp leases] Conjure timestamp range long supplier
  lock-api/src/main/java/com/palantir/lock/ConjureTimestampRangeTimestampSupplier.java
  lock-api/src/test/java/com/palantir/lock/ConjureTimestampRangeTimestampSupplierTest.java
Labels: merge when ready

#7352 Refactor LockManager.
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/precommit/PreCommitRequirementValidator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionLocksManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultPreCommitRequirementValidator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultReadSnapshotValidator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionLocksManagerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultPreCommitRequirementValidatorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/precommit/DefaultReadSnapshotValidatorTest.java
  changelog/@unreleased/pr-7352.v2.yml
Labels: merge when ready

#7389 [Named min timestamp leases] Limiting long supplier
  lock-api/src/main/java/com/palantir/lock/LimitingLongSupplier.java
  lock-api/src/test/java/com/palantir/lock/LimitingLongSupplierTest.java
Labels: no changelog, merge when ready

#7391 [Named min timestamp leases] Min leased getter
  lock-api/src/main/java/com/palantir/lock/client/AuthenticatedInternalMultiClientConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/InternalMultiClientConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/MinLeasedTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/MinLeasedTimestampGetterImpl.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/NamespacedTimestampLeaseService.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/NamespacedTimestampLeaseServiceImpl.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirer.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirerImpl.java
Labels: no changelog, merge when ready

#7392 [Named min timestamp leases] Fix possible duplicated key issue
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/RemotingTimestampLeaseServiceAdapter.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/RemotingTimestampLeaseServiceAdapterTest.java
Labels: no changelog, merge when ready, 🤖 fix nits

#7395 Single `ReviewedRestrictedApiUsage` annotation
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/annotations/ReviewedRestrictedApiUsage.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
Labels: no changelog, merge when ready

#7399 Add new `atlasdb-commons-api` package
  atlasdb-api/build.gradle
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CachingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-commons-api/build.gradle
  atlasdb-commons-api/src/main/java/com/palantir/atlasdb/common/api/annotations/ReviewedRestrictedApiUsage.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/InstrumentedTimelockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  lock-api-objects/build.gradle
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  lock-api/src/main/java/com/palantir/lock/client/UnreliableTimeLockService.java
  settings.gradle
Labels: no changelog, merge when ready

#7397 [Named min timestamp leases] LegacyTimelockService.
  changelog/@unreleased/pr-7397.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimestampLeaseResult.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimestampLeaseResults.java
  lock-impl/build.gradle
  lock-impl/src/main/java/com/palantir/lock/impl/LegacyTimelockService.java
  lock-impl/src/test/java/com/palantir/lock/impl/LegacyTimelockServiceIntegrationTest.java
Labels: merge when ready

#7401 Fix develop semantic conflict
  lock-impl/src/test/java/com/palantir/lock/impl/LegacyTimelockServiceIntegrationTest.java
Labels: no changelog, merge when ready

#7396 [Named min timestamp leases] Add timestamp lease acquirer
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimestampLeaseResult.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimestampLeaseResults.java
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/client/LeasedLockToken.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirerImpl.java
  lock-api/src/test/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirerImplTest.java
  timelock-api/src/main/conjure/timelock-api.yml
Labels: no changelog, merge when ready

#7398 [Named min timestamp leases] Wiring it all except legacy
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultLockAndTimestampServiceFactory.java
  atlasdb-tests-shared/build.gradle
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/AbstractInMemoryTimelockExtension.java
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/InMemoryInternalMultiClientConjureTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/MinLeasedTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/NamespacedTimestampLeaseServiceImpl.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirer.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirerImpl.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
Labels: no changelog, autorelease, merge when ready

#7403 make hash rotation configurable
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKvsSerializableTransactionTest.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/AtlasDbConstants.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepQueueComponents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfo.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitioner.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/config/TargetedSweepRuntimeConfig.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/SingleBucketSweepTaskIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/AbstractSweepQueueTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/TargetedSweeperTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoPartitionerTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/queue/WriteInfoTest.java
Labels: autorelease, merge when ready

#7407 Allow registering closeables if already closed
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ThreadSafeCloser.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ThreadSafeCloserTest.java
Labels: autorelease, merge when ready

#7305 Add Lease Timestamps
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TimestampLeaseAwareTransaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TimestampLeaseAwareTransactionManager.java
  atlasdb-commons-api/build.gradle
  atlasdb-commons-api/src/main/java/com/palantir/atlasdb/common/api/timelock/TimestampLeaseName.java
  atlasdb-commons-api/src/test/java/com/palantir/atlasdb/common/api/timelock/TimestampLeaseNameTest.java
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/InstrumentedTimelockService.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionPreCommitActions.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionPreCommitActionsTest.java
  changelog/@unreleased/pr-7305.v2.yml
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimelockService.java
  lock-api-objects/src/main/java/com/palantir/lock/v2/TimestampLeaseResults.java
  lock-api/src/main/java/com/palantir/lock/client/ProfilingTimelockService.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
  lock-api/src/main/java/com/palantir/lock/client/TimeLockClient.java
  lock-api/src/main/java/com/palantir/lock/client/UnreliableTimeLockService.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/MinLeasedTimestampGetter.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/MinLeasedTimestampGetterImpl.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirer.java
  lock-api/src/main/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirerImpl.java
  lock-api/src/test/java/com/palantir/lock/client/timestampleases/TimestampLeaseAcquirerImplTest.java
  lock-impl/build.gradle
  lock-impl/src/main/java/com/palantir/lock/impl/LegacyTimelockService.java
  lock-impl/src/test/java/com/palantir/lock/impl/LegacyTimelockServiceIntegrationTest.java
  timelock-api/build.gradle
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/build.gradle
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/batch/RemotingTimestampLeaseServiceAdapter.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/AsyncLockService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/LockManager.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampLockCollection.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImplTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/MultiClientConjureTimelockResourceTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/batch/RemotingTimestampLeaseServiceAdapterTest.java
  timelock-impl/src/test/java/com/palantir/atlasdb/timelock/lock/NamedMinTimestampLockCollectionTest.java
Labels: autorelease, merge when ready

#7338 Remove dead DBKVS code, fix Oracle hints
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbQueryFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/OracleQueryFactory.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/PostgresQueryFactory.java
  changelog/@unreleased/pr-7338.v2.yml
Labels: autorelease, merge when ready

#7381 [ASTS] Telemetry part 2: Add placeholders to logs
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DynamicTaskScheduler.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultSweepAssignedBucketStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/DefaultBucketProgressStore.java
Labels: no changelog, merge when ready

#7412 Lease timestamps follow ups
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cleaner/api/Cleaner.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TimestampLeaseAwareTransaction.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TimestampLeaseAwareTransactionManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-commons-api/src/test/java/com/palantir/atlasdb/common/api/timelock/TimestampLeaseNameTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionPreCommitActions.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionPreCommitActionsTest.java
Labels: no changelog, merge when ready

#7380 [ASTS] Telemetry part 1: Single bucket sweep task
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTask.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSingleBucketSweepTaskTest.java
Labels: no changelog, merge when ready

#7382 [ASTS] Telemetry part 3: Coordinator
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/BackgroundTargetedSweeperFactory.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/BucketBasedTargetedSweeper.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSweepStateCoordinator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/locks/Lockable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/TargetedSweeper.java
  atlasdb-impl-shared/src/main/metrics/targeted-sweep.yml
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSweepStateCoordinatorTest.java
Labels: no changelog, merge when ready

#7384 [ASTS] State validation
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketAssignerState.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/InitialBucketAssignerStateMachineBootstrapTaskTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketAssignerStateTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketStateAndIdentifierPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketAssignerTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/AbstractDefaultSweepAssignedBucketStoreTest.java
Labels: no changelog, merge when ready

#7414 [ASTS] enable ASTS during antithesis tests
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/config/ConfigBuggifier.java
Labels: merge when ready

#7413 Upgrade to target compile 17
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/InMemoryKeyValueService.java
  atlasdb-console/src/main/groovy/com/palantir/atlasdb/console/AtlasConsoleMain.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/BenchmarkParam.java
  atlasdb-processors/src/main/java/com/palantir/processors/AutoDelegateProcessor.java
  build.gradle
  changelog/@unreleased/pr-7413.v2.yml
  commons-api/src/main/java/com/palantir/util/sql/SqlCallStats.java
  lock-api-objects/src/main/java/com/palantir/lock/ExpiringToken.java
  lock-api-objects/src/main/java/com/palantir/lock/SimpleTimeDuration.java
  versions.lock
  versions.props
Labels: merge when ready

#7409 Move `onCommitOrAbort` to `Transaction`
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/Transaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/CallbackAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingCallbackAwareTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ForwardingTransaction.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/transaction/impl/ReadTransactionShould.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/GetAsyncExpectationAwareDelegate.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/WrapperWithTracker.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AsyncSnapshotTransactionTest.java
Labels: no changelog, merge when ready

#7416 [Named min timestamp leases] Fix break in RemoteTimelockServiceAdapter
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  lock-api/src/main/java/com/palantir/lock/client/RemoteTimelockServiceAdapter.java
Labels: no changelog, merge when ready
