Repository palantir/atlasdb, pull requests merged in 2024-09, with the labels that each got.

#7253 Bump timelock pdep version
  lock-api-objects/build.gradle
Labels: no changelog, autorelease, merge when ready

#7220 [ASTS][Bucket Retriever] Debouncing bucket retrieval requests
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/CandidateSweepableBucketRetriever.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultCandidateSweepableBucketRetriever.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultCandidateSweepableBucketRetrieverTest.java
Labels: no changelog, merge when ready

#7227 [ASTS] A somewhat random iterator, for the coordinator.
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ProbingRandomIterator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/ProbingRandomIteratorTest.java
Labels: no changelog, merge when ready

#7228 [ASTS] Sweep State Coordinator
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultSweepStateCoordinator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultSweepStateCoordinatorTest.java
Labels: no changelog, merge when ready

#7243 Asynchronously remove state from LockWatchValueScopingCacheImpl
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCache.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerInternal.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKeyValueServiceIntegrationTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImplTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  changelog/@unreleased/pr-7243.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/TransactionStarterHelper.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCache.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCacheImpl.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchValueCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchValueCache.java
  lock-api/src/test/java/com/palantir/lock/client/MultiClientTransactionStarterTest.java
  lock-api/src/test/java/com/palantir/lock/watch/LockWatchCacheImplTest.java
Labels: autorelease, merge when ready

#7252 Avoid allocating table reference args
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTableMetadata.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ReadTransaction.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/DbKvs.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/snapshot/DefaultKeyValueSnapshotReader.java
Labels: autorelease, merge when ready

#7259 feat(bucket-assigner): Bucket assigner state machine ADT
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketAssignerState.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketAssignerStateTest.java
Labels: no changelog, merge when ready

#7261 [ASTS][Bucket assigner+] Table defs
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketAssignerStateMachineTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketPointerTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/SweepBucketsTable.java
Labels: no changelog

#7249 Set statement_timeout on postgres
  atlasdb-container-test-utils/src/main/resources/docker-compose-cassandra-three-node.yml
  atlasdb-container-test-utils/src/main/resources/docker-compose-cassandra.yml
  atlasdb-container-test-utils/src/main/resources/docker-compose-cassandra2.yml
  atlasdb-container-test-utils/src/test/resources/docker-compose-nginx1.yml
  atlasdb-container-test-utils/src/test/resources/docker-compose-nginx2.yml
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/ConnectionConfig.java
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/PostgresConnectionConfig.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/nexus/db/pool/HikariCpConnectionManagerTest.java
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.postgres.yml
  atlasdb-ete-tests/docker-compose.multi-client-with-postgres-timelock-and-postgres.yml
  atlasdb-ete-tests/docker-compose.multi-client-with-timelock-and-cassandra.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-cassandra.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-postgres.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-three-node-cassandra.yml
  atlasdb-ete-tests/docker-compose.timelock-migration.cassandra.yml
  atlasdb-ete-tests/docker-compose.timelock-migration.dbkvs.yml
  atlasdb-ete-tests/src/test/resources/cassandra-docker-compose.yml
  atlasdb-perf/src/main/resources/cassandra-docker-compose.yml
  atlasdb-perf/src/main/resources/postgres-docker-compose.yml
  atlasdb-workload-server-antithesis/var/docker-compose.yml
  changelog/@unreleased/pr-7249.v2.yml
  scripts/circle-ci/common-containers.yml
  timelock-server/src/testCommon/resources/docker-compose.yml
Labels: autorelease, merge when ready

#7199 [ASTS] Bucket Storage I: Resolving Pending Schema Changes
  atlasdb-ete-test-utils/src/main/java/com/palantir/atlasdb/todo/generated/SnapshotsStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/DataStreamStore.java
  atlasdb-ete-tests/src/main/java/com/palantir/atlasdb/blob/generated/HotspottyDataStreamStore.java
  atlasdb-perf/src/main/java/com/palantir/atlasdb/performance/schema/generated/ValueStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/StreamTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestMaxMemStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/StreamTestWithHashStreamStore.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/stream/generated/TestHashComponentsStreamStore.java
  examples/profile-client/src/main/java/com/palantir/example/profile/schema/generated/UserPhotosStreamStore.java
Labels: no changelog

#7200 [ASTS] Bucket Storage II: Defining the Per Bucket Progress Table
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/TargetedSweepSchema.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/generated/SweepBucketProgressTable.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/generated/TargetedSweepTableFactory.java
Labels: no changelog

#7201 [ASTS] Bucket Storage III: Bucket Progress and Persistence
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/BucketProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/BucketProgressPersister.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/progress/BucketProgressPersisterTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/progress/BucketProgressTest.java
Labels: no changelog

#7263 feat(bucket-assigner): Bucket Writer
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/BucketWriter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketWriter.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketWriterTest.java
Labels: merge when ready

#7203 [ASTS] Bucket Storage IV: DefaultBucketKeySerializer
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/BucketProgress.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/progress/DefaultBucketKeySerializer.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/progress/BucketProgressTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/progress/DefaultBucketKeySerializerTest.java
Labels: no changelog

#7205 [ASTS] Bucket Storage VI: Concrete KVS DefaultBucketProgressStore Integration Tests
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraDefaultBucketProgressStoreTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/oracle/DbKvsOracleDefaultBucketProgressStoreTest.java
  atlasdb-dbkvs-tests/src/test/java/com/palantir/atlasdb/keyvalue/dbkvs/impl/postgres/DbKvsPostgresDefaultBucketProgressStoreTest.java
Labels: no changelog, merge when ready

#7264 Make log helper function "collectionOfHosts" less error prone
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelperTest.java
Labels: no changelog, autorelease, merge when ready

#7275 [PDS-594882] Bump timestamp cache size limit to 100k
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStore.java
Labels: no changelog, autorelease, merge when ready

#7229 Instrumentation does not mark a metric series per failure exception
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/InstrumentationUtils.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/SlidingWindowMetricsInvocationHandler.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/TaggedMetricsInvocationEventHandler.java
  atlasdb-client/src/test/java/com/palantir/atlasdb/util/InstrumentationUtilsTest.java
Labels: no changelog, merge when ready

#7232 No expectations metrics unless on a debug log level
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ExpectationsMetricsReporter.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
Labels: merge when ready

#7272 feat(bucket-assigner): Closing time calculator
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculator.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/bucketingthings/DefaultBucketCloseTimestampCalculatorTest.java
Labels: no changelog, merge when ready

#7279 fix: update name in generated code
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/generated/SweepBucketProgressTable.java
  changelog/@unreleased/pr-7279.v2.yml
Labels: merge when ready

#7234 Do not track metrics for the non-sweepable sweep strategy
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/SweeperStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/metrics/TargetedSweepMetrics.java
Labels: merge when ready

#7282 Add tracing to #putUnlessExists.
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingCassandraClient.java
Labels: autorelease, merge when ready

#7241 Re-wire `InstrumentedCassandraClient` telemetry in c* pooling setup
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientInstrumentation.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/InstrumentedCassandraClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/UnfilteredCassandraClientInstrumentation.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraServiceTest.java
Labels: no changelog, merge when ready, 🤖 fix nits

#7287 enable antithesis again
  .circleci/config.yml
Labels: no changelog, merge when ready

#7246 Define background updating top list counter
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TopListFilteredCounter.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/TopListFilteredCounterTest.java
Labels: no changelog, merge when ready

#7286 Top list counter review follow-up
  .palantir/revapi.yml
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactory.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientMetrics.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientMetricsUtils.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolingContainer.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/FilteredCassandraClientMetrics.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/InstrumentedCassandraClient.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/UnfilteredCassandraClientMetrics.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/pool/CassandraService.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientFactoryTest.java
Labels: no changelog, autorelease, merge when ready, 🤖 fix nits

#7298 fix: run all tests rather than stopping on first failure locally
  changelog/@unreleased/pr-7298.v2.yml
  gradle/shared.gradle
Labels: merge when ready

#7293 Do not fail when query contains duplicate row with local write
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/snapshot/KeyValueSnapshotReader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/snapshot/DefaultKeyValueSnapshotReader.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractTransactionTest.java
  changelog/@unreleased/pr-7293.v2.yml
Labels: autorelease, merge when ready

#7296 Improve index conflict handler validation
  atlasdb-client/src/main/java/com/palantir/atlasdb/table/description/Schema.java
Labels: no changelog, autorelease

#7292 trigger antithesis after each release
  .circleci/config.yml
Labels: no changelog, autorelease, merge when ready

#7299 [ASTS] feat(bucket-assigner): Add underlying physical table
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/TargetedSweepSchema.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/generated/SweepAssignedBucketsTable.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/schema/generated/TargetedSweepTableFactory.java
Labels: no changelog, merge when ready
