Repository palantir/atlasdb, pull requests merged in 2024-06, with the labels that each got.

#7076 [KeyValueSnapshotReader Phase II] Part 9: Introducing KeyValueSnapshotReader
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/snapshot/KeyValueSnapshotReader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/snapshot/DefaultKeyValueSnapshotReader.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
Labels: no changelog, autorelease, merge when ready

#7133 [PDS-543497] Permit 2 DC setups where one of the DCs has less than expected replication
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifierTest.java
  changelog/@unreleased/pr-7133.v2.yml
Labels: autorelease, merge when ready

#7120 Update Oracle, JDBC drivers
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
  changelog/@unreleased/pr-7120.v2.yml
  versions.lock
  versions.props
Labels: merge when ready

#7143 Make DdlManager accessible from a TransactionManager
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/cell/api/DdlManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/TransactionManager.java
  atlasdb-client/src/main/java/com/palantir/atlasdb/keyvalue/impl/DelegatingDdlManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  changelog/@unreleased/pr-7143.v2.yml
Labels: autorelease, merge when ready

#7144 Add exception when transactions are retried
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionRetryStrategy.java
  changelog/@unreleased/pr-7144.v2.yml
Labels: merge when ready

#7134 TKVSM initialization handles when runtimeConfig is provided as a Supplier
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-7134.v2.yml
Labels: merge when ready

#7142 [KeyValueSnapshotReaderManager] Part 2: Wire up KeyValueSnapshotReaderManager
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/TransactionManagerModule.java
  atlasdb-dagger/src/main/java/com/palantir/atlasdb/services/test/TestTransactionManagerModule.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManager.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AbstractSerializableTransactionTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TestTransactionManagerImpl.java
  atlasdb-tests-shared/src/main/java/com/palantir/atlasdb/transaction/impl/TransactionTestSetup.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/AtlasDbTestCase.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/TableMigratorTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/FakeTransactionKeyValueServiceManager.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SerializableTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/SnapshotTransactionManagerTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TestKeyValueSnapshotReaderManagers.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/TransactionManagerTest.java
  changelog/@unreleased/pr-7142.v2.yml
Labels: autorelease, merge when ready

#7122 Adding logs to debug lock refreshing
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureTimelockServiceImpl.java
Labels: no changelog, autorelease, merge when ready

#7149 Log tables when calls to c* fail
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraKeyValueServiceImpl.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/TracingQueryRunner.java
Labels: no changelog, merge when ready

#7152 Fix the Develop Build
  .palantir/revapi.yml
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/build.gradle
Labels: do not merge, no changelog

#7155 cacheableTablePredicate-dependent table lookups during table creation in KvTableMappingService
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingService.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/TableRemappingKeyValueServiceTest.java
  changelog/@unreleased/pr-7155.v2.yml
Labels: autorelease, merge when ready

#7161 Add namespace parameter to getLockState
  .palantir/revapi.yml
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/timelock/TimeoutSensitiveLockRpcClient.java
  changelog/@unreleased/pr-7161.v2.yml
  lock-api/src/main/java/com/palantir/lock/LockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/client/DialogueComposingLockRpcClient.java
  lock-api/src/main/java/com/palantir/lock/client/NamespaceAgnosticLockClientAdaptor.java
Labels: autorelease, merge when ready

#7118 Reduce allocations in VersionedEventStore#retentionEvents
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEvents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  changelog/@unreleased/pr-7118.v2.yml
Labels: autorelease, merge when ready

#7164 Remove obsolete performance trace logging
  atlasdb-client/build.gradle
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  changelog/@unreleased/pr-7164.v2.yml
  versions.lock
Labels: merge when ready

#7132 Timelock uses tritium-preprocessor instrumentation
  atlasdb-client/src/main/java/com/palantir/atlasdb/util/AtlasDbMetrics.java
  changelog/@unreleased/pr-7132.v2.yml
  lock-api/build.gradle
  lock-api/src/main/java/com/palantir/lock/LockService.java
  timelock-agent/build.gradle
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponents.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/LeadershipContextFactory.java
  timelock-agent/src/main/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetrics.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/AsyncTimeLockServicesCreator.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/LeadershipComponentsTest.java
  timelock-agent/src/test/java/com/palantir/atlasdb/timelock/paxos/TimelockLeadershipMetricsTest.java
  timelock-impl/build.gradle
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockService.java
  versions.lock
Labels: autorelease, merge when ready

#7165 updated gradle-docker to support gradle8
  build.gradle
Labels: no changelog, merge when ready
