Repository palantir/atlasdb, pull requests merged in 2024-04, with the labels that each got.

#7073 Use Eclipse collections impl factories
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTable.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/queue/SweepableCells.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/ReadValidationCommitTimestampLoader.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SerializableTransaction.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/DefaultCommitTimestampLoaderTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/ReadValidationCommitTimestampLoaderTest.java
  changelog/@unreleased/pr-7073.v2.yml
Labels: autorelease, merge when ready

#7077 [PDS-510479] Table names must go through LoggingArgs
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
  changelog/@unreleased/pr-7077.v2.yml
Labels: autorelease, merge when ready

#7078 Reduce map entry allocations computing filtered map size
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  changelog/@unreleased/pr-7078.v2.yml
Labels: autorelease, merge when ready

#7085 Fix duplicate key error in RetryableCassandraRequest
  .palantir/revapi.yml
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/RetryLimitReachedException.java
  atlasdb-api/src/test/java/com/palantir/atlasdb/keyvalue/api/RetryLimitReachedExceptionTest.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/RetryableCassandraRequest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/atomic/ResilientCommitTimestampAtomicTableTest.java
Labels: no changelog, autorelease, merge when ready

#7089 Prefer AssertJ
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKeyValueServiceIntegrationTest.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidatorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/impl/KvTableMappingServiceTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/metrics/LastSweptTimestampUpdaterTest.java
Labels: no changelog, merge when ready

#7062 Use ServicesConfigBlock.empty
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/LockServices.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-config/src/test/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProviderTest.java
  atlasdb-jepsen-tests/src/main/java/com/palantir/atlasdb/http/TimelockUtils.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/factory/TransactionManagersTest.java
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: no changelog, merge when ready

#7081 Initialize eclipse-collections classes to avoid JDK classload deadlock
  atlasdb-commons/build.gradle
  atlasdb-commons/src/main/java/com/palantir/util/EclipseCollections.java
  atlasdb-commons/src/test/java/com/palantir/util/EclipseCollectionsTest.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  changelog/@unreleased/pr-7081.v2.yml
Labels: autorelease, merge when ready
