Repository palantir/atlasdb, pull requests merged in 2024-01, with the labels that each got.

#6902 Boy/junit5 revive
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/CommitLockTest.java
  timelock-server/src/integ2Test/java/com/palantir/atlasdb/timelock/AbstractMultiNodePaxosTimeLockServerIntegrationTest.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/NamespacedClients.java
Labels: no changelog, merge when ready

#6903 Improve ObjectMapper instantiation for timelock-server
  atlasdb-cassandra/build.gradle
  atlasdb-config/build.gradle
  atlasdb-dbkvs/build.gradle
  atlasdb-processors/build.gradle
  timelock-server/build.gradle
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/TimeLockServerLauncher.java
  timelock-server/src/main/java/com/palantir/atlasdb/timelock/logging/NonBlockingFileAppenderFactory.java
  timelock-server/src/testCommon/java/com/palantir/atlasdb/timelock/TimeLockServerHolder.java
  versions.lock
Labels: no changelog, autorelease, merge when ready

#6905 bump auto service
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceConfig.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/cassandra/CassandraKeyValueServiceRuntimeConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceConfig.java
  atlasdb-dbkvs/src/main/java/com/palantir/atlasdb/keyvalue/dbkvs/DbKeyValueServiceRuntimeConfig.java
  versions.props
Labels: no changelog, merge when ready

#6899 Useful safe logging for cache precondition failure
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
Labels: no changelog, autorelease, merge when ready

#6912 fix: Undo atlasdb-cassandra dependency removal
  atlasdb-workload-server-distribution/build.gradle
  changelog/@unreleased/pr-6912.v2.yml
Labels: autorelease, merge when ready

#6918 [Antithesis] Fix false positives in SummaryRowsWorkflow
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflows.java
Labels: no changelog

#6919 [Antithesis] Run workloads in a random order + allow running of just one workload
  atlasdb-workload-server-distribution/build.gradle
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/config/WorkflowExecutionConfiguration.java
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/config/WorkloadServerInstallConfiguration.java
  atlasdb-workload-server-distribution/src/test/resources/workload-server.yml
  atlasdb-workload-server-distribution/var/conf/workload-server.yml
Labels: no changelog, autorelease, merge when ready

#6830 [Antithesis] Buggify - randomly fast forward timestamps
  .palantir/revapi.yml
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultLockAndTimestampServiceFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TransactionManagers.java
  atlasdb-workload-server/build.gradle
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/UnreliableTimestampManager.java
  atlasdb-workload-server/src/test/java/com/palantir/atlasdb/workload/store/UnreliableTimestampManagerTest.java
  changelog/@unreleased/pr-6830.v2.yml
  lock-api/src/main/java/com/palantir/lock/client/RandomizedTimestampManager.java
  lock-api/src/main/java/com/palantir/lock/client/UnreliableTimeLockService.java
  lock-api/src/test/java/com/palantir/lock/client/UnreliableTimelockClientTest.java
Labels: merge when ready

#6801 Improve alter table documentation searchability and error case debugging
  docs/source/configuration/key_value_service_configs/oracle_key_value_service_config.rst
Labels: merge when ready

#6922 improvement: Enable remote debugging on workload server
  atlasdb-workload-server-antithesis/var/docker-compose.yml
  atlasdb-workload-server-distribution/build.gradle
  changelog/@unreleased/pr-6922.v2.yml
Labels: merge when ready

#6920 Oracle 19.22
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
  changelog/@unreleased/pr-6920.v2.yml
Labels: merge when ready

#6930 [Antithesis] Fill in missing execution config to configuration with TimeLock and Cassandra
  atlasdb-workload-server-distribution/var/conf/workload-server.timelock.cassandra.yml
  changelog/@unreleased/pr-6930.v2.yml
Labels: merge when ready

#6932 improvement: Verify Antithesis workload server image starts up correctly
  .circleci/config.yml
  atlasdb-workload-server-antithesis/build.gradle
  atlasdb-workload-server-antithesis/src/test/java/AntithesisDockerTest.java
  atlasdb-workload-server-antithesis/tag-test-images.sh
  atlasdb-workload-server-distribution/src/main/java/com/palantir/atlasdb/workload/WorkloadServerLauncher.java
  changelog/@unreleased/pr-6932.v2.yml
  scripts/circle-ci/run-circle-tests.sh
Labels: autorelease, merge when ready

#6921 improvement: Fast forward timestamp to be able to use txn3
  atlasdb-workload-server/build.gradle
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
  changelog/@unreleased/pr-6921.v2.yml
Labels: autorelease, merge when ready

#6935 fix 17
  atlasdb-workload-server-distribution/Dockerfile
Labels: no changelog, merge when ready

#6937 fix : Revert fast forwarding of timestamp on workload server
  atlasdb-workload-server/build.gradle
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/store/AtlasDbTransactionStoreFactory.java
  changelog/0.1018.0/pr-6921.v2.yml
  changelog/@unreleased/pr-6937.v2.yml
Labels: autorelease, merge when ready

#6934 [Antithesis] Fix race condition in transient rows workflow
  atlasdb-workload-server/src/main/java/com/palantir/atlasdb/workload/workflow/TransientRowsWorkflows.java
  changelog/@unreleased/pr-6934.v2.yml
Labels: autorelease, merge when ready

#6926 Supporting pre-commit conditions that can use the mutation map to verify things
  atlasdb-api/src/main/java/com/palantir/atlasdb/transaction/api/PreCommitCondition.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/SnapshotTransaction.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AbstractSnapshotTransactionTest.java
Labels: no changelog, autorelease, merge when ready
