Repository palantir/atlasdb, pull requests merged in 2024-08, with the labels that each got.

#7215 Bump CI Oracle image to 19.24
  atlasdb-dbkvs-tests/src/test/resources/docker-compose.oracle.yml
  atlasdb-ete-tests/docker-compose.single-client-with-embedded-and-oracle.yml
  changelog/@unreleased/pr-7215.v2.yml
Labels: merge when ready

#7223 fix(bucket-retriever): Fix flaky tests by removing dependency on sleeping in tests
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ShardedSweepableBucketRetriever.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/ShardedSweepableBucketRetrieverTest.java
Labels: merge when ready, 🤖 fix nits

#7158 Don't retry lock request in lock condition
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/transaction/impl/AdvisoryLockConditionSuppliers.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/transaction/impl/AdvisoryLocksConditionTest.java
  changelog/@unreleased/pr-7158.v2.yml
Labels: autorelease, merge when ready

#7222 Set target server type primary
  atlasdb-dbkvs-hikari/src/main/java/com/palantir/nexus/db/pool/config/PostgresConnectionConfig.java
  changelog/@unreleased/pr-7222.v2.yml
Labels: autorelease, merge when ready

#7217 Trigger the TimeLock diagnostics RPC on `LockWatchManager::logState`
  .palantir/revapi.yml
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/AtlasDbDialogueServiceProvider.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/DefaultLockAndTimestampServiceFactory.java
  atlasdb-config/src/main/java/com/palantir/atlasdb/factory/TimeLockHelperServices.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImplTest.java
  atlasdb-tests-shared/src/main/java/com/palantir/timelock/paxos/AbstractInMemoryTimelockExtension.java
  lock-api/src/main/java/com/palantir/lock/client/LockWatchTimeLockDiagnosticsLogger.java
  lock-api/src/main/java/com/palantir/lock/client/NamespacedConjureLockWatchTimeLockDiagnosticsService.java
Labels: no changelog, autorelease, merge when ready

#7224 Update intial capacity to avoid cache contention
  atlasdb-client/src/main/java/com/palantir/atlasdb/transaction/impl/ConflictDetectionManager.java
  changelog/@unreleased/pr-7224.v2.yml
Labels: autorelease, merge when ready, 🤖 fix nits

#7245 TableReference#createFromFullyQualifiedName uses Namespace.createUnchecked
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/Namespace.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/TableReference.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/NamespaceTest.java
  atlasdb-tests-shared/src/test/java/com/palantir/atlasdb/schema/NamespaceTest.java
  changelog/@unreleased/pr-7245.v2.yml
Labels: merge when ready
