Repository palantir/atlasdb, pull requests merged in 2024-07, with the labels that each got.

#7168 Remove Jackson byte[] workaround
  atlasdb-client/src/main/java/com/palantir/atlasdb/persister/JacksonPersister.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/internalschema/persistence/InternalSchemaMetadataPayloadCodec.java
  changelog/@unreleased/pr-7168.v2.yml
Labels: merge when ready

#7170 switch to `using` instead of `with` since it is deprecated
  build.gradle
Labels: no changelog, merge when ready

#7174 Revert "Reduce allocations in VersionedEventStore#retentionEvents"
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEvents.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  changelog/@unreleased/pr-7174.v2.yml
Labels: autorelease, merge when ready

#7159 getActiveNamespaces tracks active namespaces with expiry
  timelock-api/src/main/conjure/timelock-management-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/TimelockNamespaces.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/management/TimeLockManagementResource.java
Labels: no changelog, autorelease, merge when ready

#7176 Add coverage for #7118 code path
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStoreTest.java
Labels: merge when ready

#7179 [ASTS] feat(bucket-retrieval): Interfaces
  atlasdb-impl-shared/build.gradle
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/CandidateSweepableBucketRetriever.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ShardedRetrievalStrategy.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ShardedSweepTimestampManager.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/SweepStateCoordinator.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/SweepableBucketRetriever.java
Labels: merge when ready

#7181 [ASTS] feat(bucket-retrieval): Fault tolerant sharded retrieval strategy
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/FaultTolerantShardedRetrievalStrategy.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DefaultParallelTaskExecutorTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/FaultTolerantShardedRetrievalStrategyTest.java
Labels: no changelog, merge when ready

#7183 [ASTS] feat(bucket-retrieval): Dynamic Task Scheduler for updating bucket list
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DynamicTaskScheduler.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/DynamicTaskSchedulerTest.java
Labels: no changelog, merge when ready

#7184 [ASTS] feat(bucket-retrieval): Sweep timestamp manager
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/DefaultShardedSweepTimestampManager.java
Labels: no changelog, merge when ready

#7189 Improve CassandraVerifier logs
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraVerifier.java
Labels: no changelog, merge when ready

#7195 Remove mapping cassandra server objects to hostname strings before logging
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraLogHelper.java
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraTopologyValidator.java
Labels: no changelog, autorelease, merge when ready

#7196 Do not leak Cassandra containers when topology validation fails
  atlasdb-cassandra/src/main/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolImpl.java
  atlasdb-cassandra/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/CassandraClientPoolTest.java
Labels: no changelog, autorelease, merge when ready

#7202 disable antithesis workflow
  .circleci/config.yml
Labels: no changelog, merge when ready

#7182 [ASTS] feat(bucket-retrieval): Sharded sweepable bucket retriever
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/ShardedSweepableBucketRetriever.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/SweepableBucketRetriever.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/ShardedSweepableBucketRetrieverTest.java
Labels: merge when ready

#7185 [ASTS] feat(bucket-retrieval): Lockables
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/sweep/asts/locks/Lockable.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/locks/LockableTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/locks/TestLockable.java
Labels: merge when ready

#7212 missing spotless
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKeyValueServiceIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/sweep/asts/locks/LockableTest.java
Labels: merge when ready

#7214 add circle-all task
  .circleci/config.yml
Labels: no changelog, merge when ready

#7213 Log servers when checking the new service invariant
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
Labels: autorelease, merge when ready

#7194 Add endpoint API definition to dump timelock lock watch internals
  timelock-agent/src/main/java/com/palantir/timelock/paxos/TimeLockAgent.java
  timelock-api/src/main/conjure/timelock-api.yml
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/AsyncTimelockServiceImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/ConjureLockWatchDiagnosticsResource.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLog.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingService.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockWatchingServiceImpl.java
Labels: no changelog, autorelease, merge when ready

#7192 Expose a lock watch manager dump state method
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManager.java
  atlasdb-api/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/NoOpLockWatchManager.java
  atlasdb-cassandra-integration-tests/src/test/java/com/palantir/atlasdb/keyvalue/cassandra/AbstractCassandraKeyValueServiceIntegrationTest.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/FilteringValueCacheSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/LockWatchValueScopingCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/SnapshotStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueCacheSnapshotImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/cache/ValueStoreImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshot.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLog.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchManagerImpl.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStore.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/TimestampStateStoreState.java
  atlasdb-impl-shared/src/main/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStore.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/ClientLockWatchSnapshotTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/DuplicatingLockWatchEventCache.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventCacheIntegrationTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/LockWatchEventLogTest.java
  atlasdb-impl-shared/src/test/java/com/palantir/atlasdb/keyvalue/api/watch/VersionedEventStoreTest.java
  lock-api/src/main/java/com/palantir/lock/client/LeasedLockToken.java
  lock-api/src/main/java/com/palantir/lock/client/LockTokenShare.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCache.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchCacheImpl.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/LockWatchValueCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchEventCache.java
  lock-api/src/main/java/com/palantir/lock/watch/NoOpLockWatchValueCache.java
Labels: no changelog, merge when ready

#7190 Expose endpoint to dump timelock lock watch internals
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/ArrayLockEventSlidingWindow.java
  timelock-impl/src/main/java/com/palantir/atlasdb/timelock/lock/watch/LockEventLogImpl.java
Labels: no changelog, autorelease, merge when ready
